### ISSUE TITLE
Improve Error handling when "IP of Istio Ingressgateway could not be derived"

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#1003]
DISCLAIMER: This might not classify as a real bug, but the issue-template for bugs still applies

**Environment**

* Client OS (e.g., Linux, OSX, Windows): Ubuntu 18.04
* Keptn Version (`keptn version`): latest version of develop branch (2019, Oct 22nd)
* Kubernetes Cloud Provider (e.g., GKE, AKS): GKE
* Kubernetes version (`kubectl version`):
  ```
  Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.10-gke.0", GitCommit:"569511c9540f78a94cc6a41d895c382d0946c11a", GitTreeState:"clean", BuildDate:"2019-08-21T23:28:44Z", GoVersion:"go1.11.13b4", Compiler:"gc", Platform:"linux/amd64"}
  ```

**Affected Component**

* [ ] Docs
* [ ] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [x] Istio
* [ ] Bridge
* [ ] Gatekeeper
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**

When installing keptn on GKE, I experienced an issue with not receiving an IP address for the istio ingress gateway within the specified time, which lead to the following error message:
```
IP of Istio Ingressgateway could not be derived.
Error occured with message: [keptn|ERROR] [2019-10-22 15:14:27] IP of Istio Ingressgateway could not be derived.
```

**To Reproduce**

Disclaimer: This won't be easily reproducible as usually the external IP address for the load balancer is already set when the relevant part of the code is reached.

1. Create a new GKE kubernetes cluster
2. Run ``keptn install --keptn-version=develop --verbose``
3. Wait
4. Experience the error
```
Installing Keptn
Deployment nats-operator in keptn namespace available.
Retry: 1/4 - Wait 5s for hostname of Istio Ingressgateway to be available ...
Retry: 2/4 - Wait 5s for hostname of Istio Ingressgateway to be available ...
Retry: 3/4 - Wait 5s for hostname of Istio Ingressgateway to be available ...
Retry: 4/4 - Wait 5s for hostname of Istio Ingressgateway to be available ...
Could not get ingress gateway domain name. Trying to retrieve IP address instead.
Retry: 1/4 - Wait 5s for ip of Istio Ingressgateway to be available ...
Retry: 2/4 - Wait 5s for ip of Istio Ingressgateway to be available ...
Retry: 3/4 - Wait 5s for ip of Istio Ingressgateway to be available ...
Retry: 4/4 - Wait 5s for ip of Istio Ingressgateway to be available ...
IP of Istio Ingressgateway could not be derived.
Error occured with message: [keptn|ERROR] [2019-10-22 15:14:27] IP of Istio Ingressgateway could not be derived.
```
The relevant part of the code is here:
https://github.com/keptn/keptn/blob/ab314b48ed0e1856bd0fa24a1b72a38803c88004/installer/scripts/common/setupKeptn.sh#L23-L33

Debugging using ``kubectl get svc istio-ingressgateway -o json -n istio-system | jq -r .status.loadBalancer.ingress[0].ip`` revelead a response of `Null`.

Further debugging using ``kubectl get svc -n istio-system`` revealed the following
```
                   TYPE           CLUSTER-IP    EXTERNAL-IP      PORT(S)                                                                                                                                      AGE
istio-citadel            ClusterIP      10.0.61.0     <none>           8060/TCP,15014/TCP                                                                                                                           30m
istio-ingressgateway     LoadBalancer   10.0.63.137   <Pending>   15020:31225/TCP,80:31380/TCP,443:31390/TCP,31400:31400/TCP,15029:31873/TCP,15030:32599/TCP,15031:30033/TCP,15032:31166/TCP,15443:32358/TCP   30m
istio-pilot              ClusterIP      10.0.49.83    <none>           15010/TCP,15011/TCP,8080/TCP,15014/TCP                                                                                                       30m
istio-sidecar-injector   ClusterIP      10.0.54.21    <none>           443/TCP  
```
After some time (1 to 5 minutes) the ingress gateway did finally receive an IP Address.

**Expected behavior**
Obviously, the expected behaviour would be that everything works ;) But that was not the case as there was a problem with GKE.

In the case of such a problem occuring again (or generally for debugging problem with ingress gateways), I would expect the following:

1. Watch the output of `kubectl get svc istio-ingressgateway -n istio-system` External IP, e.g., using
  ```bash
  kubectl get svc istio-ingressgateway -n istio-system -o jsonpath="{.status.loadBalancer.ingress[0].ip}"
  ```
2. Increase the timeout to 2 minutes (and let the user know that we are waiting for an IP address)
3. Show more debug information

**Current behavior**
After 20 seconds waiting for a hostname and 20 seconds waiting for an IP, the installation fails with the following error message: 
```
Error occured with message: [keptn|ERROR] [2019-10-22 15:14:27] IP of Istio Ingressgateway could not be derived.
```

**Additional context**

* GKE Indicent Report: https://status.cloud.google.com/incident/container-engine/19010
* Google Networking Incident Report: https://status.cloud.google.com/incident/cloud-networking/19020

**Comment by johnrusaw** [comment]
I was also receiving this "IP of Istio Ingressgateway could not be derived" message during the keptn install.

**Environment**
- Client OS (e.g., Linux, OSX, Windows): Amazon Linux 2
- Keptn Version (keptn version): CLI version: 0.5.0
- Kubernetes Cloud Provider (e.g., GKE, AKS): EKS
- Kubernetes version (kubectl version):
```
Client Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.7-eks-1861c5", GitCommit:"1861c597586f84f1498a9f2151c78d8a6bf47814", GitTreeState:"clean", BuildDate:"2019-09-24T22:12:08Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Problem**
My problem is that the EXTERNAL-IP for istio-ingressgateway LoadBalancer is perpetually in a \<Pending\> state (did not go away after either 2 or 5 minutes).  Per some Istio documentation that I found at https://istio.io/docs/tasks/traffic-management/ingress/ingress-control/#determining-the-ingress-ip-and-ports I see...
> If the EXTERNAL-IP value is \<none\> (or perpetually \<pending\>), your environment does not provide an external load balancer for the ingress gateway. In this case, you can access the gateway using the service’s node port.

It doesn't seem like the code snippet at... https://github.com/keptn/keptn/blob/ab314b48ed0e1856bd0fa24a1b72a38803c88004/installer/scripts/common/setupKeptn.sh#L23-L38 handles this, unless "$GATEWAY_TYPE" == "NodePort".  Please explain how this "$GATEWAY_TYPE" is determined or if I'm supposed to set it somehow or pass it to the install script.

Thank you.

**Comment by christian-kreuzberger-dtx** [comment]
Hi and thanks for your feedback.

Basically for EKS we do can not use the external IP, but we need a Domain. Keptn handles this during the installation by setting the parameter
```console
keptn install --platform=eks
```
after that you need to [configure your domain](https://keptn.sh/docs/0.5.0/installation/setup-keptn/#configure-a-custom-domain-required-for-eks) using

```console
keptn configure domain YOUR_DOMAIN
```

**Comment by agrimmer** [comment]
Correct. In EKS we do not get an IP but a hostname of the ELB.
Which install command did you use?

**Comment by johnrusaw** [comment]
I used the following command...
`keptn install --platform=eks`
and received the following results...
```
Using a file-based storage for the key because the password-store seems to be not set up.
Deploying keptn installer pod...
Installer pod deployed successfully.
Getting logs of pod installer-46b4x
Starting installation of Keptn
Testing connection to Kubernetes API
Connection to Kubernetes API successful
Installing Istio
Installing Istio done
Installing Tiller
Installing Tiller done
Installing Keptn
Could not get ingress gateway domain name. Trying to retrieve IP address instead.
IP of Istio Ingressgateway could not be derived.
Error occured with message: [keptn|ERROR] [2020-01-14 19:47:07] IP of Istio Ingressgateway could not be derived.
Installing Keptn failed.
Error occured with message: [keptn|ERROR] [2020-01-14 19:47:07] Installing Keptn failed.
Stopping keptn installation. Already created resources are not deleted; execute the uninstallKeptn.sh script to clean-up.
Error occured with message: [keptn|ERROR] [2020-01-14 19:47:07] Stopping keptn installation. Already created resources are not deleted; execute the uninstallKeptn.sh script to clean-up.
Error: keptn installation was unsuccessful
```

Running this gets null...
'kubectl get svc istio-ingressgateway -o json -n istio-system | jq -r .status.loadBalancer.ingress[0].ip'

Running this...
'kubectl get svc istio-ingressgateway -n istio-system'
gets pending for LoadBalancer, like so...
'''
NAME                   TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)                                                                                                                                      AGE
istio-ingressgateway   LoadBalancer   ###.##.##.##   <pending>     15020:30756/TCP,80:31380/TCP,443:31390/TCP,31400:31400/TCP,15029:30096/TCP,15030:32568/TCP,15031:31779/TCP,15032:30759/TCP,15443:32654/TCP   21h
'''

**Comment by johnrusaw** [comment]
So maybe the problem is in trying to get the hostname of the ELB.

After looking at the following code in the "release-0.5.0"...
https://github.com/keptn/keptn/blob/release-0.5.0/installer/scripts/common/setupKeptn.sh#L16-L34
which looks the same as master...
https://github.com/keptn/keptn/blob/master/installer/scripts/common/setupKeptn.sh#L16-L34

I can see that you're trying to set DOMAIN to the hostname, but in my case it does not fail, but returns null...
```
kubectl get svc istio-ingressgateway -o json -n istio-system | jq -r .status.loadBalancer.ingress[0].hostna
null
```

stripping off the pipe to jq, I get the following json...
```
kubectl get svc istio-ingressgateway -o json -n istio-system
{
    "apiVersion": "v1",
    "kind": "Service",
    "metadata": {
        "annotations": {
            "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"v1\",\"kind\":\"Service\",\"metadata\":{\"annotations\"stio\":\"ingressgateway\",\"release\":\"istio\"},\"name\":\"istio-ingressgateway\",\"namespace\":\"istio-system\"},\"spec\":{\"ports\":[{\,\"port\":80,\"targetPort\":80},{\"name\":\"https\",\"nodePort\":31390,\"port\":443},{\"name\":\"tcp\",\"nodePort\":31400,\"port\":31400},t\":15030,\"targetPort\":15030},{\"name\":\"https-grafana\",\"port\":15031,\"targetPort\":15031},{\"name\":\"https-tracing\",\"port\":1503\":\"istio-ingressgateway\",\"istio\":\"ingressgateway\",\"release\":\"istio\"},\"type\":\"LoadBalancer\"}}\n"
        },
        "creationTimestamp": "2020-01-17T14:29:57Z",
        "labels": {
            "app": "istio-ingressgateway",
            "chart": "gateways",
            "heritage": "Tiller",
            "istio": "ingressgateway",
            "release": "istio"
        },
        "name": "istio-ingressgateway",
        "namespace": "istio-system",
        "resourceVersion": "91734",
        "selfLink": "/api/v1/namespaces/istio-system/services/istio-ingressgateway",
        "uid": "d5fe7f80-3935-11ea-a768-02bdcabd3a21"
    },
    "spec": {
        "clusterIP": "172.20.228.61",
        "externalTrafficPolicy": "Cluster",
        "ports": [
            {
                "name": "status-port",
                "nodePort": 31990,
                "port": 15020,
                "protocol": "TCP",
                "targetPort": 15020
            },
            {
                "name": "http2",
                "nodePort": 31380,
                "port": 80,
                "protocol": "TCP",
                "targetPort": 80
            },
            {
                "name": "https",
                "nodePort": 31390,
                "port": 443,
                "protocol": "TCP",
                "targetPort": 443
            },
            {
                "name": "tcp",
                "nodePort": 31400,
                "port": 31400,
                "protocol": "TCP",
                "targetPort": 31400
            },
            {
                "name": "https-kiali",
                "nodePort": 31034,
                "port": 15029,
                "protocol": "TCP",
                "targetPort": 15029
            },
            {
                "name": "https-prometheus",
                "nodePort": 30299,
                "port": 15030,
                "protocol": "TCP",
                "targetPort": 15030
            },
            {
                "name": "https-grafana",
                "nodePort": 30114,
                "port": 15031,
                "protocol": "TCP",
                "targetPort": 15031
            },
            {
                "name": "https-tracing",
                "nodePort": 32378,
                "port": 15032,
                "protocol": "TCP",
                "targetPort": 15032
            },
            {
                "name": "tls",
                "nodePort": 30559,
                "port": 15443,
                "protocol": "TCP",
                "targetPort": 15443
            }
        ],
        "selector": {
            "app": "istio-ingressgateway",
            "istio": "ingressgateway",
            "release": "istio"
        },
        "sessionAffinity": "None",
        "type": "LoadBalancer"
    },
    "status": {
        "loadBalancer": {}
    }
}
```

removing the "-o json", I get...
```
kubectl get svc istio-ingressgateway -n istio-system
NAME                   TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                                                                                                                                      AGE
istio-ingressgateway   LoadBalancer   172.20.228.61   <pending>     15020:31990/TCP,80:31380/TCP,443:31390/TCP,31400:31400/TCP,15029:31034/TCP,15030:30299/TCP,15031:30114/TCP,15032:32378/TCP,15443:30559/TCP   9m13s
```

**Comment by johnrusaw** [comment]
Previously I was still thinking that this code would work...
```
elif [[ "$DOMAIN" == "null" && "$GATEWAY_TYPE" == "NodePort" ]]; then
  NODE_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="https")].nodePort}')
  NODE_IP=$(kubectl get nodes -l node-role.kubernetes.io/worker=true -o jsonpath='{ $.items[*].status.addresses[?(@.type=="InternalIP")].address }')
  DOMAIN="$NODE_IP:$NODE_PORT"
fi
```
but I'm not getting a NODE_IP from running this...
```
kubectl get nodes -l node-role.kubernetes.io/worker=true -o jsonpath='{ $.items[*].status.addresses[?(@.type=="InternalIP")].address }'
```

However, further investigating this link, https://istio.io/docs/tasks/traffic-management/ingress/ingress-control/#determining-the-ingress-ip-and-ports, refers to setting the INGRESS_HOST by using this command...
```
kubectl get po -l istio=ingressgateway -n istio-system -o jsonpath='{.items[0].status.hostIP}'
```
which does return an IP address for me.

**Comment by agrimmer** [comment]
I've tested installing Keptn on an EKS cluster and in my case I do get a `hostname` for the ingress.

Therefore, I assume that you are running into a quota limit or you do not have enough rights to get a `hostname`.  
How are you creating your EKS cluster? 
In our team, we use the `eksctl` command line tool, i.e.
`eksctl create cluster --version=1.14 --name=keptn --node-type=m5.xlarge --nodes=2 --region=eu-north-1`

The NODE_IP option is not applicable for EKS.

**Comment by johnrusaw** [comment]
We discovered that Istio won't deploy the LoadBalancer to an EKS internal private subnets (like we are planning to test in our pre-Production account) without the following annotation...
`service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0`
Refer to https://github.com/kubernetes/kops/issues/2608, https://medium.com/@joubertredrat/istio-ingress-gateway-with-aws-elb-in-private-subnet-de71a437f7fb, https://discuss.istio.io/t/istio-ingressgateway-with-aws-elb-on-private-subnet/1639, and https://discuss.istio.io/t/installing-istio-in-eks-private-subnets/3178.

Please let us know if there's an option in the keptn installation that we can pass or set to have Istio be installed this way. Thank you.

**Comment by christian-kreuzberger-dtx** [comment]
Hi,

at the moment there is no option to do that in Keptn.

I wonder if the problem is that Istio can't be installed, or whether it is just that the API is not visible to the outside and therefore the installation is aborted.

Can you show us the actual error message within Keptn?

**Comment by johnrusaw** [comment]
We were able to get further by switching to keptn version 0.6.0 and installing with the NodePort option...
`keptn install --platform=eks --gateway=NodePort`

**Comment by christian-kreuzberger-dtx** [comment]
Hi John,

yes this is possible, just bare in mind that gateway type NodePort is only a fallback options. Also, NodePort opens a port on every Kubernetes node (see https://medium.com/google-cloud/kubernetes-nodeport-vs-loadbalancer-vs-ingress-when-should-i-use-what-922f010849e0 ), which means that if your nodes ever change (e.g., when re-provisioning kubernetes nodes to another host) you might lose connection to your cluster via the IP address.

**Comment by agrimmer** [comment]
Hi @johnrusaw,
another option would be that Keptn uses an **existing** Istio installation.
Therefore, the CLI provides a hidden flag `istio-install-option` with the values `StopIfInstalled`, `Reuse`, `Overwrite` in the `keptn install`. 

You can then install istio with your custom annotations and, afterwards, install Keptn with `keptn install --istio-install-option=Resue`.

Can you please try this option?

**Comment by howardtangck** [comment]
Hi  @agrimmer,
      Still no successful. 

> Hi @johnrusaw,
> another option would be that Keptn uses an **existing** Istio installation.
> Therefore, the CLI provides a hidden flag `istio-install-option` with the values `StopIfInstalled`, `Reuse`, `Overwrite` in the `keptn install`.
> 
> You can then install istio with your custom annotations and, afterwards, install Keptn with `keptn install --istio-install-option=Reuse`.
> 
> Can you please try this option?

osboxes@osboxes:~/Downloads/keptn$ minikube start --driver=docker --memory=4096 --cpus=2 -kubernetes-version=v1.14.2
Error: unknown shorthand flag: 'k' in -kubernetes-version=v1.14.2
See 'minikube start --help' for usage.
osboxes@osboxes:~/Downloads/keptn$ minikube start --driver=docker --memory=4096 --cpus=2 --kubernetes-version=v1.14.2
😄  minikube v1.9.2 on Ubuntu 16.04
✨  Using the docker driver based on user configuration

❗  'docker' driver reported an issue: signal: killed
💡  Suggestion: Docker is not running or is responding too slow. Try: restarting docker desktop.

👍  Starting control plane node m01 in cluster minikube
🚜  Pulling base image ...
🔥  Creating Kubernetes in docker container with (CPUs=2) (2 available), Memory=4096MB (3921MB available) ...
🐳  Preparing Kubernetes v1.14.2 on Docker 19.03.2 ...
    ▪ kubeadm.pod-network-cidr=10.244.0.0/16
🌟  Enabling addons: default-storageclass, storage-provisioner
🏄  Done! kubectl is now configured to use "minikube"

osboxes@osboxes:~/Downloads/istio$ cd istio-1.5.2/
osboxes@osboxes:~/Downloads/istio/istio-1.5.2$ ls
bin  install  LICENSE  manifest.yaml  README.md  samples  tools
osboxes@osboxes:~/Downloads/istio/istio-1.5.2$ istioctl manifest apply --set profile=demo
Detected that your cluster does not support third party JWT authentication. Falling back to less secure first party JWT. See https://istio.io/docs/ops/best-practices/security/#configure-third-party-service-account-tokens for details.
- Applying manifest for component Base...
✔ Finished applying manifest for component Base.
- Applying manifest for component Pilot...
✔ Finished applying manifest for component Pilot.
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
- Applying manifest for component IngressGateways...
- Applying manifest for component EgressGateways...
- Applying manifest for component AddonComponents...
✔ Finished applying manifest for component IngressGateways.
✔ Finished applying manifest for component EgressGateways.
✔ Finished applying manifest for component AddonComponents.


✔ Installation complete

osboxes@osboxes:~/Downloads/keptn$ keptn install --platform=kubernetes --istio-install-option=Reuse
Used Installer version: docker.io/keptn/installer:0.6.1
Installing Keptn ...
Please enter the following information or press enter to keep the old value:

Please confirm that the provided information is correct: 
Cluster: minikube

Is this all correct? (y/n)
y
Using a file-based storage for the key because the password-store seems to be not set up.
Deploying Keptn installer pod ...
Installer pod deployed successfully.
Getting logs of pod installer-xn52w
Testing connection to Kubernetes API
Connection to Kubernetes API successful
Installing Istio on Kubernetes (this might take a while)
Istio installation is reused but its compatibility is not checked
Could not get ingress gateway domain name. Trying to retrieve IP address instead.
IP of Istio ingress gateway could not be derived.
Error: Keptn installation was unsuccessful

**Comment by agrimmer** [comment]
Hi @howardtangck, 
have you started `minikube tunnel` as described here https://keptn.sh/docs/0.6.0/installation/setup-keptn/#setup-kubernetes-cluster?

Please let us know.

**Comment by howardtangck** [comment]
Sorry, I missed that. Now I dont have enough resources (cpu and memory) to get the Keptn pods created. What is the minimum cpu and memory for this whole tutorial to work? Thanks.

**Comment by agrimmer** [comment]
No problem!
In the docu we recommend the following spec: `minikube start --cpus 6 --memory 12200`

**Comment by christian-kreuzberger-dtx** [comment]
This issue will become obsolete once we implement [KEP 18](https://github.com/keptn/enhancement-proposals/pull/18).

**Comment by christian-kreuzberger-dtx** [comment]
Closing this, as KEP 18 is being implemented.
