### ISSUE TITLE
Docs for Dynatrace Integration of SERVICES need to be improved

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#1025]
Currently the docs on Dynatrace Integration, specifically the **What has been setup?** section, could benefit from some more information.

```
In your Dynatrace tenant, when you navigate to Settings > Tags > Automatically applied tags you will find two entries:

    environment
    service
    test-subject

This means that Dynatrace will automatically apply tags to your onboarded services.
```

1. It should be "you will find three entries" if there are 3 entries listed below.
2. It should be explained what those entries mean (e.g., what does `test-subject` do)
3. In addition, we should mention that an additional `DT_TAGS` environment variable can be used, see [onboarding-carts/carts/templates/deployment.yaml](https://github.com/keptn/examples/blob/84b850e0e7a620104430dbfa1ff3b76be86ba626/onboarding-carts/carts/templates/deployment.yaml#L29-L30)

**Comment by grabnerandi** [comment]
I want to propose the following

In the HELM Chart we want to promote the following "best practice" by using DT_CUSTOM_PROPS to push keptn project, stage, service & deployment. Here is an example
```
        - name: DT_CUSTOM_PROP
          value: "keptn_project=.Keptn.Project keptn_service=.Keptn.Service keptn_stage=.Keptn.Stage keptn_deployment=.Keptn.Deployment release_name={{ .Release.Name }} release_namespace={{ .Release.Namespace }} release_revision={{ .Release.Revision }}"
```

Then we would need to create 4 Automated Dynatrace Tagging Rules that convert this meta data into Service Tags: project, service, stage, deployment.
Examples
* project:sockshop
* service:frontend
* stage:staging
* deployment:canary

The deployment tag also allows us to get rid of "test-subject" because the tag tells us whether this service is primary, canaray, blue/green or whathever other deployment we support.

**Comment by agrimmer** [comment]
According to issue #1109, the `DT_CUSTOM_PROP` will look as follows:

```
- name: DT_CUSTOM_PROP
  value: "keptn_project={{ .Values.keptn.project }} keptn_service={{ .Values.keptn.service }} keptn_stage={{ .Values.keptn.stage }} keptn_deployment={{ .Values.keptn.deployment }}"
```
