### ISSUE TITLE
No hint that it's only working with DT SaaS

### ISSUE THREAD

**Issue by dieselsteve** [keptn/keptn#116]
Hi All,

I just tried to setup the keptn with my local DT managed installation and failed at setupInfrastructure.sh line 22:

export DT_TENANT_URL="$DT_TENANT_ID.live.dynatrace.com"

that's obviously not possible. So 2 options from here from my point of view. 
1. Mention in the documentation that a SaaS tenant is required or
2. provide some additional install tasks for DT managed.

many thanks and best regards,
Steve

**Comment by jetzlstorfer** [comment]
Hi @dieselsteve 
thanks for your interest in keptn. 
We are aware that keptn v0.1.x can only be installed with a DT SaaS tenant with the scripts provided. We already have an open PR #69 that addresses this issue. It is not yet fixed since some scripts in the pull request prevent us from merging it. However, feel free to take a look to find some scripts prepared for DT managed installations.

**Comment by jetzlstorfer** [comment]
Information that a SaaS tenant is needed has now been added to v0.1.1

**Comment by dirkwall** [comment]
IMO this issue is resolved
