### ISSUE TITLE
Avoid installing incompatible Keptn Version (original: Provide warning when installing breaking Keptn version)

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/keptn#1162]
A warning should be provided when a breaking Keptn version is installed with an older version of the CLI. 
I was installing Keptn on friday and the installation failed, since the CLI was 0.5.2 and there was already 0.6.0beta released (seems to be fixed as of today). However, the CLI did not warn me about this mismatch. 

**Possible solutions**
- Provide a warning when installing a breaking version: List both the Keptn verison and the Keptn CLI version when installation starts and ask for user prompt if they mismatch
- Do not allow a user to install a breaking version with an outdated CLI (because the docs won't match the functionalities of the CLI)
- Prevent automatic installation of beta versions (only install stable version and never install beta versions without the use of the `--keptnVersion` flag)

**Comment by christian-kreuzberger-dtx** [comment]
I would like to discuss the possibility that `--keptnVersion` within the CLI is automatically set to the version of the release-branch or tag, e.g.,

* develop https://github.com/keptn/keptn/tree/develop 
* 0.5.2 https://github.com/keptn/keptn/tree/release-0.5.2
* 0.5.1 https://github.com/keptn/keptn/tree/release-0.5.1
* 0.5.0 https://github.com/keptn/keptn/tree/release-0.5.0
* 0.6.0.beta https://github.com/keptn/keptn/tree/release-0.6.0.beta

**Comment by christian-kreuzberger-dtx** [comment]
We also need to re-think `keptn configure domain` in that story.

**Comment by agrimmer** [comment]
In order to ensure that the CLI does not install an incompatible Keptn version, I changed the installation approach in the CLI as follows:

The command `keptn install` does not depend and use the `installer.yaml` contained in the `keptn/keptn`-repo in folder `installer/manifests/installer` anymore. Instead, this required manifest is generated by the CLI. 

Therefore, the CLI sets the Docker image for the installer job according to the CLI version. For example, if `keptn version` equals "CLI version: 0.6.0.beta2", the installer image `docker.io/keptn/installer:0.6.0.beta2` is used.

Furthermore, the semantics of the flag `--keptn-version` has also changed and now allows to provide a Docker image (no branch or tag). For example, you can now install a custom installer-Docker image with `keptn install --keptn-version=agrimmer/installer:asdf`.

Similarly, the command `keptn configure domain` also derives the required branch/tag using the information of `keptn version`. However, here the CLI still accesses the `keptn/keptn`-repo and manifests in folder `installer/manifests/keptn` because otherwise, we would have duplicated manifests.

Overall, by this approach, we ensure that the CLI version as well as the to be installed Keptn version match and, hence, are compatible.
