### ISSUE TITLE
Helm Service generates Primary Deployment.yaml but uses "Canary" for {{ .Values.keptn.deployment }}

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#1163]
As of today both the canary and the primary deployment yaml shows the value "Canary" for the deployment type. This means we cannot differentiate between Canary and Primary Deployment in Dynatrace as this meta data is not available

**Comment by agrimmer** [comment]
Thanks for reporting this issue. 
The problem was that the generated chart does not contain any templating functions anymore. Therefore, `.Values.keptn.deployment` cannot be used in the generated chart anymore.
I implemented the following solution for this issue: If we find `keptn_deployment=canary` in the primary-deployment, we can replace this string to `keptn_deployment=primary`.
