### ISSUE TITLE
keptn new-artifact creates the first configuration change event with empty stage field

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#1218]
When executing a new-artifact event via the keptn CLI the CLI sends a Configuration Change Event that has a blank stage field. Would be great to get this field filled as it would greatly help the understanding of an end user when following the event flow in e.g: keptns bridge, notification service, dynatrace service, ...

here the output of this message in the bridge
![image](https://user-images.githubusercontent.com/675886/70462812-f2a00000-1abb-11ea-98b8-96dd2e3eef31.png)

**Comment by agrimmer** [comment]
Currently, the CLI does not know the first stage (i.e. at this point it does not have the shipyard available). Therefore, the CLI sends by convention a `sh.keptn.event.configuration.change` with an empty stage. Afterwards, the `helm-service` inserts the stage information.

In order to solve this, we have to extend the Keptn API to query the stage information.
