### ISSUE TITLE
Document breaking changes and upgrade paths/scripts from 0.6.0.beta2 to 0.6.0 final

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#1250]
We will (temporarily) document all breaking changes and upgrade scripts/etc... from 0.6.0.beta2 to 0.6.0 final.

This will be added to the release notes when we release 0.6.0 final.

**Comment by christian-kreuzberger-dtx** [comment]
`keptn install` no longer provides `--keptn-version`. Instead, `--keptn-installer-image` should be used (e.g., `keptn install --keptn-installer-image=keptn/installer:latest` for installing the latest development version)

**Comment by agrimmer** [comment]
Issue #1231 removed the gateway in namespace `keptn` and the gateways for all stages but introduces a new gateway named `public-gateway` in namespace `istio-system`. 
This gateway is now used in all VirtualServices.

In order to upgrade from 0.6.0.beta2 to 0.6.0, we need to 
- delete all generated gateways (in namespace keptn and all stages),
- apply the new `public-gateway` in namespace `istio-system`, and
- adapt all VirtualServices (api, all onboarded services) to use this `public-gateway`.

**Comment by christian-kreuzberger-dtx** [comment]
ToDo: Provide an upgrade path
