### ISSUE TITLE
Allow case-sensitive service names in "keptn create service" 

### ISSUE THREAD

**Issue by agrimmer** [keptn/keptn#1465]
In `keptn onboard service` and `keptn create service` we only allow service names, which only contain lower case letters. This is due to the fact that the k8s service name has to match Keptn service names. 
However, if we use quality gates only, we do not manage k8s service names and, hence, we should allow to use case-sensitive service names in `keptn create service`.

**Comment by agrimmer** [comment]
Related to #1421
We know that this is an inconvenience but there is currently no option to provide this feature.
We will, however, consider this feature for future releases.

**Comment by yul14nrc** [comment]
I have this issue. All my automatically tags in dynatrace contains uppercase letters and I am only using keptn for quality gates, and when I try to create a service in keptn it shows the error:
`dynatraceacm@cloudshell:~/keptn (keptnproject)$ ./keptn create service Activities --project=carnival
Error: Service name contains upper case letter(s) or special character(s).`
This is a problem because if I want to use keptn I have to change all my automatically tags (there are a lot of rules)

**Comment by agrimmer** [comment]
Thank you for your explanations!
I am working on a fix for this issue: https://github.com/keptn/keptn/pull/1472
