### ISSUE TITLE
Prepare Kubernetes 1.22 Support: Change from deprecated extensions/v1beta to networking.k8s.io/v1beta1

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#1529]
Source: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

The **v1.22** release will stop serving the following deprecated API versions in favor of newer and more stable API versions:

---

-  Ingress in the **extensions/v1beta1** API version will no longer be served:  Migrate to use the **networking.k8s.io/v1beta1** API version, available since v1.14. Existing persisted data can be retrieved/updated via the new version.

`extensions/v1beta1` in Istio:
- [ ] Ingress: `\keptn\installer\manifests\istio\helm\istio\charts\grafana\templates\ingress.yaml`
- [ ] Ingress: `\keptn\installer\manifests\istio\helm\istio\charts\kiali\templates\ingress.yaml` 
- [ ] Ingress: `\keptn\installer\manifests\istio\helm\istio\charts\prometheus\templates\ingress.yaml`
- [ ] Ingress: `\keptn\installer\manifests\istio\helm\istio\charts\tracing\templates\ingress.yaml`

`extensions/v1beta1` in Keptn:
- [ ] Ingress: `\keptn\installer\manifests\keptn\keptn-ingress.yaml`

**Action**: Replace with `networking.k8s.io/v1beta1`

---

`apps/v1beta1`  in: 
- [x] Secret: `\keptn\configuration-service\common\git.go`
**Action**: Replace with `apiVersion: v1`
https://github.com/keptn/keptn/blob/79702ac70d2402f250f614332a1a1ab10fda65d3/configuration-service/common/git.go#L194-L207 

---

**Important**: If this gets changed in Keptn, it needs to be part of an upgrader job.

**Comment by johannes-b** [comment]
From https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

The **v1.22** release will stop serving the following deprecated API versions in favor of newer and more stable API versions:

-  Ingress in the **extensions/v1beta1** API version will no longer be served:  Migrate to use the **networking.k8s.io/v1beta1** API version, available since v1.14. Existing persisted data can be retrieved/updated via the new version.

**Comment by johannes-b** [comment]
Istio 1.15 still uses `extensions/v1beta1` in their Helm chart templates for: 

- istio\helm\istio\charts\grafana\templates\ingress.yaml
- istio\helm\istio\charts\kiali\templates\ingress.yaml
- istio\helm\istio\charts\prometheus\templates\ingress.yaml
- istio\helm\istio\charts\tracing\templates\ingress.yaml

**Comment by johannes-b** [comment]
Regarding the apiVersion for the Secret. Since we are using the k8s core library v1 (v1 "k8s.io/api/core/v1"), the `apiVersion` is actually set to: `apps/v1`. Nevertheless, I fixed the wrong `apiVersion` when creating a Git Secret in `\keptn\configuration-service\common\git.go`.

**Comment by christian-kreuzberger-dtx** [comment]
I just tested it with the latest build (may 6th) on the master branch:
Keptn core full installation works on Kubernetes 1.16 and 1.17. We should lift the k8s version limitation within the CLI.

**Comment by johannes-b** [comment]
Thanks for verifying that Ketpn core works on K8s 1.16, and 1.17!

Since this issue is mainly focused on changing the deprecated *extensions/v1beta* to *networking.k8s.io/v1beta1*, I created a separate issue for verifying K8s support of Keptn 0.7: https://github.com/keptn/keptn/issues/1777

Please let's discuss and continue the work there.

**Comment by johannes-b** [comment]
Due to the removal of Istio, Keptn has no manifests in `\keptn\installer\manifests\istio\helm\istio\*` to maintain. 

Thus, this issue has become obsolete and will be closed.
