### ISSUE TITLE
Project in undefined state - Catch a not initialized Git repo by creating an initial commit

### ISSUE THREAD

**Issue by pahofmann** [keptn/keptn#1545]
**Environment**
* Client OS (e.g., Linux, OSX, Windows): **linux**
* Keptn Version (`keptn version`): **0.6.1**
* Kubernetes Cloud Provider (e.g., GKE, AKS): **AKS**
* Kubernetes version (`kubectl version`): **1.14.8**

**Affected Component**
* [x] CLI

**Describe the bug**
I forgot to initialize the git repo while creating a new project with a upstream git repository.  
`keptn create project ...` failed with:   
```
Starting to create project   
ID of Keptn context: 9d1a30cd-e00b-4354-a308-03e50368bc40  
Creating project sockshop failed. Could not commit changes.
```   

The problem is: I now can neither delete the project, nor create a new one with the same name.  
Creating it fails with "Project exists", deleting it fails with "Project doesn't exist",

**To Reproduce**
1. Create new project with empty git repo
2. Try to delete the project

**Expected behavior**
If git repository is empty, project creation is aborted.  
**OR**
Project in failed state can be deleted.

**Current behavior**
Project is created but can't be deleted.

**Screenshots**
![image](https://user-images.githubusercontent.com/5699104/77349089-c6428380-6d3a-11ea-9f6f-8d622dc3d3fa.png)

**Comment by pahofmann** [comment]
This also seems to have an impact on the bridge.  
The bridge no longer shows any projects, even though there are other projects that are configured correctly:  
![image](https://user-images.githubusercontent.com/5699104/77352149-0dcb0e80-6d3f-11ea-8794-bab76145b652.png)

**Comment by pahofmann** [comment]
Is there a way to manually remove the problematic project configuration so the bridge works again?

**Comment by johannes-b** [comment]
Hi Patrick,
can you connect to the `configuration-service` pod using: `kubectl exec -it configuration-service-1234-xyz -n keptn -- /bin/sh`

In the container you find the folder `/data/config/`. There remove your project (which is a git repo)

**Comment by pahofmann** [comment]
Thanks, that fixed the problem, bridge is working again.  
Could be helpful to add that information on where the project repos are to the [Troubleshooting section](https://keptn.sh/docs/0.6.0/reference/troubleshooting/).

**Comment by christian-kreuzberger-dtx** [comment]
This also occured in #1625, we are going to fix this soon.

**Comment by agrimmer** [comment]
The root cause of this problem is the following:
When creating a keptn project with a Git upstream, the configuration service executes a `git clone` and afterwards a `git pull`. The `git pull` however fails when the repo is uninitialized: 
> Your configuration specifies to merge with the ref 'refs/heads/master'
from the remote, but no such ref was fetched.

**Proposed solution:**
When cloning the repo, we get a warning if the repo is not yet initialized:
> Cloning into 'xxx'...
warning: You appear to have cloned an empty repository.

The configuration-service should check this warning and if this occurred, it must not make a `git pull` but directly make a `git add`, `git commit` and `git push`.

See https://github.com/keptn/keptn/blob/d0fd0423db7dc2b97c1b0336225bcdf16d996da1/configuration-service/handlers/project.go#L123
https://github.com/keptn/keptn/blob/d0fd0423db7dc2b97c1b0336225bcdf16d996da1/configuration-service/common/git.go#L110

**Comment by johannes-b** [comment]
Thanks for the investigation. 
To keep this issue focuses on the root cause of the problem, which was a not-initialized Git repo, @agrimmer proposed solution avoids having Keptn projects in an undefined state. Let's prioritize this fix.

To delete a project that is in an undefined state (e.g., by adding a `--force` to `keptn delete project xyz --force`) a separate issue should be created.
