### ISSUE TITLE
Need an indication that tests are actually running

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#1565]
**Problems:** 
* When using Keptn for either end-2-end or just for performance as a self-service where a user sends a deployment-finished-event, it is hard to know whether something is actually happening from a testing perspective.

* Right now tests are triggered by `deployment-finished`, but if the user doesn't know this detail then it looks like nothing is happening until the tests are done.

**Idea:**
I am therefore proposing some `progress indicator` in Keptn that shows what is currently happening, e.g: which service is currently processing a task or at least has picked up an event.

**Comment by agrimmer** [comment]
We will address this by the proposed triple of events, e.g.
`sh.keptn.events.test.triggered` (sent out by Keptn), `sh.keptn.events.test.started` (sent out by e.g. jmeter-service) and `sh.keptn.events.test.closed` (sent out by e.g. jmeter-service).
Furthermore, we were thinking of a 4. event for reporting the status, i.e. `sh.keptn.event.test.in-progress`.

Does this sound reasonable?

**Comment by robertjahn** [comment]
I agree we need more test events so that we can see the status in the bridge, especially test started.  Just try to keep the suffix naming standard.  some events are `sh.keptn.events.XXX.done` and some are `sh.keptn.events.XXX.finished`.   If you add `sh.keptn.events.test.closed` that is yet another suffix.  If I was to vote, I would used `sh.keptn.events.XXX.finished`

**Comment by agrimmer** [comment]
Closing this in favor of #2263
