### ISSUE TITLE
Use keptn quality gates with argocd rollout analyses 

### ISSUE THREAD

**Issue by jkleinlercher** [keptn/keptn#1601]
Did anyone try to use keptn quality gates with argocd rollout analyses? https://argoproj.github.io/argo-rollouts/features/analysis/

I know keptn‘s approach is to provide a all-in-one delivery pipeline. However, we are quite happy with argocd and maybe keptn quality gates would be a perfect complement for argocd rollouts.

If anyone already has some experience, please share!
If not, how can I start to experiment with it?

**Comment by johannes-b** [comment]
Hi, 
we are currently working on an ArgoCD integration for Keptn. Thus, you can find a (**not yet officially released**) tutorial here: https://github.com/keptn/keptn.github.io/pull/456 

The tutorial is not yet released because we face an issue with ArgoCD as shown here: https://github.com/keptn/keptn.github.io/issues/449#issuecomment-606410595 
In this regard, we are in touch with the ArgoCD team.

It would be great if you could help us validating the tutorial and ArgoCD integration.

@agrimmer may I ask you for an update on that.

**Comment by agrimmer** [comment]
As Johannes said, I am working on a tutorial on how to use Keptn and Argo.
@jkleinlercher Can you please join our [Slack channel](https://join.slack.com/t/keptn/shared_invite/enQtNTUxMTQ1MzgzMzUxLWMzNmM1NDc4MmE0MmQ0MDgwYzMzMDc4NjM5ODk0ZmFjNTE2YzlkMGE4NGU5MWUxODY1NTBjNjNmNmI1NWQ1NGY) and message me for discussing details?
Duplicate to https://github.com/keptn/keptn.github.io/issues/449

**Comment by agrimmer** [comment]
Hi @jkleinlercher,
I've worked on a first tutorial where ArgoCD is used for the deployment. In the tutorial, I am using a `rollout` for a b/g deployment. This rollout is then tested and evaluated by Keptn (i.e. Keptn implements a **Quality Gate**). If all Service Level Objectives [SLOs](https://github.com/keptn/spec/blob/master/sre.md) are met (i.e. the Quality Gate is passed), Keptn promotes this rollout. If the Quality Gate is not passed, Keptn aborts this rollout. 

You can find the new tutorial here: https://tutorials.keptn.sh/

We would like to ask you for your feedback on this tutorial!

**Comment by jkleinlercher** [comment]
I will have a look at it and give you feedback! Great work!
