### ISSUE TITLE
API: Get Event returns HTTP 500 when event cant be found. Should be 404

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#1655]
When waiting for an evaluation-done event a client has to call GET /event with the keptnContext and evaluation-done as event type. When the event does not yet exists the Keptn API returns an HTTP 500 (Internal Server Error) instead of something that is more descriptive, e.g: 404 Resource Not Found.

HTTP 500 is definitely misleading as this is not an internal server error. It is really about an event not being present - so - a more suitable HTTP Status Code should be used, e.g: 404

**Comment by imrenagi** [comment]
I will take this

**Comment by johannes-b** [comment]
The /GET event endpoint still returns a 500 - Internal Server error, because the [GetEvent](https://github.com/keptn/keptn/blob/master/api/handlers/event.go#L116) function returns an error which leads to the 500 error. 

**Task:**
- Change the [getLatestEvent](https://github.com/keptn/go-utils/blob/master/pkg/lib/datastore.go#L75) to return a 404 when no event with the given keptnContext and type is available
- Catch a 404 in [GetEvent](https://github.com/keptn/keptn/blob/master/api/handlers/event.go#L116) and respond it.

**Definition of Done:**
- The /GET event endpoint returns 404 (resource not found) when the event from the given keptnContext and type is not available.
