### ISSUE TITLE
Allow Keptn Installer to pull containers from different container registry

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#1775]
**Is your feature request related to a problem? Please describe.**
Not all organizations can download containers from DockerHub. Some organizations require to load them from an in-house private registry where those containers have been download from DockerHub, scanned, and then uploaded to the private registry.
As the Keptn installer does not provide an option to specify the registry, we have some organizations that cant install Keptn using the automatic keptn installer in their organization.

**Describe the solution you'd like**
* I would like the installer to provide an option to define the registry that should be used when applying the manifests, e.g: keptn install --registry=myregistry

* Another option that would be needed is an option to list all images that are needed so that organizations can download exactly that list, e.g: keptn install --list-images

**Describe alternatives you've considered**
The alternative solution is to follow the manual installation approach where users can download these manifests listed, replace the image reference to point to the private registry and then apply them.

**Comment by YeongchanSeo** [comment]
Hi team,

I have started to provide a Keptn’s quality gates only service as a Pilot release in my company by using staging environment, so would like to progress toward GA release by using production environment.
Because production environment can only be accessed from our internal network, which means it can not be accessed from outside of the company, Keptn's installing would fail when it is installed in production environment.
I have been suggested to install using manifests to solve this way, but it is still in experimental, further, I suppose the option in this request will be more helpful to us.

**Comment by johannes-b** [comment]
Hi, 
installing Keptn into an environment without access to DockerHub is a very valid use-case. Thanks for bringing that up!

For a quick solution, I have provided a list of all images that are rolled-out when using the install instructions with the manifests files; please see [here](https://deploy-preview-543--keptn.netlify.app/docs/0.6.0/reference/manifest_installation/#summary-of-applied-images).

Nevertheless, this feature needs to be covered by the Keptn installer and we prioritize it as one of the next features for the installer.

**Comment by agrimmer** [comment]
With my PR #2022, the Keptn installer is now distributed as Helm-chart and does allow to override the used registry (see [values file](https://github.com/keptn/keptn/blob/master/installer/manifests/keptn/values.yaml)). 

The list of required images will be provided by implementing https://github.com/keptn/keptn/issues/1979 and, hence, I am closing this issue.
