### ISSUE TITLE
Keptn Core (remediation-service, helm-service): Refactor remediation-service and move functionality of scaler to helm-service 

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#1817]
**Task 1:** 

Remove the `aborter`, `blacklister`, and `slower` actions from the remediation-service, since they cannot be used right now - and no use-case supported for that actions.  

**Task 2:** 

In the remediation-service, there is the built-in function of scaling the ReplicaSet of a Deployment by 1. This function needs to be moved to the helm-service, which must listen to the following events: 

- The helm-service listens to an `sh.keptn.event.action.triggered` event with the property: *scaler* 
- Execute scaler action (to scale the ReplicaSet by 1) and send event: `sh.keptn.event.action.finished` 

**Definition of Done:** 
- [ ] Remediation-service/action folder is cleaned-up   
- [x] `helm-service` can handle a scaling action (sh.keptn.event.action.triggered -> execute action -> sh.keptn.event.action.finished)

**Comment by agrimmer** [comment]
Additionally, the following task is requried:
- Remove the special handling for a `configuration-change` event with source equals remediation-service:
https://github.com/keptn/keptn/blob/b48d5340de91e29cdb33969a632466fca0051a4e/helm-service/controller/configuration_changer.go#L137 
because the helm-service now directly receives an `action.triggered` event.
