### ISSUE TITLE
configuration-service: Store resource on master when adding a resource as service default

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#1838]
![image](https://user-images.githubusercontent.com/729071/82898245-33e87700-9f59-11ea-8f28-3165216cea27.png)

The implementation of the endpoint POST `/project/{projectName}/service/{serviceName}/resource` duplicates the resource (that is supposed to get added) to all stages (aka. git branches).

For example, when adding the resource `xyz.yaml` to the project `sockshop`, and service `carts`, this results in a `xyz.yaml` file in the folder `carts` on each stage (branch): e.g.: `dev`, `hardening`, `production`. 

**Problems:**
- Duplication of config files that are supposed to work as default config.

- After executing the command, it cannot be determined whether the file was added as default resource (using the POST `/project/{projectName}/service/{serviceName}/resource` endpoint) or as "regular" resource (using the POST `/project/{projectName}/stage/{stageName}/service/{serviceName}/resource` endpoint) 

**Solution:**
- Config files that are supposed to work as default configs should be stored on master branch. (similar to the shipyard.yaml) 

- For each service, a dedicated folder with the service name is created on master. When using the above endpoint, a default config for the service is then stored in the folder. For example, adding a `test.jmx` as default for the `carts` service: 
   ```
    - master:            <- git branch
     - carts             <- folder
       - test.jmx
     - metadata.yaml
     - shipyard.yaml
   ```

**Definition of Done:**
- [ ] Not implemented endpoints of the **Service Default Resource** section of the swagger-ui from the configuration-service are hidden (or marked as not implemented)
- [ ] Service default configs are stored as proposed

**Comment by agrimmer** [comment]
This would lead to a distribution of data across multiple branches for a service, which is also not ideal.

**Comment by christian-kreuzberger-dtx** [comment]
> This would lead to a distribution of data across multiple branches for a service, which is also not ideal.

I agree with you.

I believe that a stage should be self-contained. This is also supported by our definition in the [glossary](https://keptn.sh/docs/0.6.0/concepts/glossary/):
> **Project stage**: A project stage (or just stage) defines a logical space (e.g., a namespace in Kubernetes), which has a dedicated purpose for an application in a continuous delivery process.

I'd like to also address the problems mentioned in the issue above:

> Duplication of config files that are supposed to work as default config.

We already have had that for our helm-charts for ages. So that would be one of the first things to move to the master branch, if that's even the correct place. Maybe we need a *template* branch?


> After executing the command, it cannot be determined whether the file was added as default resource

If this is really a pain for someone (please comment!), we could address this via the commit message and one can use the git history of the file.


FYI, staying in the *+gitops world**: You store your stuff in the respective branches. Duplication will always happen (unless you cleverly play around with `git rebase` and `git cherry-pick`).
What's important is that you have a good commit history and commit messages.
