### ISSUE TITLE
Use k8s service account with a restricted set of permissions instead of default 

### ISSUE THREAD

**Issue by thschue** [keptn/keptn#1862]
**Is your feature request related to a problem? Please describe.**
Currently, keptn services use the default serviceaccount with a set of high privileges inside the k8s clusters

**Describe the solution you'd like**
Use service accounts with a minimum set of privileges 

**Additional context**
for example: 
- helm-service / verb=get, resource=configmap, resource-name=keptn-domain
- lighthouse-service / verb=create,update, resource=configmap

**Comment by johannes-b** [comment]
Thanks for bringing this up! 

The problem is clear, but I have two questions: 
- Should we provide a set of pre-defined service accounts, which are then assigned to service? 
- How can we handle service accounts of (custom) keptn-services as available on keptn-contrib/sandbox? Do we just provide a recommendation for those?

**Comment by johannes-b** [comment]
**Research Tasks:** 
- Research on which services require K8s API access.
- Research on RBAC for OpenShift.
- Research on NATS.

**Decision:**
- dynatrace-service, prometheus-service have their own role-binding
