### ISSUE TITLE
Improve the output of keptn cli for troubleshooting

### ISSUE THREAD

**Issue by roman-ferstl** [keptn/keptn#1928]
When we ran into the issue described here: https://github.com/keptn/keptn/issues/1927, we thought that it would be really helpful to see the actual kubectl commands that "`keptn install`" is making, as we could not figure out which statement actually fails to understand the problem.
Note that we also tried it with the `--verbose` flag, but we didn't get more information. 

In general, for troubleshooting purposes of the Keptn CLI itself it would be helpful to see the actual commands that `keptn install` executes. This will help with troubleshooting issues against, e.g: az commands.

**Comment by christian-kreuzberger-dtx** [comment]
Absolutely, I've added this to 0.7.0 because this will help everyone to troubleshooting installation issues.

When we tackle this, we should also take a look at the log output of the install command once it is running on the cluster. My installer currently hangs with this output:
```
Availability of provided image cannot be checked.
Used Installer version: keptn/installer:latest
Installing Keptn ...
Deploying Keptn installer job ...
Waiting for installer pod to be started ...
```
No output is received for 10 minutes - this is not optimal.

**Comment by christian-kreuzberger-dtx** [comment]
# Definition of Done

The following applies when `--verbose` is used:

* Log if a connection to the kubernetes API can be established
* Log the command every time we use `kubectl` and the return code
* Log additional messages that might help the user for troubleshooting (where appropriate)
