### ISSUE TITLE
Update UI look-and-feel

### ISSUE THREAD

**Issue by AloisReitbauer** [keptn/keptn#1974]
**Use grey background for left/right menus**

![image](https://user-images.githubusercontent.com/478193/86108538-92a69080-bac3-11ea-9462-e72537dc32af.png)

**Streamline font sizes (talk to Barrista team - some seem very large**

![image](https://user-images.githubusercontent.com/478193/86108612-ab16ab00-bac3-11ea-9256-7e3a491fb22f.png)

**Avoid boarders where possible and just use slightly different graded background instead**

![image](https://user-images.githubusercontent.com/478193/86108798-ed3fec80-bac3-11ea-8a22-e1a9071586c9.png)

**Make the state of an action more visible - Especially for failed actions**

![image](https://user-images.githubusercontent.com/478193/86108379-61c65b80-bac3-11ea-91b4-76738dd28b4a.png)

**Comment by ermin-muratovic** [comment]
@AloisReitbauer 
Avoiding the boarders and just using slightly different graded brackground instead, makes the bridge all in all "darker", since  we have several hierarchy levels.

![image](https://user-images.githubusercontent.com/6098219/87012828-09c9dc00-c1ca-11ea-8b84-cb5a87ce0a88.png)

**Comment by ermin-muratovic** [comment]
Current changes
- The background color for the menu and dialog changed to gray.
- Removed the shadow from the header
- Failed root events are more visible (red border left and stage is marked red with background instead of border)

![image](https://user-images.githubusercontent.com/6098219/87022646-1274df00-c1d7-11ea-81a3-12d01505174f.png)
