### ISSUE TITLE
Remove auto-generated Angular "it should create an instance" tests

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#2000]
As mentioned by @dominikmessner in PR #1993, we could remove the auto generated "it should create an instance" tests:
https://github.com/keptn/keptn/pull/1993/files/8b3a047f610b7fec94f2806189f58453cf0efafa#r449132239
![Screenshot from 2020-07-03 08-02-53](https://user-images.githubusercontent.com/56065213/86436921-a3dde000-bd03-11ea-80ad-d56fffee4826.png)

As this affects not only the PR, but a whole lot of lines of code in our Angular app, I'd like this to be done in a separate issue. But before we go this way, can anyone provide some more details whether these auto generated tests have any value and how big the impact on removing them would be?

**Comment by dominikmessner** [comment]
In our internal project, we removed all these tests and could speed up the test execution by 10%. I quickly had a look at a few Angular projects, the ones that I looked at don't have these default tests:
- [Angular](https://github.com/angular/angular/search?q=%22should+create+an+instance%22&unscoped_q=%22should+create+an+instance%22)
- [Material](https://github.com/angular/components/search?q=%22should+create+an+instance%22&unscoped_q=%22should+create+an+instance%22)
- [Barista](https://github.com/dynatrace-oss/barista/search?q=%22should+create+an+instance%22&unscoped_q=%22should+create+an+instance%22)

I think as soon as there is a proper test for a component, the instance creation will be tested implicitly anyways, that's why it's probably ok to remove them.
