### ISSUE TITLE
keptn installation for baremetal kubernetes cluster.

### ISSUE THREAD

**Issue by Sha90** [keptn/keptn#2040]
**Is your feature request related to a problem? Please describe.**
Looking at the documentation, there is no document on how to install keptn on a on premises bare metal kubernetes cluster, created using kubeadm. 

**Describe the solution you'd like**
Any help on how to use keptn quality gates in bare metal kube cluster.

**Comment by agrimmer** [comment]
Hi @Sha90 , 
thank you for your question!
You are right, that our documentation is missing instructions for a bare metal kube cluster.
You can install Keptn at your cluster using the following CLI command `keptn install --platform=kubernetes`.
With this option, Keptn is installed at the cluster where your current kube-context is pointing to.

With the upcoming release 0.7, we do not differentiate any Kubernetes derivates anymore because the installer was streamlined. Hence, I am closing this issue.
