### ISSUE TITLE
As a keptn developer, I can automatically set up a demo environment

### ISSUE THREAD

**Issue by dirkwall** [keptn/keptn#206]
We have an on-demand dedicated demo environment, where that latest features and overall use cases can be demonstrated. This environment can also be used for sprint reviews and community meetings.

**Acceptance criteria**
- **Given** I'm a person that gives a demo
  **When** I get a fresh Kubernetes cluster
  **Then** I want to be able to install keptn including all core components automatically

**Comment by agrimmer** [comment]
During the night, a travis cron job sets up a new environment and installs keptn in the version of the master-branch. 

Refinement of **Then**: keptn is automatically installed by the travis cron job

**Comment by agrimmer** [comment]
**Completed:**
- Setup of a nightly-cluster using keptn in version 0.2.1. This cluster is re-created on a daily basis using a Travis cron job.
- End-to-end tests verify the functionality

**Missing** due to dependencies on issue #327:
- The nightly cluster should be set up using the versions contained in the dev-branches of the core components.
- Extend end-to-end tests: (1) test which pushes an artifact into dev, staging and prod, (2) test with quality gates in place
- Rename scripts: Currently, the scripts are named 'pr_main' and 'master_main'. These names are misleading.

**Comment by dirkwall** [comment]
Closing this issue. Missing tasks are transferred to #337
