### ISSUE TITLE
Determine whether teststrategy is required fields for sh.keptn.event.start-evaluation

### ISSUE THREAD

**Issue by robertjahn** [keptn/keptn#2094]
If you POST the start evaluation without a teststrategy value, you do not get an ERROR from the API call and you get the keptncontextid and you can see it in the Keptn bridge. The problem is that the bridge or using the API, one is not able to retrieve the results.

![image](https://user-images.githubusercontent.com/24907089/88069105-0bd35980-cb3f-11ea-85df-c3c5580c76b0.png)

![image](https://user-images.githubusercontent.com/24907089/88069235-332a2680-cb3f-11ea-84a3-0a28b062e4c2.png)

I would like the core team to review whether this is expected behavior. 

Personally, I  don't see why teststrategy is required if you are doing just an evaluation.  Seems to me it is there from the earlier versions of Keptn where a test was tightly coupled to the evaluation.   

I think the solution here is to make a change to the REST API call to get results to not fail of there is a null teststrategy value.   Otherwise, if there is some need to have a teststrategy value, then the API call should fail and indicate that this attribute is required.

**Comment by agrimmer** [comment]
Good point @robertjahn!
The assumption we have in the `lighthouse-service` is as follows:
If there were no tests performed, there are no metrics that can be used for the quality gate. We know that this is wrong!

Furthermore, we use the `test-strategy` in order to decide if we would like to evaluate the canary or primary deployment (i.e. blue or green version).

By implementing this issue, will remove the dependency for the `teststrategy` but will introduce a parameter to identify whether the blue or green version should be evaluated.

**Comment by agrimmer** [comment]
This is related to #2264

**Comment by christian-kreuzberger-dtx** [comment]
I'm adding this to the 0.8.0 milestone, I think this should be possible.

**Comment by johannes-b** [comment]
The identified limitation has been removed in Keptn 0.8.0.
