### ISSUE TITLE
Add a trace link to Keptn bridge on Dynatrace Event

### ISSUE THREAD

**Issue by kristofre** [keptn/keptn#2119]
**Is your feature request related to a problem? Please describe.**
In Keptn 0.6.x there would be a link to the Keptn Bridge with the correct trace visible in the event sent to Dynatrace.
In Keptn 0.7 this is no longer the case.

**Describe the solution you'd like**
Have a link in the Dynatrace event to the Keptn Bridge with the trace context when an evaluation has been performed.

**Comment by grabnerandi** [comment]
With Keptn 0.7 the dynatrace-sli service requires the link to your bridge set in the enviroment varible KEPTN_BRIDGE_URL because Keptn Services can no longer query the keptn bridge or api endpoint from a config map. This was changed which is why that information needs to be passed as an enviornment variable. 
The *dynatrace-service* readme already contains that description: https://github.com/keptn-contrib/dynatrace-service

**Comment by grabnerandi** [comment]
Please close this issue as this feature has already been in keptn 0.7 - it just needs an additional env-variable

**Comment by grabnerandi** [comment]
Not an issue
