### ISSUE TITLE
Wrong version in environments overview when evaluation failed

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#2133]
I am using my simplenode app and have started extending my example into 3 stages: dev, staging, prod.

I've played around a bit with sending configuration-change events through both the Keptn CLI as well as using Jenkins where I accidentally sent configuration-change events into staging, therefore bypassing dev. 

This might be the reason for the wrong version information I am seeing in the bridge as you can see in the following screenshot:

![image](https://user-images.githubusercontent.com/675886/88629569-b7385d00-d0af-11ea-8c35-77f04a1d0bf2.png)

Besides the wrong information for staging in the environment overview, I also want to make sure we are displaying the correct version information in the service view. 
* The "most relevant artifact" for me is the one that made it into production. 
* The other thing that is important to know is which artifact was the last that was sent to Keptn - whether it made it to prod or not. --> That is the "most recent artifact". 

You can also see this above in the screenshot.

**Comment by johannes-b** [comment]
Andi also showed me that a problem with the image tags occurs in the following situation. 
- dev: direct deployment
- staging: direct deployment 
- product: blue/green deployment

Artifact:0.2.0 gets promoted from dev to staging, but in staging the quality gates fail. Since it is a direct deployment, no rollback happens. However, the environment screen shows artifact:0.1.0.

**Comment by ermin-muratovic** [comment]
> I've played around a bit with sending configuration-change events through both the Keptn CLI as well as using Jenkins where I accidentally sent configuration-change events into staging, therefore bypassing dev.
> 
> This might be the reason for the wrong version information I am seeing in the bridge as you can see in the following screenshot:

The bridge currently considers every failed quality gate as "rollback". Since you have the deploymentstrategy "direct", there is no rollback happening. This needs to be fixed in the bridge.



> Besides the wrong information for staging in the environment overview, I also want to make sure we are displaying the correct version information in the service view.
> 
> * The "most relevant artifact" for me is the one that made it into production.
> * The other thing that is important to know is which artifact was the last that was sent to Keptn - whether it made it to prod or not. --> That is the "most recent artifact".

As it says "Last relevant", this shows the *last* relevant artifact. Let me know if we should change that into *most recent*.
Since we can only guess what the *most relevant* stage is for the user, I would display here in this view only the last/most recent artifact. For the other use-case we have the "Environments" view, where you can see the currently deployed image for each stage and thus also the one that is running in production.
