### ISSUE TITLE
Bridge does not allow to approve artifact if the service is not yet deployed in the stage

### ISSUE THREAD

**Issue by agrimmer** [keptn/keptn#2151]
Although there is a pending `approval.triggered` event, I cannot use the Bridge in order to confirm this approval (i.e. to send an `approval.finished`):

<img width="1016" alt="Screen Shot 2020-07-30 at 15 01 16" src="https://user-images.githubusercontent.com/10980861/88926397-3a0b1480-d276-11ea-8b4e-755f875263a7.png">

The Bridge shows the message: "Service not yet deployed".

In my tests, I used the following shipyard:
```
stages:
  - name: "dev"
    deployment_strategy: "direct"
    test_strategy: "functional"
  - name: "staging"
    approval_strategy: 
      pass: "manual"
      warning: "manual"
    deployment_strategy: "blue_green_service"
    test_strategy: "performance"
  - name: "production"
    approval_strategy: 
      pass: "automatic"
      warning: "manual"
    deployment_strategy: "blue_green_service"
    remediation_strategy: "automated"
```

**Definition of Done:**
- [x] The Bridge can be used to approve/reject a service even if there is no service deployed in the respective stage.

**Comment by ermin-muratovic** [comment]
Actually the bridge allows to approve the deployment even if there is no service deployed in the respective stage.
Also the message "Service not yet deployed" is correct here, because the service isn't deployed yet.

But, you have to expand the service first, to see all pending approvals, which is indicated by the blue icon.

![image](https://user-images.githubusercontent.com/6098219/89288874-a1e6a400-d656-11ea-9110-3ecb25aebbde.png)
