### ISSUE TITLE
Integration test script troughs an error that is not catched

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#2161]
In the logs of the TravisCI build, the following error occurs:

```
ERROR: Found image 
  }docker.io/keptnexamples/carts:0.10.1 but expected docker.io/keptnexamples/carts:0.10.1  in deployment carts in namespace sockshop-dev
```

**Issue:** the image name contains a } at the beginning. This should be removed to pass the check in the test script. 

**Definition of Done:**
- [ ] The naming issue of the image is fixed

**Comment by TannerGabriel** [comment]
I will take on this issue!

**Comment by TannerGabriel** [comment]
**Extension of the issue:**
Wrong negative error codes are being thrown in some test utility functions that need to be replaced by valid error code e.g. -1 with 1.

**Issue**: Since the error codes are invalid the script doesn't exit when the error is thrown.

**Definition of Done:**
- [ ] Invalid error codes are replaced by valid ones and script exits when the error is thrown
