### ISSUE TITLE
Security requirements for CII 

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/keptn#2205]
For fulfilling the requirements of the [CII best practices](https://bestpractices.coreinfrastructure.org/en/projects/3588#security) we need to satisfy the following criteria (copy/pasted from the CII website):

1. The default security mechanisms within the software produced by the project MUST NOT depend on broken cryptographic algorithms (e.g., MD4, MD5, single DES, RC4, Dual_EC_DRBG), or use cipher modes that are inappropriate to the context, unless they are necessary to implement an interoperable protocol (where the protocol implemented is the most recent version of that standard broadly supported by the network ecosystem, that ecosystem requires the use of such an algorithm or mode, and that ecosystem does not offer any more secure alternative). The documentation MUST describe any relevant security risks and any known mitigations if these broken algorithms or modes are necessary for an interoperable protocol.
1. The security mechanisms within the software produced by the project SHOULD implement perfect forward secrecy for key agreement protocols so a session key derived from a set of long-term keys cannot be compromised if one of the long-term keys is compromised in the future.
1. the software produced by the project causes the storing of passwords for authentication of external users, the passwords MUST be stored as iterated hashes with a per-user salt by using a key stretching (iterated) algorithm (e.g., Argon2id, Bcrypt, Scrypt, or PBKDF2). See also OWASP Password Storage Cheat Sheet).

I would ask to comment on this issue how we are satisfying each item on this list. If not satisfied yet, what would be needed to satisfy the requirement?

**Definition of done**

- [ ] Satisfy requirement 1
- [ ] Satisfy requirement 2
- [ ] Satisfy requirement 3

**Comment by johannes-b** [comment]
### Keys/Tokens used in Keptn

To comment on the above-mentioned requirements, the subjects that are related to security questions are listed first. Hence, the following keys/tokens are used to secure communication ways in Keptn 0.7:

* (1) Authentication token for Keptn API: `keptn-api-token`
* (2) Keptn Bridge Credentials: `BASIC_AUTH_PASSWORD`/`BASIC_AUTH_USERNAME`
* (3) MongoDB Credentials: `admin_password`/`password`/`user`
* (4) Session token for WebSocket communication: `token`/`keptnContext`

Next, the approaches each key/token is generated and stored is briefly explained.

#### (1) Authentication token for Keptn API: `keptn-api-token`
- Generation:
  * `keptn-api-token`: Is a random alphanumeric string of 20 chars and base64 encoded.
- Storing: in the Kubernetes Secret: `keptn-api-token` 

#### (2) Keptn Bridge Credentials: `BASIC_AUTH_PASSWORD`/`BASIC_AUTH_USERNAME`
- Generation: 
  * `BASIC_AUTH_PASSWORD`: Is a random alphanumeric string of 16 chars and base64 encoded.
  * `BASIC_AUTH_USERNAME`: The default value is `keptn` that is base64 encoded.
- Storing: in the Kubernetes Secret: `bridge-credentials`

#### (3) MongoDB Credentials: `admin_password`/`password`/`user`
- Generation:
  * `admin_password`: Is a random alphanumeric string of 20 chars and base64 encoded.
  * `password`: Is a random alphanumeric string of 20 chars and base64 encoded.
  * `user`: The default value is `user` that is base64 encoded.
- Storing: in the Kubernetes Secret: `mongodb-credentials`

#### (4) Session token for WebSocket communication: `token`/`keptnContext`
- Struct: https://github.com/keptn/go-utils/blob/release-0.7.0/pkg/api/models/event_context.go#L17
- Generation:
  * `SECRET_TOKEN`: Is the `keptn-api-token` = 160-bit secret.
  * `token`: To generate this session token, the HS256 (Hash-based Message Authentication Code (HMAC) and SHA-256) is applied on the secret `SECRET_TOKEN`: https://github.com/keptn/keptn/blob/master/api/ws/client.go#L210
  * `keptnContext`: Is an UUID of the format: `xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx`
- Storing: Is not stored, but rather part of the server response and then used by the client to open a WebSocket communication. 

*Note on HS256:*
* Hash-based Message Authentication Code (HMAC) is an algorithm that combines a certain payload with a secret using a cryptographic hash function like SHA-256. The result is a code that can be used to verify a message only if both the generating and verifying parties know the secret. In other words, HMACs allow messages to be verified through shared secrets.

* The [JSON Web Algorithms RFC 7518](https://tools.ietf.org/html/rfc7518#page-7) states that a key of the same size as the hash output (for instance, 256 bits for "HS256") or larger MUST be used with the HS256 algorithm.
---

### Statements to the Requirements

*Requirement (1):* The only cryptographic algorithm Keptn is relying on is HS256. It is used for generating the session `token` for WebSocket communication. HS256 is not known to be a broken cryptographic algorithm when the secret has the same size as the hash output, i.e., 256-bit. Currently, the secret (`keptn-api-token`), which is used for hashing, has a size of 160-bit.  

*Requirement (2):* Perfect forward secrecy for key agreement protocols is currently not given since the secret - as used for the HS256 - is too short. When providing a secret with a 256-bit size, compromising a session key is "not" possible if a long-term key is compromised in the future.

*Requirement (3):* Statements about storing of passwords for authentication of external users: 
* (1) Authentication token for Keptn API: `keptn-api-token`: End-user facing
* (2) Keptn Bridge Credentials: `BASIC_AUTH_PASSWORD`/`BASIC_AUTH_USERNAME`: End-user facing
* (3) MongoDB Credentials: `admin_password`/`password`/`user`: Cluster internal usage and not end-user facing 
* (4) Credentials for WebSocket communication: `token`/`keptnContext`: Session key that is not stored

The two keys/tokens that are in the focus of this requirement are (1) and (2). Both are base64 encoded and stored in a Kubernetes secret. 

### Conclusion

**Requirement (1) and (2):** To fulfill these two requirements, the used secret must have a size of 256-bit. Moreover, it must not be the `keptn-api-token`. 
*Task:* To accomplish these requirements, a research task has to figure out whether it is possible to not use a persistently stored secret but rather create a random secret that is stored in memory and has a lifetime according to the lifetime of the corresponding WebSocket channel. If the WebSocket channel terminates, the secret has to expire. Besides, the random secret MUST have a size of 256-bit. 

**Requirement (3):** To fulfill this requirement, the keys must be stored as iterated hashes.
*Task:* To accomplish this requirement, a research task should evaluate how end-user facing credentials are stored by other products that are running on Kubernetes (e.g. Argo, Tekton). Based on that research outcome, a decision should be made on how to proceed in storing end-user facing credentials.

**Comment by johannes-b** [comment]
To address the above-mentioned requirements, two issues have been created: #2295 & #2296
