### ISSUE TITLE
Keptn Bridge: highlight stages more prominent in eventflow

### ISSUE THREAD

**Issue by rpionke** [keptn/keptn#2229]
Can we highlight the stages in the eventflow, so that the stages are more prominent?

Sample screenshot:
![image](https://user-images.githubusercontent.com/11491375/90727127-10686a80-e2c3-11ea-8327-af25aa234be6.png)

**Comment by johannes-b** [comment]
Hi, with the new sequence screen we will address this issue since the new screen will separate the executed sequences for each stage. Please see: 
![image](https://user-images.githubusercontent.com/729071/104891870-c539ad00-5971-11eb-93e3-af556faf597e.png)

The corresponding issue is: https://github.com/keptn/keptn/issues/2627

**Comment by rpionke** [comment]
This looks very promising!
I will close this issue here.
