### ISSUE TITLE
Keptn Bridge: Minor improvements for 0.7.1

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#2275]
- [x] **Qualit gates only - environment screen**

Problem: When running quality gates only use-case, a failed quality gate does not show up in the environment screen: 

![image](https://user-images.githubusercontent.com/729071/91954440-19652d00-ed02-11ea-9404-a015bc408071.png)

- [ ] **Icon matches status of expandable**

Situation: When clicking on the environment screen and stage, deployable services are expanded. Please change the icon to match the expanded state: 

![image](https://user-images.githubusercontent.com/729071/91954645-63e6a980-ed02-11ea-84e7-21863ef7fd2d.png)

**Comment by grabnerandi** [comment]
When having a stage that does direct deployments and the qulaity gate fails the quality gate status is not shown in the environment screen. probably related to what johannes highligted but in my case it is also the case for delivery when i have a direct deployment strategy

![image](https://user-images.githubusercontent.com/675886/91955149-0e5ecc80-ed03-11ea-8232-c0fb945a3dbc.png)

**Comment by grabnerandi** [comment]
Clickable links work - but - instead of showing the label name and the value and just make the value clickable its better to just show the label name and put the link behind that name. This makes the labels shorter and the UI cleaner. Also - there is no real value in seeing the partial link in the bridge as I am clicking on it anyway

Like in the image below. Just show "Dashboard Link" and make that clickable. no need to show parts of the actual link

![image](https://user-images.githubusercontent.com/675886/91955356-5847b280-ed03-11ea-85d5-59d8b9b7688f.png)
