### ISSUE TITLE
Bridge timeframe selector

### ISSUE THREAD

**Issue by alipatton10** [keptn/keptn#2280]
**Is your feature request related to a problem? Please describe.**
When running demos the bridge can get very cluttered especially as we tend to run them over and over again

**Describe the solution you'd like**
A time frame selector to allow the bridge to be filtered

**Describe alternatives you've considered**
Manually deleting the records from the DB

**Additional context**
A timeframe selector similar to the DT one would be good.

**Comment by alipatton10** [comment]
Additionally it would also be useful to have a way in the bridge to delete certain things such as if i run a deployment the first time but forget to provide the SLOs it would be good to have the ability to easily remove this without having to manually delete it in the DB

**Comment by johannes-b** [comment]
In the upcoming sequence screen (which is focused on the executions of task sequences) we want to add a timeframe selector: 

![image](https://user-images.githubusercontent.com/729071/106581770-86941d00-6543-11eb-94db-a415f8de4fbe.png)

I will use this issue for implementing the timeline selector.

**Comment by johannes-b** [comment]
I invested some more thoughts into the timeframe selector and don't want to introduce it (as proposed in the mockup) because I think there is an easier approach to address the problem of a cluttered sequence and service screen also with an easier component. 

Besides, I think that the timeframe selector is not the right component because there is not really a need to select a specific time window I'm interested in. E.g., why do I want to look at events that happened from last Monday to last Tuesday? What I'm interested in are the last 10 events that happened. 

My proposal: Let's initially load 25 events and provide an `show older Sequences` button to load the next 10: 

**Sequence screen**
![image](https://user-images.githubusercontent.com/729071/109611184-24bcd800-7b2e-11eb-85fb-234d787e7020.png)

**Service screen**
![image](https://user-images.githubusercontent.com/729071/109611233-356d4e00-7b2e-11eb-96b9-f79117f0675b.png)

*Question*
Do we need to refresh the filters?

**Comment by Kirdock** [comment]
At the moment there isn't a proper way to load 10 older sequences.
Because of the pull-interval we have x loaded Sequences. That means the loaded amount of sequences is dynamic and we can't just take the `pageKey`. We could calculate the `pageKey` with `(amountOfSequences / pageSize) + 1` but this would also be incorrect because we have decimals here. We could also increase the `pageSize` for the calculation of the `pageKey` but then we have to delete some fetched sequences.
