### ISSUE TITLE
API returns 200 OK on event if project or service doesn't exist

### ISSUE THREAD

**Issue by alipatton10** [keptn/keptn#2314]
I am currently updating the keptn alexa skill and I wanted to add some error handling validation so I changed the project name to one that doesn't exist and sent an event to event api. It still returned a 200 ok and a keptn context but that context doesn't appear in the bridge and it should not be returning a 200 OK. The same thing happened with a service that doesn't exist

**Environment**

keptn 0.7.0

**Affected Component**

* [ ] Docs
* [ ] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [ ] Bridge
* [ ] Gatekeeper
* [ ] Datastore
* [x] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**

in correct project still returns 200 ok in event API.
 here is the request body i sent
{
    "contenttype": "application/json",
    "data": {
        "canary": {
            "action": "set",
            "value": 100
        },
        "eventContext": null,
        "labels": {},
        "project": "keptnmnlnjlnksample",
        "service": "simplenode",
        "stage": "",
        "valuesCanary": {
            "image": "docker.io/grabnerandi/simplenodeservice:2.0.0"
        }
    },
    "source": "Keptn-Alexa-Skill",
    "specversion": "0.2",
    "type": "sh.keptn.event.configuration.change"
}

and the response body was

{
    "keptnContext": "d709bcde-7fc1-49e4-84df-4bb7d16ee8e1",
    "token": "xxxxxxxxxxx"
}

**To Reproduce**

send an event that should trigger a deployment but change project name to something that doesn't exist 

**Expected behavior**
an error response and code

**Current behavior**
200 ok

**Screenshots**

*
![Screenshot 2020-09-09 at 14 06 43](https://user-images.githubusercontent.com/41793795/92603398-2ad0ab00-f2a7-11ea-8dfb-05612dfbc4cc.png)
*Additional context**

**Comment by christian-kreuzberger-dtx** [comment]
As Keptn is event-driven, in my opinion, the API is behaving correctly by accepting the event and signaling to you with a status code 200 that the event has been accepted.

IMHO validating the event payload at this early stage is not feasible (it would create a lot of computing and network overhead), but of course this could be done.

I'm sure @agrimmer also has an opinion on this.

**Comment by alipatton10** [comment]
I understand your point but if we stick with that approach how could we properly integrate with things like change management tools? If i send this via CLI I get an error so surely the API should function in the same way
![image](https://user-images.githubusercontent.com/41793795/92614984-89e8ec80-f2b4-11ea-8157-148add5a7520.png)

**Comment by christian-kreuzberger-dtx** [comment]
> If i send this via CLI I get an error so surely the API should function in the same way

the error you are seeing via the CLI is coming via an additional websocket connection, and not as a response from the API.

**Comment by alipatton10** [comment]
ok but if the API isn't the same it is kind of pointless. Are we saying that if someone wants to control keptn from anything other than the CLI they will have to do their own client side error processing?

**Comment by christian-kreuzberger-dtx** [comment]
> Are we saying that if someone wants to control keptn from anything other than the CLI they will have to do their own client side error processing?

Exactly.

Paging @johannes-b on this use-case related issue.

**Comment by johannes-b** [comment]
I did a quick research on the issue to get an opinion about the problem. 
Interesting readings that I found: 
- https://runnable.com/blog/error-handling-in-event-based-systems
- http://oceanrep.geomar.de/14524/1/ARES2007.pdf (page 4) 
---
Keptn is per design an event-based system with an API that has not the request/response behavior of a monolithic application, i.e., when sending an event to Keptn, the response of that call can not include the result of the event processing (since this will happen a couple seconds/minutes later). Thus, I agree with @christian-kreuzberger-dtx on that point that a POST on `/event` with a 200 response is valid. 

However (and back to use case of @alipatton10 ), Keptn could already do a sanity check of the incoming event - at least for the properties `project` and `service`. From a logical perspective, Keptn knows the entities (projects/services), and when it receives an event that does not correlate to one of those entities - why processing it?

**Comment by christian-kreuzberger-dtx** [comment]
> From a logical perspective, Keptn knows the entities (projects/services),
I agree!

> and when it receives an event that does not correlate to one of those entities - why processing it?

a) to create it :) (e.g., create project / create service)
b) maybe as a future use-case: to auto-detect it (e.g., after restoring from a backup) or to indicate that it should be fetched from somewhere else (e.g., import a repo, import config from external provider, ...)


I've also been working with event-based systems, and the rule of thumb was (similar to what your research has shown): accept as many events as possible, with as little validation as possible (to increase throughput and lower latency); errors are handled later.

But I agree with @alipatton10s use-case: It's virtually impossible to catch such an error via the API right now. What is needed here is a mechanism via the API that we can use to query whether the event has been processed or not (e.g., the get event endpoint).

**Comment by agrimmer** [comment]
That you get a 200 response is intended as this response only says that the event was successfully published. Therefore, I agree with @christian-kreuzberger-dtx and @johannes-b. Furthermore, the API has no chance to check/predict whether any subscriber to the published event would produce an error.

However, I completely understand your use case and we will solve it as follows:

After a service has executed a task like `project.create`, `service.create`, `configuration-change`, etc., the service has to 
 confirm the execution and its result with a `.finished` event (e.g. `project.create.finished`). This `.finished` event then contains a potential error. 

In your service, you can then either (1) subscribe to the `.finsihed` event if the service runs within the cluster or use the Keptn API endpoint `/keptn/api/mongodb-datastore/event` to query the `.finished` event using the keptncontext.

**Good news:** This is exactly how we are implementing the eventing in Keptn 0.8.0!

**Comment by grabnerandi** [comment]
Thanks @agrimmer for the explanation and the way forward. 
To make integrations for external tools such as Alexa, Jenkins, Azure DevOps ... easier I wonder if we should also think about adding "use case API endpoints",e .g: "DO configuration change", "START evaluation", ... which mimic what the Keptn CLI is doing. I assume that the CLI is first validating if project, service, stage ... are valid and is otherwise returning errors to the end user. Instead of having every external tool implement the same checks and the same "wait for success" I wonder if it will be easier for our external tool integrators to call a single api such as /api/configchange, /api/evaluation ... -

**Comment by christian-kreuzberger-dtx** [comment]
@grabnerandi Introducing every event with a separate endpoint would introduce a lot of development overhead, I'd like to avoid that.

The CLI actually does not do specific things for each event, it just opens a websocket connection and streams the log output.
That's something we could mimic in the API, e.g., we could introduce a flag that indicates that we want to wait for a result, e.g.:

```
POST /event?streamWebsocket=true&streamWebsocketTimeout=60
```

This could indicate that I'm interested in the websocket response and I want to wait for max. 60 seconds.

**Comment by christian-kreuzberger-dtx** [comment]
The discussion seems to have died on this. Is this still needed? Is anyone willing to implement a POC?
