### ISSUE TITLE
Include quality gate in CLI use case flag

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/keptn#2379]
The CLI flag `use-case` for `keptn install` does only list the `continuous delivery` use case. 
For installing the Keptn Quality Gates, this flag has to be omitted.

In my opinion it would make it more clear to also include the `--use-case=quality-gates` to the install option to have a streamlined installation experience.

Thus, also the install help command should list it (current version):
```
flags:
  -u, --use-case string                The use case to install Keptn for [continuous-delivery]
```

Desired version:
```
flags:
  -u, --use-case string                The use case to install Keptn for [quality-gates, continuous-delivery]
```

**Comment by christian-kreuzberger-dtx** [comment]
This might be relevant for 0.8.0. For 0.7.x the flagging makes perfect sense, as there is no such thing as a quality-gates use-case specific installation (while there is one for continuous-delivery).

**Comment by agrimmer** [comment]
Since 0.7.0, we consider all Keptn components for quality gates as core (i.e. the lighthouse-service). 
Therefore, we intentionally removed the option `--use-case=quality-gates`. 
However, if a user knows the former CLI version, he/she gets a hint: https://github.com/keptn/keptn/blob/0cde1b5b08b6f95088e60c1141226f6491e79e11/cli/cmd/install.go#L86
