### ISSUE TITLE
Unable to set or override deployment strategy via keptn onboard cli command

### ISSUE THREAD

**Issue by warber** [keptn/keptn#2538]
The `--deployment-strategy` flag does not set/override a deployment strategy for a given stage.

**To Reproduce**

Given a project using the following trivial `shipyard.yaml`

```
stages:
  - name: "dev"
  - name: "production"
```

when onboarding a service using the following command (note the `--deployment-stragety` flag) :
```
keptn onboard service <svc-name> --project=<project-name> --chart=./<chart-name> --deployment-strategy=direct
keptn send event new-artifact --project=<project-name> --service=<svc-name> --image=<img-name> --tag=<tag>

```
then the continuous delivery process stops at the `dev` stage, i.e., the service is not deployed in the `production` stage.
The bridge looks as follows:

![bridge-screenshot](https://user-images.githubusercontent.com/72415058/95971855-07eb6680-0e12-11eb-8eb4-cf2bb778b291.png)

The logs of the `gatekeeper-service` reveal that there is no deployment strategy is defined for, hence the `--deployment-strategy` flag was not taken into consideration.

![gatekeeper-logs](https://user-images.githubusercontent.com/72415058/95971968-2e110680-0e12-11eb-8952-e0163954f1e6.png)

* Keptn Version (`keptn version`): 0.7.1

**Expected behavior**
The onboarded service passe both stages, `dev` as well as `production`

**Current behavior**
The onboarded service is only deployed in `dev` stage, as to keptn there is no deployment strategy is defined

**Comment by agrimmer** [comment]
In order to execute the continuous-deployment use case with Keptn, we always assume that there is a `deployment_strategy` defined in the shipyard. Hence, the gatekeeper-service tries to parse the `deployment_strategy` field defined in the shipyard. However, your shipyard does not define any`deployment_strategy`. 

I agree that this assumption is not reasonable especially when defining a deployment strategy using the `--deployment-strategy` flag of the CLI.

However, in 0.8.0 we will remove this `--deployment-strategy` flag. Hence, I would propose to not fix this issue.

**Comment by christian-kreuzberger-dtx** [comment]
> However, in 0.8.0 we will remove this --deployment-strategy flag. Hence, I would propose to not fix this issue.

Agreed. I'll leave this issue open and assign it to 0.8.0 though.
