### ISSUE TITLE
Show the unit of an SLI on the Keptn's bridge and roll up calculated response time metrics to milliseconds

### ISSUE THREAD

**Issue by leonvzGit** [keptn/keptn#2637]
**Is your feature request related to a problem? Please describe.**

I have created calculated metrics for response time for every test step on a given service, the bridge displays this in microseconds, this is expected, but I would appreciate it if all response time metrics can be rolled up as they are in the Dynatrace interface, to milliseconds and then to seconds. This is causing some confusion for the practitioners consuming the data on the Bridge.

**Describe the solution you'd like**
I would like the response time calculated metrics to also be rolled up to milliseconds,  The unit should also be displayed in the Bridge interface.

**Describe alternatives you've considered**

**Additional context**
The screenshot below shows the response time p90 and 95 etc in milliseconds (non-calculated metrics) the calculated metrics, however, are shown in microseconds:
![image](https://user-images.githubusercontent.com/14150187/98206982-9a7bb300-1f43-11eb-9f37-27c001453bee.png)

**Comment by grabnerandi** [comment]
Hi Leon. I have one temporary solution for you but still agree we need to get the metric unit into the Bridge.
The Dynatrace SLI Service that queries data from Dynatrace - either by parsing the SLI.yaml or by parsing a Dynatrace Dashboard already provides the capability to convert all MicroSeconds into Milliseconds when data is retrieved by parsing a dashboard. The same is true for "well known response time metrics" such as the built-in servie response time when it is used in the SLI.yaml.

Now - if you want the Dynatrace SLI Service to know that your metric definition in the SLI.yaml is MicroSeconds and that it should convert it to Milliseconds then you can use the following prefix for your Query:

Assuming your query looks something like this right now:
```
teststep_rt_echo: metricSelector=calc:service.teststepresponsetime:merge(0):avg:names:xxxxx
```

Then you can prefix it with MV2;<Unit>; - so - the above query would look like this:
```
teststep_rt_echo: MV2;MicroSecond;metricSelector=calc:service.teststepresponsetime:merge(0):avg:names:
```

When the Dynatrace SLI Service parses the SLI.yaml and finds the query to begin with MV2 it assumes the next value after ; is the Metric Unit. If it is MicroSecond it will automatically convert it to MilliSecond.

Give this a try. I think though - we should extend the SLI capability in Keptn to not only return the SLI value but also the Unit so that the Bridge can display the Unit and eventually also provide some conversions

**Comment by leonvzGit** [comment]
Thank Andi
