### ISSUE TITLE
Link back to evaluation from Environment Failed Quality Gates in Bridge 0.7.2

### ISSUE THREAD

**Issue by leonvzGit** [keptn/keptn#2696]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
The  Environment view in Bridge 0.7.2 shows the Quality Gates that failed, I would like to have a link back to the evaluation in the services view from the environment view where quality gates failed

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/14150187/99498565-5abfbd00-2980-11eb-8cfa-de296047e433.png)

**Comment by johannes-b** [comment]
Hi @leonvzGit, 
great idea for improvement! 
Let me add it to the backlog of the Bridge for 0.8.0.

I labeled it with *help wanted* because the implementation should be straight forward:
-  The bridge has deep linking functionality that allows linking to the event (evaluation-done): https://keptn.sh/docs/0.7.x/reference/bridge/deep_linking/#links-to-project-and-events 
  `project/:projectName/:serviceName/:contextId/:eventId:`
- Add a label next to the text `Quality gate of ... failed with a score of: 73 - go to: Evaluation result`  *Evaluation result* should then link to the evaluation done event in the services screen (--> `project/:projectName/:serviceName/:contextId/:eventId:`)
