### ISSUE TITLE
Include yq binaries

### ISSUE THREAD

**Issue by Dynatrace-Adam-Gardner** [keptn/keptn#273]
**Is your feature request related to a problem? Please describe.**
Install fails on GKE cluster 1.12.7-gke.7 due to lack of `yq`

Results in (at least, but possibly other issues): `no healthy upstream` for Jenkins.

**Describe the solution you'd like**
Include the `yq` binary and alias it.

```
wget https://github.com/mikefarah/yq/releases/download/2.3.0/yq_linux_amd64 -O ~/yq
chmod +x ~/yq
echo "alias yq="~/yq"" >> ~/.bashrc
source ~/.bashrc
```

**Describe alternatives you've considered**
`yq` repositories and recommended installation options all fail. Only way to successfully install yq is using the binary.

**Additional context**
Related issues:
- https://github.com/mikefarah/yq/issues/232
- https://github.com/keptn/keptn/issues/136

**Comment by johannes-b** [comment]
Hi, 
we defined `yq` as one of the [prerequisites](https://keptn.sh/docs/0.2.0/installation/setup-keptn-gke/) for keptn 0.2.0.

However and coming soon, a bunch of the prerequisites will become obsolete since we handle the keptn install process via a pod in the cluster (#250). In other words, the only prerequisite(s) will then be `kubectl` (and `gcloud` for GKE).

The #250 will address this issue.

**Comment by dirkwall** [comment]
`yq` is mentioned in the prerequisites and will become obsolete with the new installer.
