### ISSUE TITLE
Filter number of Quality Gate evaluation shown

### ISSUE THREAD

**Issue by leonvzGit** [keptn/keptn#2744]
**Is your feature request related to a problem? Please describe.**
We have 28 services in 1 project doing at least 3 quality evaluations per day per service against 15+ slo's we have notices a performance degradation when the services are loaded on Keptn's bridge

**Describe the solution you'd like**
We would like to be able to filter the number of evaluation results shown on keptn bridge, to the last 15 by default and the option to choose the amount

**Describe alternatives you've considered**
No other option considered
**Additional context**
The filter should be on the heatmap and chart, or the event 
![image](https://user-images.githubusercontent.com/14150187/100969619-069a0880-353c-11eb-9754-fd32b5b0a683.png)

**Comment by cjmckenna** [comment]
+1 on this

**Comment by christian-kreuzberger-dtx** [comment]
>  We have 28 services in 1 project doing at least 3 quality evaluations per day per service against 15+ slo's

So that would be 84+ evaluations per day. Can you provide an approximate timeframe (e.g., 4 weeks)? This would help us in estimating the number of evaluations and therefore cloud-events.

**Comment by sergiohinojosa** [comment]
Hi guys, 
just a quick comment. Implementing the amount evaluations should match the events on the left side as well, atm there is no way of showing more and the number of events does not match the number of evaluations. Adding filter by time should also reduce the mongodb impact

![image](https://user-images.githubusercontent.com/20834538/106010409-b366b100-60b9-11eb-8cfd-b4f006f3c9fb.png)


Thanks and best
Sergio

**Comment by christian-kreuzberger-dtx** [comment]
I understand your idea, but while it sounds simple, I believe in the end this might not be possible, as all sort of events can appear on the left side (e.g., problem open without evaluations, evaluations performed in a different stage).

Anyway, I think we have a GH Issue about a timeframe-picker for CloudEvents, which could also be applied to the heatmap, but as we'll need to work on some details (e.g., what happens if the timeframe is too big).
