### ISSUE TITLE
Double-check the README.md of each microservice

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#2775]
The README.md of various Keptn components are out-dated. This issue is dedicated to updating the “README”-documentation of the components listed below. 

**Keep an eye on:**

* Update description of the functionality
* Referenced CloudEvents, what are required properties?
* Deployment instructions / Uninstall instructions

**Update README of:** 

- [ ] api
- [ ] bridge
- [ ] cli
- [ ] configuration-service
- [ ] distributor
- [ ] gatekeeper-service
- [ ] helm-service
- [ ] installer
- [ ] jmeter-service
- [ ] mongodb-datastore
- [ ] openshift-route-service
- [ ] remediation-service
- [ ] shipyard-controller
- [ ] upgrader (add Readme.md how an upgrade is managed)

**Comment by warber** [comment]
@johannes-b 
I propose to create a **template** for README files of services in order to harmonize the documentation of our services.
The template should at least contain:

* **Description**: A brief introduction to the purpose/functionality of the service. Ideally, this contains a very high-level *component diagram* that shows the relation to other services the service is interacting with.
* **Concept of Execution**: A more detailed description of the input/output behavior of the service. It shall be visible which *CloudEvents* the service is supposed to receive and send. Could be textual or in the form of a *sequence diagram*
* **Configuration**: a list of **environment** variables and/or **configuration files** to adapt the execution of the service. Environment variables shall be marked with *mandatory* or *optional*
* **Deployment / Uninstall instructions**
