### ISSUE TITLE
Remediation service does not handle problem event with state CLOSED

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#2895]
If the monitoring tool, e.g: Dynatrace - sends a "sh.keptn.events.problem" when a problem is closed it is currently handled by the dynatrace-service which adds missing data such as project, stage, service and then again sends a "sh.keptn.events.problem" to let the remediation service know about this.

Currently there are two issues with this
#1: The remediation-service is not hanlding sh.keptn.event.problem as the ProblemEventHandler is not called at all.
#2: To avoid any confusion and potential double processing we should introduce a sh.keptn.events.problem.close similar to the .open event as right now the same event is handled by more than one service but based on the data on the event and who is sending it differnet services act or dont act.

This issue current leads to inconsistent behavior when problem close events are sent from Dynatrace
**Environment**
* Keptn Version (`keptn version`): 0.7.3

**Comment by christian-kreuzberger-dtx** [comment]
Just to add:

Dynatrace sends a `sh.keptn.event.problem` CloudEvent - https://github.com/keptn/spec/blob/0.1.7/cloudevents.md#problem
Dynatrace-Service processes this event, and fills in service, stage and project. It then sends a `.problem.open` CloudEvent - https://github.com/keptn/spec/blob/0.1.7/cloudevents.md#problem-open

ad 1: Yes, remediation-service can not handle `.problem` events (in Keptn 0.7.x), only `.problem.open`. This is by design, as we can not "cancel" an ongoing remediation (see Issue #1616 and the [event-stream for remediations](https://user-images.githubusercontent.com/10980861/83032100-b5153c00-a035-11ea-9e9e-71d94b026d72.png) for details).
ad 2: 
> To avoid any confusion and potential double processing we should introduce a sh.keptn.events.problem.close

This was proposed in https://github.com/keptn/spec/pull/22 already, but back then it was decided that we don't need it yet.
In fact, dynatrace-service has a special handling for closing problems, such that we keep track of it via CloudEvents:
https://github.com/keptn-contrib/dynatrace-service/blob/945f67a95ace00cd5bbe8ec3998c5fc0bafa304e/pkg/event_handler/problem_handler.go#L52-L75
as well as
https://github.com/keptn-contrib/dynatrace-service/blob/945f67a95ace00cd5bbe8ec3998c5fc0bafa304e/pkg/event_handler/problem_handler.go#L77-L108


Anyway, I believe we need to consider this issue for Keptn 0.8.0 and therefore I would follow Andis suggestion (and Ermins [PR](https://github.com/keptn/spec/pull/22)) to introduce a `problem.close` event.
