### ISSUE TITLE
Show Shipyard Version in Keptn Bridge

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#2909]
Now that #2804 has been implemented and merged, we could show the shipyard version in Keptn Bridge, e.g., on the main screen:
![image](https://user-images.githubusercontent.com/56065213/104620815-b14f2c00-568f-11eb-99da-ebe928cccd26.png)

FYI @ermin-muratovic @johannes-b please decide whether this makes sense and where to put this information.

**Comment by johannes-b** [comment]
To help users migrating from 0.7.x to 0.8, this is a good idea! 

I propose to add this information to the project tile since we have no other way of managing project-specific config yet. In the future, a settings page where we manage the Git-upstream would be the right place to deal with the shipyard version. 

For now, I propose the following: 

![image](https://user-images.githubusercontent.com/729071/106580167-dffb4c80-6541-11eb-9b5d-ebc3775f82d7.png)

**Comment by johannes-b** [comment]
In the meta-data of Keptn, specify (hard-coded) the currently supported spec version. Use this information to perform the validation in the UI.
