### ISSUE TITLE
Integration Tests: QualityGates Integration Test fails on minishift

### ISSUE THREAD

**Issue by warber** [keptn/keptn#2951]
The "Quality Gates Standalon" Test works on GKE and k3s but fails on minishift.

https://github.com/keptn/keptn/runs/1728653188?check_suite_focus=true

```
[...]
keptn update project PROJECTNAME --git-user=GIT_USER --git-token=GIT_TOKEN --git-remote-url=GIT_REMOTE_URL

Starting to create project
Project created successfully
Verified that project exists via the API
Starting to create service
Service created successfully
Sending start-evaluation event for service 'wrong-service' in stage hardening
Sending start-evaluation event for service 'wrong-service' in stage 'wrong-stage'
Sending start-evaluation event for service 'wrong-service' in stage 'wrong-service' in project 'wrong-project'
Sending start-evaluation event for service frontend in stage hardening
Getting evaluation-done event with context-id: 7507207d-6474-4c98-ac46-44bfeb66c87b
parse error: Invalid numeric literal at line 1, column 3
parse error: Invalid numeric literal at line 1, column 3
Error: [2021-01-19 15:32:01] ERROR: Checking .source, expected 'lighthouse-service', got '' ❌
Executing cleanup...
Delete lighthouse-config configmap
Error from server (NotFound): configmaps "lighthouse-config" not found
Deleting project musicshop
Starting to delete project
Deleting services of project musicshop...
Deleting service frontend
Service deleted successfully
Project deleted successfully
Shipyard of project musicshop cannot be retrieved anymore. After deleting the project, the namespaces containing the services are still available. This may cause problems if a project with the same name is created later.
Uninstalling dynatrace-sli-service
Error from server (NotFound): deployments.extensions "dynatrace-sli-service" not found
Removing secret dynatrace-credentials-musicshop
Error from server (NotFound): secrets "dynatrace-credentials-musicshop" not found
Error: Process completed with exit code 1.

```

**Comment by christian-kreuzberger-dtx** [comment]
This did not fail on K3s 6 days ago (2021-01-14): https://github.com/keptn/keptn/actions/runs/484455321

On Minishift we've had this error for a while now.

To get more insights, I recommend looking at the "parse error" presented:

```
Sending start-evaluation event for service frontend in stage hardening
Getting evaluation-done event with context-id: 7507207d-6474-4c98-ac46-44bfeb66c87b
parse error: Invalid numeric literal at line 1, column 3
parse error: Invalid numeric literal at line 1, column 3
Error: [2021-01-19 15:32:01] ERROR: Checking .source, expected 'lighthouse-service', got '' ❌
```

I'm guessing that either retrieving the cloudevent failed or the content of the cloudevent contains an error message.

**Comment by bacherfl** [comment]
The problem here is that for some reason the dynatrace-sli-service is not able to reach the DT tenant and thus retrieving the metric values for the service fails:

```
dial tcp: lookup <dynatrace-tenant-hostname> on 172.30.0.2:53: read udp 172.17.0.24:47228-\u003e172.30.0.2:53: i/o timeout
```

When tested locally on minishift, the dynatrace-sli-service is able to communicate with the DT, so this problem appears to only happen in this particular scenario (running minishift on GitHub actions). Moving this item to the Backlog for now due to other issues currently having a higher priority

**Comment by christian-kreuzberger-dtx** [comment]
some things to try out to get more troubleshooting info:

1. Set `--network-nameserver 8.8.8.8` when calling `minishift start`
2. Try to execute a container that tries to access keptn.sh or google.com, e.g., `kubectl run -i --restart=Never --rm test-${RANDOM} --image=alpine:3.11 -- sh -c "wget https://keptn.sh"`
3. Try to use tmate https://github.com/marketplace/actions/debugging-with-tmate to connect to the gh action via SSH

To do any of this, commit your changes to a branch by selecting your branch in "use workflow from", e.g.:
![image](https://user-images.githubusercontent.com/56065213/105958052-657e8880-607a-11eb-991b-c75aeabea764.png)

**Comment by christian-kreuzberger-dtx** [comment]
Using the `kubectl run` command above has shown that the cluster can not reach https://keptn.sh (it stops with a "bad address" error). To me this sounds like a problem with Minishift not resolving the hostname.

I tried to counter this by adding `--network-nameserver 8.8.8.8` and by trying a different GH action for setting up the cluster,
```
      - name: Setup OpenShift
        uses: manusa/actions-setup-openshift@v1.1.2
        if: env.CLOUD_PROVIDER == 'minishift-on-GHA'
        with:
          dns ip: '8.8.8.8'
          oc version: 'v3.11.0'
          github token: ${{ secrets.GITHUB_TOKEN }}
```

but the error persisted. I'll try tmate now.

**Comment by christian-kreuzberger-dtx** [comment]
After debugging with tmate, I found that the problem persists when using `alpine` based containers, but it works on Ubuntu. This is the same behaviour that we found with Keptn 0.7.x in the case of searchdomain problems:
https://keptn.sh/docs/0.7.x/troubleshooting/#fully-qualified-domain-names-cannot-be-reached-from-within-the-cluster

A quick check revelead that on GH Action runners the searchdomain is set to "randomstring.cx.internal.cloudapp.net", which seems to cause the problem.

**Comment by christian-kreuzberger-dtx** [comment]
# Final Report on this Issue

This issue is occurring on Minishift on GitHub actions due to the search-domains set in `/etc/resolv.conf`. For whatever reason, this does not affect K3s on GitHub actions (they probably have a fix for that?).
The root-cause is that on alpine based images (all of our images are based on alpine) there is a problem with musl/libc when it comes to resolving hostnames. We have seen the same issue before, and documented it [in our Troubleshooting Guide](https://keptn.sh/docs/0.7.x/troubleshooting/#fully-qualified-domain-names-cannot-be-reached-from-within-the-cluster) already. 

The only way *we* can fix this is by using a non-alpine based base-image (e.g., debian-slim).

Anyway, as this is not something we can "just do" to fix the integration tests, I'm closing this with wont-fix.

**Comment by christian-kreuzberger-dtx** [comment]
todo: disable test on minishift
