### ISSUE TITLE
Use github.com/stretchr/testify/require instead of general asserts

### ISSUE THREAD

**Issue by cpanato** [keptn/keptn#3149]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Replace any general asserts in the testing code to use `github.com/stretchr/testify/require` this was added in this PR https://github.com/keptn/keptn/pull/3005 to try to make the test code cleaner and easier to see what is being checked.

This is just a suggestion, but other projects use that to assert the tests.

It might touch all *_test.go files.
I volunteer myself to update the tests

/cc @christian-kreuzberger-dtx 

**Describe alternatives you've considered**

**Additional context**

**Comment by christian-kreuzberger-dtx** [comment]
Hi,

sorry for the long waiting time.

Generally speaking, I think it is viable to change this. Though I'd like to hear opinions from @bacherfl and @warber if that's something we want to do.

**Comment by cpanato** [comment]
this is something y'all want? or should we close the issue?

**Comment by warber** [comment]
@cpanato So, basically, the behavioral change would be to fail the test early whenever an assertion (using `require`) fails, right?
I think that's good and it's the behavior I am used to when for example working with JUnit.
I would say, please go for it wherever it makes sense to you. Plus: If you feel motivated, feel free to do some cleanup of the test code here and there if you stumble across dirty edges :-P
Plus: If you want to work on this issue would it be possible to split the contribution into multiple PRs (say one per service/project) instead of one big PR?

**Comment by cpanato** [comment]
@warber thanks! yes i will split in services to make it easier to review :)

I will start asap

**Comment by cpanato** [comment]
- [ ] api
- [ ] cli
- [ ] codecov.yml
- [ ] configuration-service
- [ ] distributor
- [ ] helm-service
- [ ] jmeter-service
- [ ] lighthouse-service
- [ ] mongodb-datastore
- [ ] platform-support
- [ ] remediation-service
- [ ] secret-service
- [ ] shipyard-controller
- [ ] statistics-service

**Comment by cpanato** [comment]
it is not closed, can we reopen that, there are more things to do :)

@bacherfl
