### ISSUE TITLE
Support for multi-arch images of keptn components (ARM)

### ISSUE THREAD

**Issue by imrajdas** [keptn/keptn#3409]
**Is your feature request related to a problem? Please describe.**
Currently, keptn docker images are not built for multi-arch support.

**Describe the solution you'd like**
Add arm64 and amd64 support for the docker images using `docker buildx`. Currently, amd64 is supported, but not arm64

**Describe alternatives you've considered**

**Additional context**

**Comment by rajdas98** [comment]
cc: @jetzlstorfer

**Comment by christian-kreuzberger-dtx** [comment]
I've already looked at this at
* https://github.com/keptn/gh-action-build-docker-image/issues/1
* and PR https://github.com/keptn/keptn/pull/3055

At this point it's not feasible to build ARM containers/images using `docker buildx`, as the build process takes multiple times longer using `buildx` (we are talking several hours instead of 30 minutes).

If we get an ARM/ARM64 based GH Action Runner the story might be different.

**Comment by rajdas98** [comment]
> If we get an ARM/ARM64 based GH Action Runner the story might be different.

Is it taking the same time after making the pipelines parallel for AMD and ARM?

**Comment by christian-kreuzberger-dtx** [comment]
Due to our mono-repo our CI already consists of many parallel steps (unit tests, building docker images, building CLI for multiple architectures, ...). 
Adding parallel steps for Docker Builds will block other steps like unit tests and building the CLI.

In addition, just building images for ARM/ARM64 is not the whole story. Those images also need to be e2e/integration tested, etc... 
If the use-case is that someone needs a one-time build, then it's absolutely possible to do that by cloning the repo, checking out the respective branch/tag, and running `make build-docker` locally.

**Comment by rajdas98** [comment]
@christian-kreuzberger-dtx, I thought the ARM support would be good for the community. Currently, I don't have this requirement. You may close this issue if you want. Thanks.

**Comment by rajdas98** [comment]
One more way is to use more than one CI tool(circleCI + GitHub workflow) to reduce pipeline time. But this will create an overhead to manage two CI tool.

**Comment by christian-kreuzberger-dtx** [comment]
> I thought the ARM support would be good for the community

Long-term, yes. We can leave the issue open, such that people can comment on it or upvote it if they have this requirement.

**Comment by nlamirault** [comment]
Hi, any news on this feature ? It could be nice to try Keptn on K3S running on RPi 4

**Comment by oleg-nenashev** [comment]
IMO it is a roadmap candidate. Arm is becoming more and more popular server architecture, including the K8s clusters. And also new Apple workstations. Creating preview packaging is relatively easy (we did it in Jenkins), having test automation is more tricky.

IMO a roadmap candidate. Maybe the same for RISC-V

**Comment by mowies** [comment]
I managed to get a PoC working in this PR here: https://github.com/keptn/keptn/pull/7365

**Comment by nlamirault** [comment]
any news on this feature ?

**Comment by nlamirault** [comment]
do you think it is possible to have this feature for https://github.com/keptn/keptn/milestone/59

**Comment by mowies** [comment]
Hi @nlamirault !
We can't provide an official version of Keptn with ARM support because not all of our dependencies are supported on ARM.
We use Bitnami's MongoDB Helm chart as a database and bitnami does not provide any ARM mongo images.
This is why we don't have ARM support yet in Keptn.

**Comment by nlamirault** [comment]
@mowies it's not possible to use the Bitnami Helm chart and change the Docker image to use the official Mongo Docker image ? 

https://hub.docker.com/_/mongo

**Comment by mowies** [comment]
No, unfortunately that's not so easy to do. Bitnami has lots of custom stuff in it's images in addition to their custom chart.

**Comment by thisthat** [comment]
Given the limitation of Bitnami, I will close this issue. Please, reopen it if the situation changes.
