### ISSUE TITLE
Bridge doesn't list failed quality gate evaluations in Environment Screen

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#3438]
While testing Keptn 0.8.0, I noticed that Bridge doesn't show failed quality gate evaluations in environment screen, e.g.:

![image](https://user-images.githubusercontent.com/56065213/109964632-351bb100-7cee-11eb-8bb2-72abf67c02cc.png)

But:
![image](https://user-images.githubusercontent.com/56065213/109964670-4369cd00-7cee-11eb-85ab-98758bb417aa.png)

**Comment by Kirdock** [comment]
Root cause is probably `trace.isEvaluation()`.
Event type of a evaluation in delivery: `sh.keptn.event.evaluation.triggered`
Event type of a evaluation triggered by the CLI for a specific stage: `sh.keptn.event.${Stage}.evaluation.triggered`
https://github.com/keptn/keptn/blob/eb31fc0a3b551a27bc80b9753df1a384352eb4bd/bridge/client/app/_models/trace.ts#L206-L208
