### ISSUE TITLE
Show history of quality gates results for each service

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#3547]
## User story

Status quo: The environment screen shows the actual quality gate result for each service. #3491 

![image](https://user-images.githubusercontent.com/729071/111272027-56f02e80-8632-11eb-9261-9ff2f5b04545.png)

**Enhancement:** As a user, I would like to see the history of the quality gate results for a service, by taking a look at the last 5 evaluations. 

**Details:**
- Add the last 5 evaluations to a service similar to the approach shown here: 
- The score on the right (e.g., 55) is the actual score. Hence the user gets the same behavior like on the Heatmap on the service screen.
- Attention: No extra API calls for fetching the previous evaluations should be sent to avoid overloading the API with this enhancement. 

![image](https://user-images.githubusercontent.com/729071/130911201-e5d7a8e8-42e2-4110-88c6-654fc22ea4da.png)

### Acceptance criteria

- [x] I see the previous evaluations to derive a trend 
- [x] Proper handling of corner cases:
  - No previous evaluation is available
  - Just 1-4 previous evaluations are available 

### Definition of Done
- [x]  Everything in acceptance criteria implemented and manually tested
- [x]  Added unit tests
- [x]  Put attention to test corner cases
- [x]  Documentation updated

**Comment by Kirdock** [comment]
Note (scaling issues):
With this change, the bridge server would need additional `stages x services` API calls.

Solution 1 (worst case, additional stages x services API calls):
The bridge server fetches the last 5 events for each service for each stage

Solution 2 (additional `count services` API calls):
We split the response of the project endpoint into `information on the left` and `information on the right`.
`/project/{projectName}/environment`: information about stages and services (name, image, last sequence, last evaluation, count remediation, count approval)
`/project/{projectName}/environment/stage/{stage}`: stage with service information (name, image, last 5 evaluations, deployment URL,  remediations, approvals)
The second call can be done on demand then. On selection, the data is updated.
Need to think about: There may be inconsistencies between the information on the right and the information on the left because it's differently updated. A change in one view should trigger (an API call) in the other view.
