### ISSUE TITLE
Fine-tune Spellchecking GH Action to be less restrictive for source code

### ISSUE THREAD

**Issue by warber** [keptn/keptn#3627]
Problem: The [spellchecking action](https://github.com/keptn/keptn/actions/workflows/spelling.yml) is used to detect misspellings in all kinds of files, including source code. While we already disabled the spellcheck for `*_test.go` files, there is also the need to restrict the spellchecking even more for regular source code files.

For example: having an import statement like `import k8serr "k8s.io/apimachinery/pkg/api/errors"` is totally fine, however, `spellcheck` complains that it cannot identify the word `serr` to be valid. Hence, it needs to be added to the list of ignored files. During the first time using the spellcheck action we've identified many similar situations.

So the question arose whether we can configure `spellcheck` to be more "developer-friendly".
On one hand, we want to be more flexible while naming things in source code, and on the other hand we don't want to lose the ability to identify misspellings/typos which could eventually be visible to the end-user. 

Tasks: 

- [ ] investigate if and how `spellcheck` can be relaxed for source code files

**Comment by jsoref** [comment]
## create patterns for exceptions on words

`k8serr` is best addressed by adding a pattern -- https://github.com/check-spelling/check-spelling/wiki/Configuration-Examples:-patterns

```
# kubernetes abbreviation
[Kk]8s
# <word>v#
[Vv]\d+(?:\b|(?=[a-zA-Z_]))
```

The first pattern would cause the bot to only see `err` (which is a word, as in `to err is human`).

## only considering strings and output

Currently patterns only works by masking out things to ignore, I don't have a way to highlight things to focus on (offhand, I suppose I could call it "focus"), but I suspect I'd need to offer it on a per file patterns, otherwise it is unlikely to work well for projects with more than one type of file. I really worry that doing this would require people to write quite a bit of code -- effectively reinventing parsing for a large number of languages, which seems quite painful.

## only considering specific files which are somehow marked for spellchecking

To limit which files should be checked, you can use `.github/actions/spelling/only.txt`, you could do something like:
```
\.md$
\.html$
/cmd/
^cli/main\.go$
```

This would get any file in a `cmd` directory, the file named exactly `cli/main.go`, and all Markdown and html files. You would add additional lines for additional kinds of files.

## making the tool more developer friendly

I can offer a PR to enable the experimental feature so that it's easier for people to update the expect file (instead of running code locally) as I previewed in my presentation. I just didn't want to do that initially...

**Comment by jsoref** [comment]
## more developer friendly part two
I was starting to write `.github/actions/spelling/advice.txt`:
```
<!-- markdownlint-disable MD033 MD041 -->
<details><summary>Need help understanding this</summary>

## Information on how to

* [exclude files/paths/types](https://github.com/check-spelling/check-spelling/wiki/Configuration-Examples:-excludes)
* [mask patterns](https://github.com/check-spelling/check-spelling/wiki/Configuration-Examples:-patterns)
* [supplement the dictionary](https://github.com/check-spelling/check-spelling/wiki/Feature:-Allow)

Ask @jsoref for help (available on Slack as well)
</details>
```

but, i'm not sure if that's something you'd want.

 (The @ reference to me is totally optional,) I'm happy to actually make code suggestions to live PRs to help people through, but so far it didn't look like people wanted that.

**Comment by warber** [comment]
After some discussions with the team, here's what would be the most wanted solution:
We want to keep the spell-checking functionality active - also for source code as it provides valuable benefits.
However, we want to change the way the spellchecking action is triggered.

Specifically, the current workflow of the spellcheck action shall be changed to the following:

- Spellcheck GH action is automatically *triggered every x days*. (default: x=20)
- When triggered, the current **master** branch shall be scanned for misspellings
- If spellcheck finds new misspellings, a **new issue** will be automatically created containing al found misspellings

From here on one team member will take care of resolving the misspellings mentioned in the created issue.

@jsoref do you see any technical problems when implementing with this workflow? and - can you eventually help to implement it? :-)

**Comment by jsoref** [comment]
Hmm, not technically impossible, it'd definitely require a small portion of new code, since there isn't currently any provision for filing a bug -- the simplest thing is a flag which enables the `schedule` feature to run against a single branch and write a comment (the branch being `master`), getting the bot to file a bug instead of just commenting on the commit wouldn't be a big step past that.

I suspect you'll want it to make available its details (where it found things) instead of just what it found. That's stuff it's starting to retain (in 0.0.18 which doesn't exist yet).

Not this week, but I can look in April...

It's much easier for me to offer a prerelease of talking to the bot (since that's ready for people to try today, the UX shouldn't change between now and when I release it, although I'm looking into changing how it works internally to handle private repositories...).
