### ISSUE TITLE
Show waiting status of successive sequence executions

### ISSUE THREAD

**Issue by warber** [keptn/keptn#3777]
## User Story
As a user, I want to be able to see whether a sequence execution is postponed in a given stage

**Details**: It can be the case that *the same sequence* is triggered repeatedly by the user. However, it is not allowed for a sequence to be executed more than once for any stage, i.e., only one instance/execution of a sequences can be in `active` state for a given stage. The others are in `waiting` state, waiting for the `active` one to finish in its current stage.

The User shall be able to see that a sequence is in `waiting` state as depicted in the following image:
![image](https://user-images.githubusercontent.com/72415058/114713404-60ec7680-9d31-11eb-8375-674fa7911997.png)

:warning: As part of this story, the sequence screen shall use the new `controlPlane/v1/state` endpoint (#3796) in order to fetch information of all sequences.

## Acceptance Criteria
* [ ] User can see that a stage is waiting for other sequence(s) to be finished
* [ ] User can filter sequences with having the exeuction state: `waiting`

## Definition of Done
* [ ] Feature implemented in Bridge
* [ ] Manual Test

## Dependencies
#3776
#3796

**Comment by Kirdock** [comment]
At the moment there are some additional dependencies
- #4433 additional parameter `shkeptncontext`. This is needed because of deep-links in the sequence screen. There may be sequences that aren't in the list because of the `pageSize`. The old behavior is that we load this sequence and then the sequences between.
- #4206 additional parameter `problemTitle`. This is needed because we show the problem title in the sequence view. 
![image](https://user-images.githubusercontent.com/11599148/122954030-62649b80-d37f-11eb-872b-535e29c80f47.png)

The environment screen also needs to be adjusted because at the moment the sequence screen and the environment screen share the same sequence data. Nevertheless we need to change the environment screen to fetch it's own data.

We have three options now.
## Option 1
For now we still use the old endpoint and adjust the environment screen to fetch it's own data.
Contra:
- This is still incomplete because if we fetch 20 root events there could still be some services without any and this wouldn't reflect the current status.

## Option 2
A new endpoint because the result should be one sequence for each service in a stage, which is completely different than the sequence endpoint.

## Option 3
We use the sequence endpoint. Then we need additional information:

- approval traces. It is possible to accept decline approvals. Should they just be fetched if they are needed? Additional information needed would be `data.labels` and `data.message` of the approval trace because this information is passed on to the next tasks in the sequence.
![image](https://user-images.githubusercontent.com/11599148/122954432-b8394380-d37f-11eb-87f9-5f764d093c7d.png).
- evaluation traces. Currently we have an overlay for all evaluations which shows the whole evaluation result. Either we disable the overlay or we fetch this information.
![image](https://user-images.githubusercontent.com/11599148/122953623-1ade0f80-d37f-11eb-86f5-49d717cf236d.png)
- remediations. The screen shows which remediation is currently running and also which actions have been executed. So additional information would be `problemTitle` or `ImpactedEntity`? and `actions[]`
- deploymentUri. At the moment `deploymentUri` is taken from the latest deployment trace if there is any. My suggestion would be to add it to the service in the `GET /project` endpoint.

Contra:
- The endpoint has to be adjusted because we need a sequence for each service in each stage. Else this would also result in one additional parameter for the service name and then there would be too much api-calls.
