### ISSUE TITLE
CI workflow tweaks cause multiple CI runs when opening a Pull Request

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#3826]
This is a follow-up of https://github.com/keptn/keptn/pull/3752 - pinging @jsoref  on this as well.

I noticed that CI runs are sometimes duplicated, e.g., when opening a PR:
![image](https://user-images.githubusercontent.com/56065213/115386691-0001ea00-a1da-11eb-976b-1f80270751fe.png)

![image](https://user-images.githubusercontent.com/56065213/115386757-1c058b80-a1da-11eb-86fc-c49b9bd26e39.png)

I'm pretty sure it has to do with the following line:
https://github.com/keptn/keptn/blob/dde0b7171afc3c34edb165761055627a097d84f6/.github/workflows/CI.yml#L13

Any opinions in how to fix this?
Maybe we don't need `synchronize` or `opened`?

**Comment by jsoref** [comment]
`synchronize` is what tells the system that `HEAD` on the incoming branch has changed (whether via a `push` or `push -f`), so you almost certainly do not want to drop that.

Without `opened`, I think you'd miss the first instance for a PR, so dropping this doesn't _seem_ like the right choice.

The organization does offer a list of [all events it has sent](https://api.github.com/users/keptn/events) / you could have your workflow dump the GITHUB_EVENT content. So you could try to compare the two instances to determine how they differ.

The GitHub docs can be incredibly frustrating. You might be best served by filing a ticket and getting GitHub support to tell you how to do what you want / why what we're doing here isn't the right thing (I know, that's cheating, but if you can't figure out how to do based on the docs, then it's reasonable to blame them for it, and they should bare the effort until the docs improve). 

https://docs.github.com/en/developers/webhooks-and-events/github-event-types

Other than things that specifically respond to label/unlabeled, this is the first time I've encountered something responding to this pair of events, so I don't really know much about it.

The laziest solution would be to just remove the line entirely, since that's equivalent to before the line was "corrected" to try to reflect the intention of its original author.

**Comment by christian-kreuzberger-dtx** [comment]
> The GitHub docs can be incredibly frustrating

Agreed.

> The laziest solution would be to just remove the line entirely, since that's equivalent to before the line was "corrected" to try to reflect the intention of its original author.

I can see that this might be the best solution to try out right now.

**Comment by christian-kreuzberger-dtx** [comment]
Using
```
 types: [opened, synchronize, reopened, labeled, unlabeled] 
```

this is the behavior:

**Creating a PR without a label**: One run
**Creating a PR with a label**: Two runs

![image](https://user-images.githubusercontent.com/56065213/115507654-aef70200-a27c-11eb-9568-a899d3cab508.png)


Removing `types: ...` completely, just using
```
on:
  pull_request:
    branches: [ main ]
```

obviously fails to detect any changes in labels of the PR, but results in only a single run.

Using
```
 types: [opened, synchronize, reopened, labeled, unlabeled] 
```
results in no run being triggered at all (unless I label the PR).

**Comment by christian-kreuzberger-dtx** [comment]
After reading up on the types a bit, the behaviour is expected.

My recommendation is to not use `types` at all, and just use `on: pull_request`.

**Comment by jsoref** [comment]
> Using

I suspect this isn't what you used:
 
> ```
>  types: [opened, synchronize, reopened, labeled, unlabeled] 
> ```
> 
> results in no run being triggered at all (unless I label the PR).

But yes, I believe you've reached the right conclusion.

If a PR that's created with a label is treated as sequentially:
1. create pr
2. add label to existing pr

then it's probably near impossible to do what you want (short of having a duplicate canceller task -- I've seen one of those recently, although I couldn't actually prove to myself that it worked).
