### ISSUE TITLE
Customization of Keptn Bridge

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#3886]
## User Story
As a user, I want to run a branded Keptn Bridge with a different color theme, fonts, and logos compared to the default implementation.

### Details

This is a research task:
- To identify the UI components that can be customized,
- To propose a concept of how to centralize the customization. 
- Are there blockers that make it difficult to change things?

## Definition of Done
* [x] A list of all elements (logo, images, CSS files, etc.) that can be changed (This should define the interface for changing the look and feel of the Bridge)
* [x] A proposal on how to centralize the customization

**Comment by ermin-muratovic** [comment]
**The elements that should be customizeable:**

- Logo in Header
https://github.com/keptn/keptn/blob/65b22d6bb75625c2b332e601ff853c8bfd98ae7c/bridge/client/app/app-header/app-header.component.html#L4
- Logo in Favicon
https://github.com/keptn/keptn/blob/069dd0f5c7b6f37a3737f4c0c9c7cf07a801b039/bridge/client/index.html#L18
- A logo is also used on several other pages, mainly in an error case (e.g. no project available, showing instruction how to setup a project)
https://github.com/keptn/keptn/blob/081f478e9f88df88aaef8ceec0f3e50c7fe56997/bridge/client/app/project-board/project-board.component.html#L5
https://github.com/keptn/keptn/blob/069dd0f5c7b6f37a3737f4c0c9c7cf07a801b039/bridge/client/app/dashboard/dashboard.component.html#L11
https://github.com/keptn/keptn/blob/8e7609afdbe0d23271fdca8a6e0f3d6e3c9f4a93/bridge/client/app/evaluation-board/evaluation-board.component.html#L39
- Title in Browser Tab and Header
https://github.com/keptn/keptn/blob/069dd0f5c7b6f37a3737f4c0c9c7cf07a801b039/bridge/client/index.html#L5
https://github.com/keptn/keptn/blob/28c9401923f1dd482a5d1827181745a5923b3529/bridge/client/app/app-header/app-header.component.html#L5
- The name "Keptn" is also used on several places as label or part of a message. Each label and message should be customizable.
https://github.com/keptn/keptn/blob/069dd0f5c7b6f37a3737f4c0c9c7cf07a801b039/bridge/client/app/_views/ktb-integration-view/ktb-integration-view.component.html#L2
https://github.com/keptn/keptn/blob/069dd0f5c7b6f37a3737f4c0c9c7cf07a801b039/bridge/client/app/_views/ktb-integration-view/ktb-integration-view.component.html#L3
https://github.com/keptn/keptn/blob/069dd0f5c7b6f37a3737f4c0c9c7cf07a801b039/bridge/client/app/_views/ktb-integration-view/ktb-integration-view.component.html#L5
https://github.com/keptn/keptn/blob/069dd0f5c7b6f37a3737f4c0c9c7cf07a801b039/bridge/client/app/_views/ktb-integration-view/ktb-integration-view.component.html#L6
https://github.com/keptn/keptn/blob/069dd0f5c7b6f37a3737f4c0c9c7cf07a801b039/bridge/client/app/_views/ktb-integration-view/ktb-integration-view.component.html#L21
https://github.com/keptn/keptn/blob/069dd0f5c7b6f37a3737f4c0c9c7cf07a801b039/bridge/client/app/_views/ktb-integration-view/ktb-integration-view.component.html#L25
https://github.com/keptn/keptn/blob/0e13840285ac70343dab2ccfd24bc90c778fed4d/bridge/client/app/_views/ktb-service-view/ktb-service-view.component.html#L25
https://github.com/keptn/keptn/blob/0e13840285ac70343dab2ccfd24bc90c778fed4d/bridge/client/app/_views/ktb-service-view/ktb-service-view.component.html#L43
https://github.com/keptn/keptn/blob/081f478e9f88df88aaef8ceec0f3e50c7fe56997/bridge/client/app/project-board/project-board.component.html#L10
https://github.com/keptn/keptn/blob/081f478e9f88df88aaef8ceec0f3e50c7fe56997/bridge/client/app/project-board/project-board.component.html#L15
https://github.com/keptn/keptn/blob/081f478e9f88df88aaef8ceec0f3e50c7fe56997/bridge/client/app/project-board/project-board.component.html#L20
https://github.com/keptn/keptn/blob/069dd0f5c7b6f37a3737f4c0c9c7cf07a801b039/bridge/client/app/dashboard/dashboard.component.html#L14
https://github.com/keptn/keptn/blob/8e7609afdbe0d23271fdca8a6e0f3d6e3c9f4a93/bridge/client/app/evaluation-board/evaluation-board.component.html#L44
https://github.com/keptn/keptn/blob/8e7609afdbe0d23271fdca8a6e0f3d6e3c9f4a93/bridge/client/app/evaluation-board/evaluation-board.component.html#L48
https://github.com/keptn/keptn/blob/3a41d62e4eafe44fffab2a4b63ceaed63f00296d/bridge/client/app/_components/ktb-stage-details/ktb-stage-details.component.html#L29
https://github.com/keptn/keptn/blob/3a41d62e4eafe44fffab2a4b63ceaed63f00296d/bridge/client/app/_components/ktb-stage-details/ktb-stage-details.component.html#L53
https://github.com/keptn/keptn/blob/3a41d62e4eafe44fffab2a4b63ceaed63f00296d/bridge/client/app/_components/ktb-stage-details/ktb-stage-details.component.html#L54
https://github.com/keptn/keptn/blob/081f478e9f88df88aaef8ceec0f3e50c7fe56997/bridge/client/app/_components/ktb-project-tile/ktb-project-tile.component.html#L8
https://github.com/keptn/keptn/blob/081f478e9f88df88aaef8ceec0f3e50c7fe56997/bridge/client/app/_views/ktb-settings-view/ktb-settings-view.component.html#L4-L6
- Colors and fonts
  - Header background and font style
https://github.com/keptn/keptn/blob/65b22d6bb75625c2b332e601ff853c8bfd98ae7c/bridge/client/app/app-header/app-header.component.html#L1
  - Menu background and font style
https://github.com/keptn/keptn/blob/65b22d6bb75625c2b332e601ff853c8bfd98ae7c/bridge/client/app/app-header/app-header.component.html#L23
  - Confirmation dialog background and font style
https://github.com/keptn/keptn/blob/65b22d6bb75625c2b332e601ff853c8bfd98ae7c/bridge/client/app/app-header/app-header.component.html#L73
  - Navigation background and font style
https://github.com/keptn/keptn/blob/65b22d6bb75625c2b332e601ff853c8bfd98ae7c/bridge/client/app/project-board/project-board.component.html#L34
  - Button colors and font style for primary and secondary buttons
https://github.com/keptn/keptn/blob/65b22d6bb75625c2b332e601ff853c8bfd98ae7c/bridge/client/app/app-header/app-header.component.html#L77
https://github.com/keptn/keptn/blob/65b22d6bb75625c2b332e601ff853c8bfd98ae7c/bridge/client/app/app-header/app-header.component.html#L78




**I would suggest** to have all customizable parts in one file, but since some customizations affect text, others styling and others affect assets, we will need to override several files for full customization. Still I would suggest to group it in three files:

- The environments file should contain all file references as URL (logo, text file, ...)
https://github.com/keptn/keptn/blob/65b22d6bb75625c2b332e601ff853c8bfd98ae7c/bridge/client/environments/environment.ts#L1-L3
- We should introduce a JSON translation file, which will contain all texts and labels that are used in the Bridge. This would allow to replace the texts and also would allow us to translate in other languages
- We already have a SCSS file that contains and/or overrides several variables that are used for styling and all available variables should be documented and listed in this file and used correctly across the Bridge
https://github.com/keptn/keptn/blob/65b22d6bb75625c2b332e601ff853c8bfd98ae7c/bridge/client/_variables.scss#L1-L8



And lastly, we should allow to add and replace assets in the Bridge. This could be implemented in the node app, by providing a URL to assets (could be a zip archive), that is downloaded and extracted on startup into the https://github.com/keptn/keptn/tree/master/bridge/client/assets directory. We already have some parameters that are interpreted by the node app and this functionality could be added there:
https://github.com/keptn/keptn/blob/65b22d6bb75625c2b332e601ff853c8bfd98ae7c/bridge/server/app.js#L9-L48
