### ISSUE TITLE
Introduce uitestid-s in Bridge

### ISSUE THREAD

**Issue by ermin-muratovic** [keptn/keptn#4038]
## User Story
As a user
I want to be able to select elements in Bridge by using specified `uitestid`'s for UI tests.

### Details

Introduce `uitestid`-s on all main elements in Bridge to allow easier selection for automated UI tests.
![image (13)](https://user-images.githubusercontent.com/6098219/117811821-530f1000-b261-11eb-916a-9efee4c73776.png)

* Part of this issue should also be to identify all key elements in Bridge, which should have an uitestid.

Example:
![image (12)](https://user-images.githubusercontent.com/6098219/117812069-9e292300-b261-11eb-93e3-21e7dccaca80.png)

### Acceptance Criteria
In the Bridge
the key elements should have an `uitestid` attribute, that describes that element and allows to select that element.

## Definition of Done
- [ ] elements in Bridge have `uitestid` attribute and (manually) tested

**Comment by christian-kreuzberger-dtx** [comment]
This is the advise I got:

* use `uitestid` on containers/components, rather than on spans, a, ...
* For "iterative" things (like printing a list of something) it is okay to re-use the same `uitestid`
* Make sure `uitestid` is set on things that are meant to stay for a long time (e.g., don't put `uitestid` on low-level elements such as a button, unless this is a button that will stay there forever)
