### ISSUE TITLE
Show instructions or link for triggering evaluations in stage

### ISSUE THREAD

**Issue by laneli** [keptn/keptn#4055]
When clicking on a service and stage without any evaluation the panel below the timeline is empty.
There should be a hint here, that evaluations results will be shown here and how to trigger an evaluation.

![image](https://user-images.githubusercontent.com/2674029/117940395-4fcf5f00-b309-11eb-96a7-9cd3e8def781.png)

**Comment by johannes-b** [comment]
Very good idea @laneli!

However, we don`t need to inform the user about triggering a sequence, because this is already available: 

![image](https://user-images.githubusercontent.com/729071/120188900-f88d2200-c216-11eb-90f4-1e14066e3ffd.png)

Nevertheless, we need to tell the user that an `evaluation` task was not part of the sequence: 

![image](https://user-images.githubusercontent.com/729071/120188790-d85d6300-c216-11eb-8281-d960658c44ae.png)
