### ISSUE TITLE
Response time degradation in configuration-service when using a Git Upstream (e.g., GitHub)

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#4066]
Using Keptn 0.8.2.
After a quick and dirty load-test (`while true; do keptn trigger evaluation --project=sockshop --stage=staging --service=carts  --timeframe=5m; sleep 5; done`) with Dynatrace monitoring active, I noticed that configuration-service performs poorly under sustained load:

![image](https://user-images.githubusercontent.com/56065213/117996539-85dd0500-b342-11eb-9e64-91fc790494c9.png)

Looking at the files that were fetched and why they cause issues, it is quite clear that it is caused by the git upstream to github.com.
![image](https://user-images.githubusercontent.com/56065213/117996649-9c835c00-b342-11eb-8f3e-cb3c1fc42302.png)

Looking at the call hierarchy, it seems that we end up spending some time in the `LockProject` function:
![image](https://user-images.githubusercontent.com/56065213/117996811-c2106580-b342-11eb-97b9-3cf1dba0e3c9.png)

**Comment by johannes-b** [comment]
Please take a look at this Slack message for additional details: https://keptn.slack.com/archives/CNRCGFU3U/p1631570522120000

**Comment by agrimmer** [comment]
This response time degradation could be fixed by the following proposal. Therefore, let's assume if you trigger a Keptn sequence
* first, the Git commit is fixed (e.g. HEAD) and will be e.g. part of the event data, and
* second, the files of this Git commit are then used throughout the complete sequence execution.

*Advantages of this proposal:*
* The user would know what resources (Helm chart, jmeter tests, etc.) and which versions have been used for a sequence execution.
* We would be able to cache (i.e. checkout) the Git commit in the container and deliver the files without any access to an upstream or without pulling for latest changes.

*Services blocking this approach:*
* The helm-service and the dynatrace-service are the only services which write to the Git repository during a sequence execution. We need to re-evaluate if those features are still needed. I personally doubt it.

**Comment by thisthat** [comment]
I run `while true; do keptn trigger evaluation --project=sockshop --stage=staging --service=carts --timeframe=5m; sleep 5; done` with the `resource-service` enabled. I let the "load-test" run for 30min and the slowest API call was 2s.

![image](https://user-images.githubusercontent.com/992621/170939803-fbdb1b07-611f-4e87-b56d-b7ccd5e6c997.png)

**Comment by thisthat** [comment]
With the resource-service enabled by default, we can close this ticket
