### ISSUE TITLE
Add problem title of remediation to sequence endpoint

### ISSUE THREAD

**Issue by Kirdock** [keptn/keptn#4206]
The sequence endpoint should also return the problem title of remediations in order to reduce the amount of api-calls in the bridge. 

Currently the open remediations in the service screen of the bridge need additional information and therefore there is another api-call to receive the `ProblemTitle` (e.g. "Failure rate increase") of it.
![image](https://user-images.githubusercontent.com/11599148/120198081-072d0680-c222-11eb-9e75-42e0abeefcba.png)

The sequence screen will also need this kind of information when the endpoint is changed to the new one.
![image](https://user-images.githubusercontent.com/11599148/120197871-cb923c80-c221-11eb-886e-7d6f412b4437.png)

New model:
```json
{
  "nextPageKey": 0,
  "pageSize": 0,
  "state": "...",
  "stages": [...],
  "problemTitle": "",
  "totalCount": 0
}
```

## Acceptance Criteria
- [x] The sequence endpoint returns the problem title of the remediation
- [x] State Sequence migration logic is adapted 

## Definition of done
 - [ ] Integration tests are updated

**Comment by johannes-b** [comment]
I did some investigation around this topic by executing the [Quickstart](https://keptn.sh/docs/quickstart/), which contains a remediation scenario. My findings are summarized below.

Before, I would like to show the `remediation.triggered` event, which kicks off the remediation scenario: 

```
{
   "type":"sh.keptn.event.production.remediation.triggered",
   "specversion":"1.0",
   "source":"https:\/\/github.com\/keptn\/keptn\/prometheus-service",
   "id":"f2b878d3-03c0-4e8f-bc3f-454bc1b3d79d",
   "time":"2019-06-07T07:02:15.64489Z",
   "contenttype":"application\/json",
   "data":{
      "project":"podtatohead",
      "stage":"production",
      "service":"helloservice",
      "problem":{
         "problemTitle":"out_of_memory",
         "rootCause":"Response time degradation"
      }
   }
}
``` 

### Environment screen shows running remediation, but missing details:

![image](https://user-images.githubusercontent.com/729071/141940833-ef7b2bd5-2b76-4691-b3da-e5694df2f829.png)

* Which data field is used by this label? 

### Service screen does not show the remediation sequence: 

![image](https://user-images.githubusercontent.com/729071/141940987-42919e9b-1588-4dc3-9239-eee6471f81e7.png)

While the above screenshot displays a running remediation sequence on the service (carts), in Keptn 0.10 this is not visible. Besides, the red icon is missing.

![image](https://user-images.githubusercontent.com/729071/141941113-3f4bf8a5-ae50-4a91-8d07-85e58919b827.png)

### Sequence screen does not display Problem Title (Root cause) 

![image](https://user-images.githubusercontent.com/729071/141941426-30815bde-6c33-4c5b-a8ac-21778a140003.png)


### Event contains the ActionIndex at the wrong place:

![image](https://user-images.githubusercontent.com/729071/141942372-46243ea3-6b64-48e7-ab4e-0e95df62f886.png)


Current event: 

```
{
  "data": {
    "ActionIndex": 1,
    "action": {
      "action": "restart",
      "description": "Restart Pod",
      "name": "restart"
    },
    "message": "",
    "problem": {
      "problemTitle": "out_of_memory",
      "rootCause": "Response time degradation"
    },
    "project": "podtatohead",
    "result": "pass",
    "service": "helloservice",
    "stage": "production",
    "status": "succeeded"
  },
  "id": "ea866eec-d31d-4f27-919a-28413f44a898",
  "source": "shipyard-controller",
  "specversion": "1.0",
  "time": "2021-11-16T07:37:19.117Z",
  "type": "sh.keptn.event.action.triggered",
  "shkeptncontext": "e5ffa518-25c1-44fd-a9f9-3d09eedd6b0f",
  "shkeptnspecversion": "0.2.3"
}
```

The proposed change to (see `get-action`): 

```
{
  "data": {
    "get-action": {
       "actionIndex": 1
    },
    "action": {
      "action": "restart",
      "description": "Restart Pod",
      "name": "restart"
    },
    "message": "",
    "problem": {
      "problemTitle": "out_of_memory",
      "rootCause": "Response time degradation"
    },
    "project": "podtatohead",
    "result": "pass",
    "service": "helloservice",
    "stage": "production",
    "status": "succeeded"
  },
  "id": "ea866eec-d31d-4f27-919a-28413f44a898",
  "source": "shipyard-controller",
  "specversion": "1.0",
  "time": "2021-11-16T07:37:19.117Z",
  "type": "sh.keptn.event.action.triggered",
  "shkeptncontext": "e5ffa518-25c1-44fd-a9f9-3d09eedd6b0f",
  "shkeptnspecversion": "0.2.3"
}
```

---

Can we use this issue to revamp how a remediation sequence is displayed in the Bridge?
