### ISSUE TITLE
keptn CLI command keptn generate support-archive  not working on windows

### ISSUE THREAD

**Issue by diegorqc** [keptn/keptn#4225]
**Environment**
When using windows (powershell with Keptn CLI 0.8.3 and keptn version matching). Tested with keptn running on 2 different environments (Microk8s and on AKS cluster)

**Affected Component**

* [ ] Docs
* [ ] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [ ] Bridge
* [ ] Approval
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**
when running Keptn CLI command keptn generate support-archive nothing is output and the CLI doesn't show any error. When running the same command over a linux console, the files are generated correctly (example using git bash on windows)
```
keptn generate support-archive --dir=./localdir
Retrieving kubectl version
Checking whether kube context points to Keptn cluster
Please confirm that this is the cluster Keptn is running on:
Cluster: microk8s
Is this all correct? (y/n)y
```

**To Reproduce**
Run `keptn generate support-archive` on a windows machine using powershell. No output generated

**Expected behavior**
The zip file with the logs is generated

**Comment by johannes-b** [comment]
I tested the command on my Windows box too and experience the same problem. 

According to the implementation (https://github.com/keptn/keptn/blob/master/cli/cmd/generate_support_archive.go#L134), the command should print: `Retrieving logs from cluster` after the question: `Is this all correct? (y/n)y`

Could it be fixed by changing: 
`userConfirmation := common.NewUserInput().AskBool("Is this all correct?", &common.UserInputOptions{AssumeYes: false})`
to 
`userConfirmation := common.NewUserInput().AskBool("Is this all correct?", &common.UserInputOptions{AssumeYes: assumeYes})` (as used at other places in the code.)

**Comment by johannes-b** [comment]
This issue may be related to another bug too: https://github.com/keptn/keptn/issues/3959

**Comment by johannes-b** [comment]
The problem on windows is documented here: https://groups.google.com/g/golang-nuts/c/hWoESdeZ398?pli=1

**Comment by DarthBenro008** [comment]
Hey @johannes-b , I would like to work and further investigate on this issue!

**Comment by johannes-b** [comment]
@DarthBenro008 this would be really great! The bug might be in the function: `common.UserInputOptions` since it is a glitch with \r and \n on Windows as pointed out by the above link.

**Comment by DarthBenro008** [comment]
@johannes-b , Apparently the issue was that PowerShell was adding some spaces in the input ( pretty weird 🤔 ) I did some testing with `strings.Compare()` apparently it was throwing `1` instead of `0` indicating the strings "y" and the given input are not same. 

Hence I just applied a `TrimSpace()` which removed any redundant spaces and made the comparison easier 😃 . Opened a PR for same with working results screenshots attached

**Comment by DarthBenro008** [comment]
@johannes-b I think writing a unit test should be as simple as adding the following snippet in https://github.com/keptn/keptn/blob/master/cli/pkg/common/userinput_test.go

```go
	t.Run("test Y with spaces", func(t *testing.T) {
		input := UserInput{
			Writer: ioutil.Discard,
			Reader: bufio.NewReader(bytes.NewBufferString("Y  \n")),
		}
		answer := input.AskBool("Are you sure?", &opts)
		assert.True(t, answer)
	})
```
Should I go ahead and add it?

**Comment by johannes-b** [comment]
@DarthBenro008 please add this test!

**Comment by DarthBenro008** [comment]
@johannes-b I have added the test 😃
