### ISSUE TITLE
Allow to start integration tests directly from a PR

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#4322]
User Story: As a Keptn core maintainer/developer I want to be able to start integration tests directly from a Pull Request, e.g., by adding a label to the PR (e.g., `CI:integration_tests_triggered`).

# Definition of Done

- [ ] In addition to the current workflow_dispatch setup for integration tests, integration tests can be triggered by adding a label to a PR
- [ ] When tests have started, another label needs to be added (e.g., `CI:integration_tests_started`)
- [ ] When tests have finished, another label needs to be added (e.g., `CI:integration_tests_finished`)
- [ ] When tests have finished, a report of the tests (similar to our "Integration tests failed comment") is shown on the PR

**Comment by mowies** [comment]
I did some research on this topic and found that there is currently no nice way of achieving this ticket without significant effort.

I checked the setup that [dynatrace/monitoring-as-code](https://github.com/dynatrace-oss/dynatrace-monitoring-as-code) uses (developed by @didiladi) but after a short discussion with him, we agreed that it would not be the right fit for several reasons:
- Monaco will actually get rid of the setup in the near future because it didn't work well enough in the end for them.
- For Keptn, the setup wouldn't scale well, since it would run a pipeline every 5 minutes to dispatch other pipelines. We are already limited in concurrent jobs on GH actions and cannot afford more runs. The result would probably be that the dispatcher pipeline would actually be queued for long times after triggering other pipelines. Which would make the whole automation behind it relatively useless in that case.
- Other options such as triggering the integration tests directly with the `pull_request.labeled` event also don't work since it would immediately have concurrency issues when you want to run integration tests from the same PR multiple times (e.g. for different commits).

I will close this issue for the above reasons.
