### ISSUE TITLE
Service evaluation screen gets refreshed every time after polling data

### ISSUE THREAD

**Issue by laneli** [keptn/keptn#4491]
When selecting a service and examining the evaluations - after each poll, the data is fetched and the whole view is reloaded.
Symptoms:
* The view is cleared
* The loading indicator shows again after each poll
* There is a re-route to the last stage of the service (so when I examined staging I suddenly am back to production again)

Affected component:
ktb-service-details

In the component the deployment seems to get re-set, the stage re-selected and therefore the weird behavior happens.

**Comment by grabnerandi** [comment]
Hi. Just wanted to add that this problem is impacting end users to really using the keptn bridge due to the constant redrawing and therefore loosing scroll position. I am working with a handful of users and several have reported that this behavior makes it rather hard to anlayze and discuss the heatmap as it constantly refreshes
Great to see this was already fixed. hope it soon makes it into an upcoming release
