### ISSUE TITLE
Bridge: Adding / Deleting / Updating subscription

### ISSUE THREAD

**Issue by warber** [keptn/keptn#4572]
### Add subscription

When clicking on the "Add subscription" button the user is presented with a UI component like below to create an additional subscription for the Keptn integration:

* Click `Add subscription`

* Enter name/task/filters:

![image](https://user-images.githubusercontent.com/729071/125420111-45965949-2b4e-400e-8cf8-0159d926db08.png)

* When clicking the **Save** button; The subscription data is updated via the Keptn Uniform API (see #4437)

* A **Delete** button is now available:

![image](https://user-images.githubusercontent.com/729071/125420740-a4e92f0a-5ccc-4208-9734-f6996005fd21.png)

### Deleting subscriptions

* Click on an already created subscription

* Click the **Delete** button: The subscription data is updated via the Keptn Uniform API (see #4437) 

* Result: the list of subscriptions does not show the deleted subscription

### Updating subscription

* Click on an already created subscription

* Change the settings

* Click the **Save** button

#### Implementation Notes

* The Bridge server should fetch this information from an API everytime. This is to avoid sync problems with changes in the Shipyard file. 
* In the uniform screen, subscription events are filtered by `project` and then `stage`, they are represented as an array but they must contain only a single element.
* The list of possible events for which a service can subscribe to is the list of [Keptn Cloudevents](https://github.com/keptn/keptn/issues/4572)

## Acceptance Criteria

* [x] User is able to add/delete/update a subscription for an integration

## Definition of Done
* [x] Story is implemented in th Bridge
* [x] Unit/UI Tests
* [ ] Documentation is updated

### Dependencies
- [x] #4437

**Comment by johannes-b** [comment]
Design question: Do we need a separate view for creating/updating/deleting one subscription or can it be handled in the table?

**Comment by johannes-b** [comment]
I would now prefer going with a separate view, in order to allow implementing this: https://github.com/keptn/enhancement-proposals/pull/54 for the webhook-service

**Comment by Kirdock** [comment]
Note: If we go with a separate view, we also need to introduce new deep links (not only for the 'create/edit'-view). In order to navigate back after editing/creating a subscription, we also need a deep link to navigate back to a specific integration.
`/uniform/services/{integrationId}`. This should be updated after selecting an integration. Maybe also `/uniform/services/{integrationId}/subscription` but at the moment we don't need it, because the subscription tile is always expanded.
We should also consider changing the route for `/uniform/services` to `/uniform/service` because we now have `/service` `/sequence` in singular but `/uniform/services` and `/uniform/secrets` in plural
