### ISSUE TITLE
Sequence endpoint: State for each stage

### ISSUE THREAD

**Issue by Kirdock** [keptn/keptn#4625]
Because of parallel stages, we may have several states (e.g. production-A is `waiting` and production-B is `failed`) and therefore the `state` property in the sequence state is not enough to determine the status. An additional `state` property in each stage is necessary.
In addition to this the bridge needs to adapt these changes and should show the state of each stage in the list of sequences.

# Definition of done
- [ ] The `/sequence` endpoint also returns the state of each stage
- [ ] The bridge is able to show this information in the list of sequences

**Comment by johannes-b** [comment]
![image](https://user-images.githubusercontent.com/729071/153884415-85486f8a-80ec-4f71-bdd5-a8161401e28a.png)

When there is a sequence execution for another sequence, no `warning note` is shown.

**Comment by ermin-muratovic** [comment]
@johannes-b thanks for your feedback. 

Currently the GET `/sequence` API endpoint would return the correct state, but we are still not using that property in the Bridge. We have a contribution open, see #6831 which adjusts the message and hopefully will also use the correct property to determine the waiting status.

It might be that in your case, because of the changes in #5526, our old implementation in the Bridge is now broken.
