### ISSUE TITLE
Misleading warning on Keptn CLI during keptn auth

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#4720]
This happens with keptn cli 0.8.6

When doing a Keptn auth the first output is a warning that keptn CLI is currently not authenticated. This is misleading and doesnt make sense when calling keptn auth as I am just about to authenticate

here a screenshot to show this warning
![image](https://user-images.githubusercontent.com/675886/126439932-97e0d21f-36e2-445c-a507-10cb42e060b0.png)

**Comment by nevosial** [comment]
Hello I would like to work on this .
Can you help me where to get started as I am a new contributor.

**Comment by warber** [comment]
@nevosial thx for your desire to contribute.

The CLI code base is part of this mono repo.
Just grab a fork of this repo and start working on this on your own branch.

You can find more information about this [here](https://github.com/keptn/keptn/blob/master/docs/fork.md)
You can use Visual Studio Code, Goland, or any other dev environment - It does not matter so much, especially as this is a CLI issue, hence it is rather easy to build and test it. Just compile it locally and issue commands to your keptn installation to try it out.

The relevant files to start taking a look for in order to fix this issue are [cli/cmd/auth.go](https://github.com/keptn/keptn/blob/master/cli/cmd/auth.go) as well as [cli/cmd/root.go](https://github.com/keptn/keptn/blob/master/cli/cmd/root.go). After a quick look, I would bet that the error message comes from [this](https://github.com/keptn/keptn/blob/ba815415f63f75f640b2d2ed3ca83100f0385555/cli/cmd/version.go#L177) line which originates from the root command where it tries to make a version check when a command is executed....

hope this helps

**Comment by madhavsikka** [comment]
Hi, can I take this up ?

**Comment by thisthat** [comment]
Hi, @madhavsikka! Thank you for your help, I'll assign this to you :D 
I believe this was fixed while doing some refactoring of the CLI. Please, verify if this problem still occurs :)

**Comment by madhavsikka** [comment]
Yeah, I don't see this issue now. Thanks
