### ISSUE TITLE
Redirect to dashboard if project is deleted

### ISSUE THREAD

**Issue by Kirdock** [keptn/keptn#4765]
When you are in the project-screen and the project is deleted (through the CLI or another tab), the bridge still shows the project-screen and still tries to poll the project even if it receives a 404 status code.

# Definition of Done
- [ ] The bridge redirects to the dashboard if the project endpoint returns 404

**Comment by laneli** [comment]
I reactivated the mechanism to show "Project doesn't exist" message again - subscription was missing.
Also instead of redirecting, I would propose to use the existing mechanism to also show this message when 404 is returned by the API.

![image](https://user-images.githubusercontent.com/2674029/128186132-c76827a5-5a12-478f-a709-592d7231fdf5.png)
