### ISSUE TITLE
Allow Keptn CLI to use a proxy for accessing the Keptn API

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#4786]
Some of our users can't access the Keptn API directly but have to go through a Proxy. If they want to use the Keptn CLI as their choice of automation tool they currently cant use it as the Keptn API doesnt allow to specify a proxy to be used.

One option would be to extend the keptn auth command with an optional proxy setting, e.g: proxy url, proxy user, proxy password

**Comment by warber** [comment]
Might be helpful: https://stackoverflow.com/questions/14661511/setting-up-proxy-for-http-client

**Comment by mpolonen** [comment]
It would be really great if this was solved. I think the problem is in cli/cmd/check_endpoint_status.go There is a custom transport object and no proxy setting so setting environment variable does not work. I think I cloud make it work with something like this (adding the proxy line).

var client = http.Client{
        Transport: &http.Transport{
                TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
                Proxy: http.ProxyFromEnvironment,
        },
}

**Comment by thisthat** [comment]
Hi @mpolonen, in https://github.com/keptn/keptn/issues/6343#issuecomment-1020998889 we updated the documentation to explain how to enable a proxy via env var. We offer two env var: `HTTP_PROXY` and `HTTPS_PROXY`.
