### ISSUE TITLE
Remove error-retry-mechanism of api calls

### ISSUE THREAD

**Issue by Kirdock** [keptn/keptn#4867]
At the moment there are 3 retries if an api call fails. For most of the cases this is not needed, like a 404 response for a fetching a project. Either remove the retry-mechanism completely or limit it to error responses with a status code of 500.

**Comment by carpe-github** [comment]
The issue described in this thread should be also verified once this issue is resolved:
https://dynatrace.slack.com/archives/GBZA8CM6H/p1628578732022700
A key proposal from this thread:
It would be better if we make the retry logic smarter, which means to not repeat the requests which are expected to not be succeeded on further retries, like in this case, where the response clearly says why the request was failed.
