### ISSUE TITLE
Question : Can I install keptn without Istio ? is Istio mandatory ?

### ISSUE THREAD

**Issue by jwalitptl** [keptn/keptn#4934]
Hello,

We are using Argo rollouts blue-green deployment without Istio. We are a big enterprise and it's hard and time-consuming to migrate to Istio. do we have the option to not use Istio with keptn and still continue using Argo rollouts.

Pls provide suggestions..

**Comment by johannes-b** [comment]
Hello @jwalitptl,

If you are using Argo Rollouts there is no need to install Istio, since your blue/green deployment is done via Argo and not by Istio. :) 

* In the repo https://github.com/keptn-contrib/argo-service, you can find an Argo service that is designed to work with Argo Rollouts. 
* Besides, we also provide a tutorial for this use-case: https://tutorials.keptn.sh/tutorials/keptn-argo-rollouts-dynatrace-08-on-k3s/index.html?index=..%2F..keptn08x#0

**Comment by jwalitptl** [comment]
@johannes-b   thanks much for quick reply
