### ISSUE TITLE
[doc] Automation for creating documentation for a new release and versioning of release docu

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#4980]
## User story

When releasing a new version of Keptn, the documentation is also released based on the same release tag. As a user, I can switch between the release versions, while the latest stable version is shown by default. 

*Future situation:* As we are going to change the versioning of releases by incrementing the Minor version (Major.Minor.Patch), the current documentation approach does not scale. We would have duplicate the docu for each new release. 

### Details

* Using tagging / branching to create release documentation in https://github.com/keptn/keptn.github.io
* On the page, I can switch between the release docu. For example, see istio.io: 
![image](https://user-images.githubusercontent.com/729071/130186885-b185163d-fb99-4ee1-b707-df6fd455b12e.png)
* When switching to an older release, the release version is reflected in the URL: https://istio.io/v1.9/ 
* Consequently, we should not show the documentation for previous releases, but rather the release docu the user has selected: 
![image](https://user-images.githubusercontent.com/729071/130187166-76a3fc25-d684-487d-b0dc-4637b456feb7.png)

### Advantage

* By applying this approach, it becomes obsolete to duplicate the docu for each release in: https://github.com/keptn/keptn.github.io/tree/master/content/docs

**Comment by jetzlstorfer** [comment]
Related to this I do have two more suggestions:

1. Include a search in the documentation https://github.com/keptn/keptn.github.io/issues/693 
2. Include a "Improve this page" or "Edit on Github" button on each page https://github.com/keptn/keptn.github.io/issues/859

**Comment by mowies** [comment]
I would suggest to look into a documentation specific website generator like [ReadTheDocs](https://readthedocs.org/) which has things like support for intelligent version switching and text search already included.
It should not be that hard to switch since ReadTheDocs is also based on Markdown files and our content wouldn't need to change much.

**Comment by StackScribe** [comment]
We need real reference pages for commands and files, with accompanying guides that contain introductory information about each entity.  These should not be part of release-specific source but should instead be written to cover all releases, with a "Differences between versions" on each page to chronicle changes to the interface over time.

**Comment by StackScribe** [comment]
We need a separate, comprehensive Architectural section rather than the current structure, which has an Architecture section under “Concepts”.  This has general diagrams for Keptn with links to other architectural materials included in other sections.  Need to investigate whether this is the best approach or whether we should have a separate “Architecture” section that consolidates all the architectural  information for all components and operations.  Include prose that discusses how various operations are actually implemented to supplement the drawings and, as appropriate, note differences between versions.

**Comment by StackScribe** [comment]
Should link of possibly embed appropriate videos in the documentation as appropriate.
