### ISSUE TITLE
Bridge: Show Keptn core services logs

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#5097]
## User Story

As a user, I would like to see error logs from the Keptn core services

## Implementation details

The uniform screen should provide a general `Keptn Core service` that aggregates the logs of all Keptn core services.

## DoD 

- [ ] Logs are visible in the Uniform screen
- [ ] UI Tests

**Comment by johannes-b** [comment]
Keptn Core services are: 
- api
- configuration-service
- mongodb-datastore
- secret-service
- shipyard-controller
- statistics-service

What about:
- bridge?

--- 
My opinion: 

* A generic `Keptn core service` should not be part of the table in the Uniform because the Uniform is mapped to a project and I would like to see the logs/errors on Keptn instance level. 

* Instead of investing in this generic `Keptn core service`, I would focus on improving the error messages that are returned. Hence, we could guide the user where the info is needed (and not link the user to a separate page)

**Comment by thisthat** [comment]
The team agreed to close this issue in favor of displaying more relevant error messages when an error occurs.
