### ISSUE TITLE
Just one running sequence is shown in environment screen

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#5148]
**Environment**

* Keptn Version (`keptn version`): 0.9.0

**Affected Component**

* [x] Bridge

**Describe the bug**

* Triggered two subsequence delivery sequences: 
  * `keptn trigger delivery --project=sockshop --service=carts --image=docker.io/keptnexamples/carts --tag=0.11.1` 
  * `keptn trigger delivery --project=sockshop --service=carts --image=docker.io/keptnexamples/carts --tag=0.11.3`

* They are correctly shown in the sequence screen: 
  * The first one is currently deploying in production
  * The second one is currently deploying in staging 
![image](https://user-images.githubusercontent.com/729071/131965284-2ce43e1c-685a-48c1-a616-3841eeb64d55.png)

* However, in the environment screen just the sequence in `production` is indicated as running:

![image](https://user-images.githubusercontent.com/729071/131965464-6ccb08dd-6b5c-4f03-a86f-dab3efad78d5.png)

* Besides, when clicking on the delivery sequence in `staging`, I get forwarded to the sequence that is already in `production`:
![image](https://user-images.githubusercontent.com/729071/131965340-b2cd6fda-e4ab-4158-ab9d-307213054edc.png)

**To Reproduce**

* Triggered two subsequence delivery sequences: 
  * `keptn trigger delivery --project=sockshop --service=carts --image=docker.io/keptnexamples/carts --tag=0.11.1` 
  * `keptn trigger delivery --project=sockshop --service=carts --image=docker.io/keptnexamples/carts --tag=0.11.3`

**Expected behavior**
* In the environment screen, all running sequences are shown and when clicking on the sequence, the user gets forwarded to the most recent sequence in this stage.

**Comment by Kirdock** [comment]
The problem here is probably the following:

1. Sequence A started.
2. Sequence A is running in staging. => Timestamp for the latest sequence in staging is updated
3. Sequence B started waits for sequence A to finish in staging. => Timestamp for the latest sequence in staging is updated
4. Sequence A finished in staging. => Timestamp for the latest sequence in staging is updated
5. Sequence B in staging is not updated to `started` or `finished` and therefore it is not the last/current one.

Then sequence A was the last sequence that was modified in that stage, not B.

**Comment by Kirdock** [comment]
Solution: instead of determining the latest sequence by the latest sequence timestamp, the latest sequence should be determined by the latest event.
