### ISSUE TITLE
Core: Research JetStream

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#5307]
## Action Item

Research and document in this ticket:
 - [x] How to switch to JetStream
 - [x] Should we change any configuration for its deployment?
 - [x] Is there any breaking change for other services?
 - [x] Compared to NATS, how more/fewer resources are needed?

**Comment by bacherfl** [comment]
## Reasearch findings:

In General, JetStream dstinguishes between Push-based and Pull based subscribers:

* When creating a push-based subscription, the subscriber will receive all events for a certain topic, including the ones that have happened in the past. The main use case for these kinds of subscribers is for logging/monitoring services that need to derive a state from all previous events, but do not have to execute any tasks or produce results.
* Pull based subscribers can be used for implementing an exactly-once message delivery system. These subscribers can subscribe to a certain topic by attaching themselves to a Consumer of a stream. A consumer can have a durable name, which means that it will only receive messages that have not been acknowledged by another subscriber attached to that consumer (i.e. at-most once). When a subscriber for a consumer recovers from a downtime, it will receive all unacknowledged messages that have been sent in the meantime since those will be persisted by Jetstream. In our case, a durable name would correspond to a combination of a service name and a topic this service is subscribed to. E.g.
`shipyard-controller-sh-keptn->` or `helm-service-sh-keptn-event-deployment-triggered`. Multiple instances of the same services would then attach themselves to the same consumer.

From an architectural point of view, some adaptations would need to be made, since in JetStream, the streams, as well as the consumers have to be managed. In order for the eventing to work, a stream containing all topics of the Keptn event domain needs to be set up. With our current event topic names, the stream would simply be called `sh` - the name of a stream must start with the common prefix that all topics share, and must not contain a `.` - therefore, `sh.keptn` can unfortunately not be used as a stream name - Simply calling it `sh` seems a bit hacky though.
Also, ideally the consumers would also be managed by a central component based on the available topics and integrations within the uniform.
Both the streams and consumers can in theory be also created as needed by the distributors, but this would likely lead to problems regarding race conditions and in general is not a clean solution.

**Comment by thisthat** [comment]
Thank you @bacherfl for your research! I will close the ticket since all points have been addressed.
