### ISSUE TITLE
Bridge: Sequence is red although no error is reported

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#5684]
**Environment**

* Client OS (e.g., Linux, macOS, Windows):
* Keptn Version (`keptn version`):
* Kubernetes Cloud Provider (e.g., GKE, AKS):
* Kubernetes version (`kubectl version`):

**Affected Component**

* [ ] Docs
* [ ] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [x] Bridge
* [ ] Approval
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**

A delivery sequence was correctly completed, but it is marked in red. Also, the deployment box has a red border.

**To Reproduce**

Configure a webhook subscription on `sh.keptn.event.deployment.finished`.  Insert a wrong variable for the webhook payload. Trigger a deployment sequence.

**Expected behavior**

The sequence should not be marked with an error state since an integration failed but it didn't stop the sequence to proceed.

**Screenshots**

![webhook_error_sequence](https://user-images.githubusercontent.com/992621/137128666-2f624989-1162-488a-81bf-7ed76f13577b.PNG)

**Comment by thisthat** [comment]
A possible solution is to use only task events to determine the result of a sequence. The list of available task for a given project can be fetched using `/bridge/api/project/{project}/tasks`

**Comment by laneli** [comment]
The fix now limits the determination of failed results. For that, it uses the list of tasks and sequences of the shipyard file.
e.g. `sh.keptn.event.dev.delivery.finished`, `sh.keptn.event.deployment.finished`

Limitations:
* The original bug occurred because of a nested `sh.keptn.event.deployment.finished.finished` event that was sent from the webhook-service. When this gets fixed, the event will fail the task / sequence again - but it will be then visible in the task list.
* `get-sli` will always succeed a sequence, even if the task failed. It is not defined in the shipyard.yaml file.
