### ISSUE TITLE
Core: Improve error message of webhook-service

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#5692]
## Action Item

The `webhook-service`  should provide a more descriptive message for when a variable cannot be parsed. 

Currently, the message is generic; e.g.:
```
could not parse request 'curl --header 'Content-type: application/json' --request POST --data '{"text":"Hello, World! {{.env.data.project}}"}' https://hooks.slack.com/services/yada_yada_yada'
```

It should report something like:
```
could not parse {{.env.data.project}} for 'curl --header 'Content-type: application/json' --request POST --data '{"text":"Hello, World! {{.env.data.project}}"}' https://hooks.slack.com/services/yada_yada_yada' 
```

## DoD
- [ ] Feature implemented
- [ ] Unit tests

**Comment by odubajDT** [comment]
I will take it, thanks.

**Comment by odubajDT** [comment]
From my POV, the problem with missing information in the error message is due to missing test on the required presence of requests[] in webhook struct (https://github.com/keptn/keptn/blob/master/webhook-service/lib/webhook_config.go#L21). Actually, the output actually contains this information (https://github.com/keptn/keptn/blob/master/webhook-service/handler/handler.go#L193) but if the array is empty, it cannot process it. Therefore the fix should be to validate the webhook-config (https://github.com/keptn/keptn/pull/6064/files#diff-d1c7c9f6ce3e909d74ce6038d94f363cf373b19579b2365dc1754491a86c33f7) so the invalid config will result in the error. With valid config, I was unable to reproduce the problem.
