### ISSUE TITLE
CI: Generate the draft changelog after merges to the main branch

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/keptn#6090]
**Is your feature request related to a problem? Please describe.**
As a Keptn user, I would like to see what changes are coming in the next release. The new releases are shipped monthly with hundreds of commits, so I cannot just take a look at the commit history

**Describe the solution you'd like**
It would be ideal to update GitHub Actions so that a changelog draft is generated for each actions run in the main branch. Currently the autogenerated changelogs are good for initial analysis, e.g. https://gist.github.com/oleg-nenashev/b1246c9dde4898a3d44d31542d3616bf#file-changelog-autogenerated-md for 0.11.0

The generated changelog could be just dumped to the build log or, ideally,  somehow published to the website or another resource as the upcoming changes preview

**Describe alternatives you've considered**

**Additional context**
To generate the changelog manually, run the `npx` tool from npm in the repository root

```
npx standard-version@^9.3.1 --release-as "0.11.0-preview" --skip.commit ----skip.tag --header "" -i RELEASE-BODY.md
```

**Comment by mowies** [comment]
Thanks @oleg-nenashev for this input!
I think it makes sense to implement something like a release preview, but I still have a few open questions:
- If the changelog is generated with every `master` branch pipeline run, that means that we have a looot of changelogs. So we would need to overwrite the old one every time, right?
- Where would you put that preview changelog then? Then repo is not an option for this. It would mean that the pipeline would commit to the repo for every pipeline run from `master`. Just leaving it in the build log is also no option since users who are not part of the Keptn GH organisation can't view the GH actions logs.

**Comment by mowies** [comment]
Hey @oleg-nenashev !
Is this still relevant? I noticed that users who are not members of keptn, are not able to see the pipeline logs anyways so I think the usefulness of this is very limited.
