### ISSUE TITLE
Allow `serviceAccount` specification through helm values

### ISSUE THREAD

**Issue by kristofre** [keptn/keptn#6095]
**Is your feature request related to a problem? Please describe.**
In certain environments, users are unable to create `serviceAccount` objects and they want to specify pre-created `serviceAccounts` to be used. Right now the only way to do this is to modify the helm templates, which brings challenges when upgrading.

**Describe the solution you'd like**
Being able to specify `serviceAccount` for all keptn services through helm values.

**Describe alternatives you've considered**
Modify the helm templates.

## Acceptance criteria

- [ ] Allow to specify pre-existing service-accounts for all SAs that keptn needs

## DoD

- [ ] Manual tests - with and without `helm install --reuse-values`

**Comment by mowies** [comment]
Hi @kristofre !
So we discussed this ticket in the team and came to the conclusion that we can only provide a "workaround" solution right now. We have some limitations in the `secret-service` with k8s RBAC objects, therefore we cannot provide an option to configure separate service accounts per Keptn service. What we could provide is an option to provide SAs as a replacement for the currently existing SAs that we use in Keptn.

Would that be a solution that works for you?

**Comment by mowies** [comment]
Coming back to this: It could actually be implemented in a slightly "dumb" way.
Instead of giving users the option to configure a separate SA per keptn service, we can give them the option to exactly configure the same SAs as we have in keptn already, including the `keptn-default` SA that's needed for secret-service to work properly.

2 options to make this work with `keptn-default`:
1. Let users provide the keptn-default SA but have a JSON schema for the helm values so that only the exact name `keptn-default` is allowed to keep secret service working the same way as before.
2. Let helm also adjust the `scopes.yaml` configmap for secret service to replace the scope `keptn-default` with whatever name the user provides in the helm values as a replacement for the `keptn-default` SA.
