### ISSUE TITLE
Core: Research how to Chaos test Keptn

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#6180]
## Action Item 

With [KEP48](https://github.com/keptn/enhancement-proposals/pull/48#), we are making Keptn high-available. The goal of this research is to investigate how we could perform chaos testing for our components in an automated fashion. 

Some suggestions:
- [x] https://netflix.github.io/chaosmonkey/
- [x] https://litmuschaos.io/

**Comment by christian-kreuzberger-dtx** [comment]
FYI, consider that we already have some experience with litmus-chaos in Keptn :)
See https://www.youtube.com/watch?v=Ac0DcT1SF3g and https://www.youtube.com/watch?v=aa5SzQmv4EQ

Especially considering Keptn-on-Keptn, this would allow to perform certain tests with Keptn directly.

**Comment by RealAnna** [comment]
**Research Outcomes:**

We coud run chaos tests on a dev cluster while load tests and end-to-end tests are running. We could have some random pod being killed or some change in networks and cpu resources, to see whether they are successful anyway. To judge our current implementation of graceful shutdown and liveness/readiness we could test scale up and down scenarios.

**First iteration on chaos framework requirements**
- We should select a solution that is well configurable and that in the future we may automatize even as a sequence on keptn on keptn. 
- The solution chosen should also have the possibility to experiment with pod lifecycle, networking, CPU and memory resources, container lifecycle, and also I/O. 
- To facilitate the initial usage the solution should include the possibility to schedule chaos workloads and to visualize what is the result of the experiment.

**Possible tools**

After discarding pod killing solutions such as:  jnewland/kubernetes-pod-chaos-monkey, 
https://github.com/asobti/kube-monkey and https://github.com/linki/chaoskube 

The two most promising options for us are: [Litmus ](https://github.com/litmuschaos/litmus) and [Chaos Mesh](https://chaos-mesh.org/) 
These are both CNCF sandbox projects and are based on Cloud Native concepts. They present out-of-the-box experiments for all categories mentioned in the requirement list. They both are based on K8s CDRs. 

**Litmus chaos:** 
The tutorial we have for keptn integration is a bit old and needs some fixing, nevertheless it is promising that this was previously used already.
The namespace operator installation directly on cluster via helm works good, I installed it in the keptn namespace following [this tutorial ](https://docs.litmuschaos.io/docs/user-guides/chaoscenter-namespace-scope-installation) 
I portforwarded the frontend dashboard and from there started a workflow from chaoshub templates: I added a generic pod delete experiment and ran the workflow immediately. I had to modify the pod delete to kill in keptn namespace and change the nginx app name label to specific app name or, in the example below, I used the label keptn-keptn to randomly select all pods of our installation.

_overall impressions:_
The dashboard could be potentially helpful in creating the experiments templates once so that after we can just reschedule them from there. It is easy enough to explore the experiment results in it.
![image](https://user-images.githubusercontent.com/89971034/144869697-d36b947d-5635-4ce2-b61b-305a16f03984.png)

Problem is that it's full of bugs: sometimes the chaos templates do not appear or you add an experiment and that is not saved… some workflow does not show you the templates at all even tho they are downloaded and present on your machine. If something crashed/went wrong during the experiments the chaos agent may die and the whole dashboard becomes useless for an undetermined timeframe. **Using LoadBalancer seems to solve this issues**  but the whole solution is still in beta and not 100% stable. As mentioned in their GitHub another alternative to the buggy frontend could be setting up an ingress.

Litmus is the most complete and flexible option since it allows us to define:
• Chaosexperiment: The definition of the experiment with default parameters.
• Chaosengine: Binds the experiment definition with the chaos target workload. If successful, the experiment is initiated by the Litmus operator, overriding any variables specified in the manifest file.
•Chaosresult: Displays basic information about the progress and eventually the result of the experiment.

**Chaos Mesh**
As a typical operator, a controller manager pod runs in a regular deployment and is responsible to watch for its own CRDs (NetworkChaos, IoChaos, StressChaos, PodChaos, KernelChaos and TimeChaos), which users can use to create new objects to specify and start chaos experiments.

_overall impressions:_
Installation and first experiment were extremely easy and intuitive. I followed [this tutorial](https://opensource.com/article/21/6/chaos-mesh-kubernetes) on my gke instance and started a workflow killing random keptn pods.  The dashboard is extremely intuitive for configuring experiments and allows to create workflos and schedule them repetitively. 
![image](https://user-images.githubusercontent.com/89971034/144870842-9ed575ea-60a0-471b-8431-deb3226a16a1.png)
The outcome of the experiment is not as evident and easy to interpret as Litmus: basically, the logs of the jobs are reported but I was not able to understand who was killed and if it was back up without checking on the cluster itself. 
Again all templates are there for the required tests, but it does not give possibilities to configure your own.

**summary**
Both litmus and chaosmash seems valid tools, the former requires more effort both for installation and build of the experiments but comes with a full set of examples and can be extended with custom experiments and results. The latter is ready to use and immediate, with less ability to customize.
