### ISSUE TITLE
Configuration Service: PoC of having multiple replicas with mandatory upstream

### ISSUE THREAD

**Issue by bacherfl** [keptn/keptn#6229]
Currently, the configuration service is deployed as a K8s deployment with one replica with a Persistent Volume attached to it. 
The goal of this task is to evaluate wether we can run multiplpe replicas of the configuration service, where each replica has its own volume - Operating Keptn with this configuration was not possible before because we did not have the limitation of having a mandatory upstream repository: When only the internal git repo hosted by the configuration service is used, requests for adding/retrieving resources will reach different configuration service pods which are out of sync with each other. If however those instances are synced by an upstream repository, having multiple replicas should work.

For this purpose, the following tasks need to be done:

Tasks:

- [ ] Deploy configuration-service as a StatefulSet where each replica has its own PV
- [x] Verify if everything works as expected with one replica
- [x] Verify if everything works as expected with multiple replicas of the configuration service and a mandatory upstream git repository
- [x] Document results and roadblocks that are encountered
- [x] Document where we need to adapt to these changes (docs, integration tests, etc.)

**Comment by odubajDT** [comment]
According to information what I have, there is no need to deploy configuration-service as a StatefulSet, but we can leave it as a Deployment. Due to mandatory upstream git repository, data do not need to survive pod restarts, as they can be synced with the upstream afterwards. As a volume emptyDir can be used as a cache and everything seems to work as expected. Will continue on documenting the needed changes and verifying the update.

**Comment by odubajDT** [comment]
Unit tests for this update seem to work fine (https://github.com/keptn/keptn/pull/6300). Let's see what integration tests will say https://github.com/keptn/keptn/actions/runs/1549211140

**Comment by odubajDT** [comment]
Integration tests are failing due to installation of gitea, will keep working on that and trying to resolve how to manage this. From the perspective of changing the volumes to emptyDir and increasing replicas to two is not a big deal and everything seems to be working well. 

There will be some changes regarding the whole story, as for example backup_restore_test will do not need to backup configuration data, as these will be synced from the upstream repository automatically, so there is a need to backup only database and then restore it (+ git credentials). This should be changed also in the documentation. Until now going through the code and trying to find places which should be changed.

**Comment by odubajDT** [comment]
## Conclusion
