### ISSUE TITLE
Adding Upstream git fails with Keptn 0.12.0

### ISSUE THREAD

**Issue by pcjeffmac** [keptn/keptn#6645]
Your issue may already be reported! Please search on the [issue tracker](https://github.com/keptn/keptn/issues) before creating a new one.

**Environment**

* Client OS (e.g., Linux, macOS, Windows): Linux
* Keptn Version (`keptn version`): 0.12.0
* Kubernetes Cloud Provider (e.g., GKE, AKS): Microk8
* Kubernetes version (`kubectl version`): 1.19

**Affected Component**

* [ ] Approval
* [x] Bridge
* [x] CLI
* [ ] Datastore
* [ ] Docs
* [ ] Distributor / Event Broker
* [ ] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] REST API
* [ ] Webhook
* [x] Configuration

**Describe the bug**

When attempting to add an upstream git repo, the configuration is failing.
This error is presented in the configuration service.

```bash
time="2022-01-19T21:49:40Z" level=info msg="Storing Git credentials for project dynatrace"
time="2022-01-19T21:49:47Z" level=error msg="Could not add upstream repository while updating project dynatrace" error="failed to set upstream and push for project 'dynatrace'"
```
Attempting to add the upstream git from the keptn web UI also fails.

![Screen Shot 2022-01-20 at 9 03 20 AM](https://user-images.githubusercontent.com/19553291/150375722-310252f3-dcb7-4956-8625-653eff42246d.png)

**To Reproduce**

Try adding an upstream repo using the CLI command,
CLI command: 

```bash
keptn update project $KEPTN_PROJECT --git-user=$GIT_USER --git-token=$API_TOKEN --git-remote-url=$GIT_SERVER/$GIT_USER/$KEPTN_PROJECT.git
```

1. Go to '...Project'
2. Click on '....Set Git upstream for the project'
3. Enter '...Git upstream URL, User and Token'
4. Click on "Set Git upstream"
5. Failure is presented in above screenshot.

**Expected behavior**

Expectation is that the Git upstream will be saved and link is established between keptn and the Git upstream repo.

**Current behavior**

Error occurs and the Git upstream does not get added.

**Screenshots**

**Additional context**

**Comment by grabnerandi** [comment]
I ran into the same issue when setting a git upstream to an empty git repository hosted on github.com. When I do the same thing with Keptn 0.10 it works

**Comment by bacherfl** [comment]
HI @pcjeffmac ! Thanks for reporting the issue, I'm already looking into it. Can you please also tell me if the upstream repository you were trying to add was already initialized or an empty git repository?

**Comment by bacherfl** [comment]
@grabnerandi just to clarify: did you try that with Keptn 0.12.0 as well, or were you using Keptn 0.11.x?

**Comment by bacherfl** [comment]
I just saw in the Slack channel that you were already providing the information I asked for, thx :-) I think I might have some ideas how this could have happened, but I will need some further details:

- Was the project you were trying to update created with Keptn 0.12, or did this affect projects created with an older Keptn version?

I'm asking because we had to do some changes regarding the git configuration since the git user and email were previously set using the global git config, to which the configuration service had no access is some environments - therefore we now set those config values per project. 

May I ask you to open a terminal on the configuration-service pod, using `kubectl exec`, and check the following:

```
cd /data/config/<projectName>
git config user.email
git config user.name
```

If these is not set, then I believe that is the root cause of the problem you are facing. In this case, please follow the instructions provided in the description of this issue, until we have finished the fix for that on our side: https://github.com/keptn/keptn/issues/6651 

Also, for projects created with Keptn 0.12.0 this problem should not occur

**Comment by pcjeffmac** [comment]
I started with an empty gitea repository.  Using keptn 0.12.0, fresh install.
Fresh install of all components.

**Comment by Dynatrace-Adam-Gardner** [comment]
Chiming in here, starting from nothing (no Keptn install or namespace whatsoever) it worked for me like this:

```
helm upgrade keptn keptn --install -n keptn --create-namespace --wait --version=0.12.0 --repo=https://charts.keptn.sh --set=control-plane.apiGatewayNginx.type=LoadBalancer
kubectl annotate namespace keptn keptn.sh/managed-by=keptn
kubectl label namespace keptn keptn.sh/managed-by=keptn
keptn auth
keptn status
# Get bridge username
kubectl get secret -n keptn bridge-credentials -o jsonpath="{.data.BASIC_AUTH_USERNAME}" | base64 --decode
# Get bridge password
kubectl get secret -n keptn bridge-credentials -o jsonpath="{.data.BASIC_AUTH_PASSWORD}" | base64 --decode
export GIT_USER=my_git_user
export GIT_TOKEN=ghp_*******************
export GIT_REPO=https://github.com/my_git_user/my-repo
keptn create project terraform \
--shipyard=shipyard.yaml \
--git-user=$GIT_USER \
--git-token=$GIT_TOKEN \
--git-remote-url=$GIT_REPO
```

**Comment by pcjeffmac** [comment]
The additional steps, to create the project first, with the git information does seem to work.
However, this still indicates the keptn update command is not working as expected.
No way to add the git upstream after the project has been created.
I suspect this will be fixed with the bug fix.
