### ISSUE TITLE
Core: Resource-service can be configured with SSH/HTTPS

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#6647]
## User Story

As a user, I would like to reach a private Git repository.

## Acceptance Criteria

The resource-service should open SSH or HTTPS connections towards the configured git repository.

HTTPS can be configured with:
- username
- password/token
- TLS Client Certificates
- Git Proxy (some [doc](https://gist.github.com/evantoli/f8c23a37eb3558ab8765#setting-a-global-proxy))

SSH can be configured with:
- private key (some [doc](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#adding-your-ssh-key-to-the-ssh-agent))

The service should also provide some ways to change its configuration, e.g., API, helm-value, manually changing the deployment, ... .
Open question:
 - [x] Define where the certificates and keys should be stored (e.g., config-map, secret)

## DoD 

- [ ] Document with a POC how this could be implemented, challenges, etc...

**Comment by odubajDT** [comment]
notes:
- storing TLS certificate: TSL secret, https://medium.com/avmconsulting-blog/how-to-secure-applications-on-kubernetes-ssl-tls-certificates-8f7f5751d788

**Comment by odubajDT** [comment]
Support of SSH implemented as PoC, see the linked draft pull-request.

**Comment by odubajDT** [comment]
Support for proxy implemented as PoC, please see the linked draft pull-requests

**Comment by odubajDT** [comment]
**SSH private key**

Support of SSH is fully implemented and tested. For details see the linked draft pull-requests. The private key is stored in git-credentials-<project_name> secret, as well as other auth credentials. This usage was properly tested on github.com and also gitlab.com. There are no unit or integration tests yet for this and also some additional checks are needed in CLI, if the required parameters are not set properly. Additional parameters which were added regarding this change:
- `git-private-key`
- `git-private-key-passphrase`

Also additional check, that parameter `git-remote-url` starts with `ssh://` was added. Example of a command using private key as auth method:

`keptn create project test1 --shipyard=../test/go-tests/shipyard.yaml --git-user=odubajDT --git-private-key=<path_to_private_key> --git-remote-url=ssh://git@github.com/odubajDT/test1.git --git-private-key-pass=<passphrase>`

**Comment by odubajDT** [comment]
**HTTP(S) proxy**
Support of HTTP(S) proxy is fully implemented and partly tested. For details see the linked draft pull-requests. The proxy credentials are stored in `git-credentials-<project_name>` secret, as well as other auth credentials. This usage was properly tested on github.com with the use of public proxy server. There are no unit and integration tests yet and the feature is not tested 100%. It will probably be a solution to have this merged and tested by users with their own proxy servers to see if everything is working properly. There are also some additional checks are needed in CLI and also shipyard models, if the required parameters are not set properly. Additional parameters which were added regarding this change:

- `git-proxy-url` - URL and a port to proxy server
- `git-proxy-scheme` - scheme of the proxy server
- `git-proxy-user` - user name for proxy server auth
- `git-proxy-password` - user password for proxy server auth
- `git-proxy-insecure` - disable SSL verification when connecting to the git repository URL

Example of a command using proxy:
`keptn create project <project-name> --shipyard=<path-to-shipyard-file> --git-user=<user> --git-token=<token> --git-remote-url=https://<git-url> --git-proxy-url=<server-ip>:<port> --git-proxy-scheme=(http/https) --git-proxy-insecure --git-proxy-user=<proxy-user> --git-proxy-password=<proxy-password>`

**Comment by odubajDT** [comment]
**TLS Client Certificates**

Support of TLS Client Certificates should be fully implemented, but it is not tested at all yet due to (probably) need to create an administrative git repository account and a lack of experience in this field. The TLS Client Certificate credentials are stored in `git-credentials-<project_name>` secret, as well as other auth credentials. There are no unit and integration tests yet. There are also some additional checks are needed in CLI and also shipyard models, if the required parameters are not set properly. Additional parameters which were added regarding this change:
- `git-public-cert` - public certificate

Example of a command using TLS Client Certificate:
`keptn create project <project-name> --shipyard=<path-to-shipyard-file> --git-user=<user> --git-token=<token> --git-remote-url=https://<git-url> --git-public-cert=<path-to-public-cert>`

*Note*: the feature was not tested at all, reference for the implementation is done according to docs, where `CABundle` parameter in `gitOptions` should be the one containing the certificate
