### ISSUE TITLE
MongoDB Connections: Deal with potential replica lags in mongodb

### ISSUE THREAD

**Issue by bacherfl** [keptn/keptn#6811]
When using a mongodb replica set with multiple replicas the situation can occur where, if an entry is written to the database and read shortly after, it may not be availlable yet for the reader. That is because e.g. AWS DocumentDB has a potential replica lag of ~50-100ms (see https://docs.aws.amazon.com/documentdb/latest/developerguide/replication.html).

To tackle this, we should check where we can adapt our code to avoid situations where an entry that is written to the DB is read immediately afterwards, if possible. Also, to reduce the risk of this problem, mongodb provides the option of specifying `WriteConcerns` (https://docs.mongodb.com/manual/reference/write-concern/). In our scenario, the `majority` WriteConcern may be a reasonable option. In the mongo-go-driver, this can be set as follows:

```
m.Client, err = mongo.NewClient(options.Client().ApplyURI(connectionString).SetWriteConcern(writeconcern.New(writeconcern.WMajority())))
```
We could also consider using the `writeConcern` timeout option as a helm value parameter with a default of 30s. 

This also impact the Bridge in storing/retrieving data for OAuth authentication. 

## Acceptance Criteria

- [ ] Helm value to configure the timeout - defaults 30s
- [x] MongoDatastore has the documentation updated
- [ ] The writeconcerns are implemented in both core

### Documentation
https://docs.aws.amazon.com/documentdb/latest/developerguide/transactions.html#transactions-isolation-level

https://docs.aws.amazon.com/documentdb/latest/developerguide/how-it-works.html#durability-consistency-isolation.read-consistency

https://docs.mongodb.com/manual/reference/write-concern/

**Comment by odubajDT** [comment]
According to the discussion inside the keptn-core team, we decided not to implement this feature. The reason is, that it does not make any sense to enable these options on the default installation, which runs only one replica of mongoDB. When running multiple replicas on a system with externally hosted MongoDB, there is a poccibility and also recommendation to enable any kinds of options by setting the external mongoDB connection string, as it is (will be) described in the docs[1]

PR for docs update available here [2].

[1] https://keptn.sh/docs/0.14.x/operate/advanced_install_options/#install-keptn-with-externally-hosted-mongodb
[2] https://github.com/keptn/keptn.github.io/pull/1215
