### ISSUE TITLE
ArtifactHub is not showing latest Keptn versions

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#6924]
At https://artifacthub.io/packages/helm/keptn/keptn we are only seeing 0.12.0 and older versions:

![image](https://user-images.githubusercontent.com/56065213/154744844-b8d07468-565d-4e57-9b4a-d0441c0edfde.png)

## Quick Analysis

The config is properly pointing to https://charts.keptn.sh, so that should be fine.

It looks like index.yaml of keptn/helm-charts is not updated properly: https://github.com/keptn/helm-charts/commits/gh-pages/index.yaml

**Comment by mowies** [comment]
Thanks for the issue! This happened due to a bug in the release pipeline which prevented the helm charts to be uploaded. During the manual upload we forgot do also push the index.yaml file. This should be resolved now.

It will take a few minutes for ArtifactHub to update our repo but then this should be resolved.

**Comment by christian-kreuzberger-dtx** [comment]
![image](https://user-images.githubusercontent.com/56065213/154910826-5ec3589e-ae95-479c-8bd1-a298827f4191.png)
