### ISSUE TITLE
Helm Charts for 0.12.1 and 0.12.2 are missing in helm charts repo

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#6925]
While the releases for
* 0.12.1 https://github.com/keptn/keptn/releases/tag/0.12.1
* 0.12.2 https://github.com/keptn/keptn/releases/tag/0.12.2
are on GitHub, the helm charts are not in https://github.com/keptn/helm-charts/tree/gh-pages/packages

**Comment by mowies** [comment]
Thanks for the issue! This happened due to some release pipeline changes to being backported to the 0.12.x maintenance branch. Therefore the new changes regarding how Keptn releases helm charts were not there, which in turn means that the `0.12.*` charts were not pushed.
I fixed this manually now, and it should update on ArtifactHub in a few minutes.
