### ISSUE TITLE
Ability to subscribe to action.triggered in bridge

### ISSUE THREAD

**Issue by agardnerIT** [keptn/keptn#7003]
The job-executor-service and / or webhook service should be able to respond to `action.triggered` events.

This would provide the ability to action my self-healing actions without defining custom action provider service.

**Comment by thisthat** [comment]
Hi @agardnerIT, thank you for your suggestion. I suggest that this issue will be addressed in the KEP which we are currently discussing here: https://github.com/keptn/keptn/discussions/6748
More precisely, the last point will provide a way for users to subscribe to custom events so that they can enter a subscription to `action.triggered`.
I will close this issue with a "won't do" and please, follow the discussion and provide your input on that subject :)
