### ISSUE TITLE
Enable Istio injection for namespaces, for blue/green namespaces including jmeter-service pod

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/keptn#715]
The internal service routing between blue/green services is not done correctly.

## Reproduction of the bug:
Prerequisites: 
onboarded carts service as described in the 0.4.0 docs.

Bug:
When accessing the carts.sockshop-production endpoint from another service inside the cluster the routing is done via round-robin, i.e., sometimes the blue and sometimes the green version of the service is called.

Expected behaviour: only the service that is defined in the VirtualService is called, e.g., 100% to blue.

Please note:
This does not apply to services that are exposed via an http endpoint, they are working fine. I.e., if accessing carts.sockshop-production.xx.xxx.xx.xx.xip.io everything is working as expected.

**Comment by bacherfl** [comment]
To make this work, we need Istio sidecar injection in namespaces which are configured to use blue/green deployments. A newer version of Istio with the possibility of sidecar injection has been introduced with PR #719 .
Additionally, we found that for internal routing via VirtualServices requires named ports to be used in the `Service` definitions for the services to be accessed via VirtualServices. In the VirtualService definitions, we also need to register the cluster-internal URLs (e.g. `carts` and `carts.sockshop-production.svc.cluster.local`). This will be fixed in the new version of the Helm service that's currently being developed (Issue #611 )

**Comment by grabnerandi** [comment]
Just to add to this discussion. A flexible option would be if keptn can provide both internal and external URLs as part of the cloud native event. In this case the service itself, e.g.: JMeter, Neotys, ... can decide on whether they want to test against the internal or external endpoint

**Comment by bacherfl** [comment]
The istio-injection can for now be enabled by executing `kubectl label namespace sockshop-staging istio-injection=enabled`. Therefore this can be solved with a Doc-entry instead of implementing this in the helm service for now.
