### ISSUE TITLE
Bug: Keptn public demo URL not working in quickstart

### ISSUE THREAD

**Issue by jainammm** [keptn/keptn#7280]
Hello,

In the tutorial [Explore Keptn Without Installation](https://tutorials.keptn.sh/tutorials/keptn-public-demo-011/index.html?index=..%2F..index#0), the keptn demo [URL](https://keptn.public.demo.keptn.sh/) is not working to play around with keptn.

**Describe the bug**

The URL helped new users to explore keptn without installation. 

**To Reproduce**

1. Go to https://keptn.public.demo.keptn.sh
2. See URL getting timed out

**Expected behavior**

URL providing a hosted Keptn installation along with 4 projects

**Current behavior**

URL getting timed out. 

Thanks.

**Comment by jainammm** [comment]
I'd like to assign this bug to myself on my way to get familiar with code and contribute to keptn

**Comment by jainammm** [comment]
Also, any helpful pointers to look into while debugging this would help

**Comment by agardnerIT** [comment]
:warning: Just for your information, we had to shut the public Keptn demo (https://keptn.public.demo.keptn.sh/). Apart from Log4J, there are other issues including the corrupted database and general security concerns about the instance until KEP-60 "RBAC for Keptn" is implemented. The instance will remain shut down over the Christmas break, I will update the documentation accordingly. I will also start a new repository for a new Demo Keptn setup, fully managed -as-code via GitOps.

https://keptn.slack.com/archives/CFH4VK9GT/p1640277222051900

So this is a documentation / website text issue rather than the demo being broken. @StackScribe  FYI

**Comment by jainammm** [comment]
Thanks, @agardnerIT for the information. Should I close this review for now or should I go ahead and make changes to the documentation and remove the link from here (https://tutorials.keptn.sh/tutorials/keptn-public-demo-011/index.html?index=..%2F..index#0). The video was also explanatory so we can keep that only along with the brief project descriptions.

**Comment by thisthat** [comment]
Hi @jainammm, please feel free to provide a PR to remove the link :)
