### ISSUE TITLE
Assume yes for keptn CLI

### ISSUE THREAD

**Issue by Dynatrace-Adam-Gardner** [keptn/keptn#734]
Add a debug flag to assume yes for the keptn installer.

Example usage:

```
keptn install --platform=gke -y
```

**Comment by johannes-b** [comment]
Hi Adam, 
thanks for the feature request.

Do you want to have the `-y` flag to skip the question: `Please confirm that the provided information is correct:` during the install process? 
Or do you want to execute `keptn install` without any user prompt?

**Comment by Dynatrace-Adam-Gardner** [comment]
Initially I raised the request to skip `Please confirm that the provided information is correct:`, but yes, it'd be great to run `keptn install` silently too.

So strictly speaking, this enhancement was to skip the confirmation. Let's keep it at that.

**Comment by agrimmer** [comment]
We would like to keep the confirmation as the CLI is prompting the user for information anyway.

However, the keptn CLI already provides the possibility to silently install keptn. Therefore, the user has to provide a `creds.json` file containing the required data. 
This feature is however hidden behind a flag (mostly because we do not have any documentation for it yet). 

However, if you would like to have this feature to silently install keptn, we can extend our documentation.

**Comment by christian-kreuzberger-dtx** [comment]
For me, `keptn` is already reading credentials directly from `kubectl`, it is just prompting me to confirm/enter cluster name, zone and GKE project, which I just "confirm" by pressing ENTER:
```
Installing keptn...
Please enter the following information or press enter to keep the old value:
Cluster Name [cluster-ckreuzberger]: 
Cluster Zone [us-central1-a]: 
GKE Project [my-cluster-project]: 

Please confirm that the provided information is correct: 
Cluster Name: cluster-ckreuzberger
Cluster Zone: us-central1-a
GKE Project: my-cluster-project

Is this all correct? (y/n)
```
All this information is automatically read via the `getGkeClusterInfo` method.

As Keptn is still in development, I would name this flag something like `--omit-input` or `--auto-input` or `--guess-input` (rather than `-y`), to make it clear to the CLI user that this will automagically fill in some inputs (and could potentially just overwrite things in the cluster that you are currently connected to).

**Comment by christian-kreuzberger-dtx** [comment]
A similar approach could be used for `keptn uninstall`:

```
Your kubernetes current context is configured to cluster: gke_my-cluster-project_us-central1-a_cluster-ckreuzberger
Would you like to uninstall keptn from this cluster? (y/n)
```

**Comment by dirkwall** [comment]
The Keptn CLI supports non-interactive installations. With the parameter `-c` you can provide a `creds.json` file that already contains the information that the CLI prompts you for.
See https://github.com/keptn/keptn/tree/master/installer/scripts for examples of `creds.json` templates for various platforms.
