### ISSUE TITLE
Hardcoded dependency to production tenant

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/keptn#739]
In the `deployDyntraceCommon.sh` script there is a hard dependency on ".live" tenants which has to be replaced to also support sprint tenants or managed tenants:
https://github.com/keptn-contrib/dynatrace-service/blob/develop/deploy/scripts/deployDynatraceCommon.sh#L32

**Comment by bacherfl** [comment]
The string `ENVIRONMENTID.live.dynatrace.com` is part of the Custom Resource yaml (retrieved from the [OneAgent Github Repo](https://raw.githubusercontent.com/Dynatrace/dynatrace-oneagent-operator/v0.3.1/deploy/cr.yaml), as per the instructions in the [Dynatrace docs](https://www.dynatrace.com/support/help/technology-support/cloud-platforms/kubernetes/installation-and-operation/full-stack/deploy-oneagent-on-kubernetes/) of the OneAgent, and is being replaced by the Tenant URL passed to the script. This way, we also support managed and sprint tenants. 
Currently waiting for more information about the error that occurred before this bug was reported.

**Comment by christian-kreuzberger-dtx** [comment]
@jetzlstorfer I believe this issue does not exist anymore, as `ENVIRONMENTID.live.dynatrace.com` is replaced by `$DT_TENANT` (and the tenant should include the full URL, e.g., xyz.dynatrace.some-company.com according to our instructions/README).

I'm closing this for now.
