### ISSUE TITLE
Bridge: Reword Integrations Page

### ISSUE THREAD

**Issue by agardnerIT** [keptn/keptn#7708]
**Is your feature request related to a problem? Please describe.**
The bridge integrations page could be better. Currently, if a new user saw this page, they'd leave with the impression that:

1. Keptn only integrates with 3 tools (Azure Dev Ops, Gitlab and Jenkins)
2. Only the keptn-sandbox repo exists

The page could load all integrations from artifacthub, it could at least point to the [integrations page](https://keptn.sh/docs/integrations/). It could offer a submission box for users to suggest tooling integrations that automatically generates a Github issue in the integrations repo.

Taking it one step further, it could act like a marketplace for integrations with one-click installs.

![image](https://user-images.githubusercontent.com/26523841/167740313-e82f7ccd-ba8b-4db5-978b-bef2c7cf683f.png)

**Comment by agardnerIT** [comment]
https://github.com/keptn/keptn/issues/7378

**Comment by johannes-b** [comment]
Hi @agardnerIT

totally agree with you and luckily this happened already with Keptn 0.15 - please see screenshot: 

![image](https://user-images.githubusercontent.com/729071/167776210-4eaa8bb2-e671-4d3e-83e8-2585a370b8c6.png)

* The current "Integration" page is not that prominent anymore
* A renaming happened to `Common use cases`
* Part of the support category

--- 

* https://github.com/keptn/keptn/issues/7378 is still valid (i.e., removing this button) because at this point a call to an external resource is performed that causes more troubles than value. 

* https://github.com/keptn/keptn/issues/5830 covers the same idea of pulling integrations from ArtifactHub to have a kind of in-product marketplace.

**Comment by TannerGilbert** [comment]
Closing this as the integration page was removed in #8344. Also, it's no longer planned to show the integration from ArtifactHub inside the Bridge. They'll stay at https://keptn.sh/docs/integrations/.
