### ISSUE TITLE
standard-version is deprecated, research release-please and alternatives

### ISSUE THREAD

**Issue by mowies** [keptn/keptn#7848]
standard-version was set to deprecated here: https://github.com/conventional-changelog/standard-version/releases/tag/v9.5.0

They linked to https://github.com/googleapis/release-please as a good alternative to it. We should invest some time to research if that package is a fit for us as well.

There are also already some fork of standard version available: https://github.com/absolute-version/commit-and-tag-version

**Comment by philipp-hinteregger** [comment]
## Comparison release-please and semantic-release

* Basic release process
  * Possible with both tools. Release every new version from the master just as expected, and also release patch versions on maintenance branches
  * One difference: release-please generates a release PR that has to be merged. Only after that merge can the release be published on GitHub

* pre-release
  * release-pleaese lists this option in it's readme, but the functionality is not yet implemented.
  This could mean that it might be available in the future, but that's speculation. As of now this functionality is just not available
  * semantic-release implements pre-releases, but it requires a separate branch (e.g. beta) from which the pre-release can be generated

* release types
  * release-please provides an option to configure release types
  * semantic-release doesn't allow any configuration of types (e.g. no chore)

* maintenance
  * Age: 
    * release-please: 2019
    * semantic-release: 2015
  * Development activity
    * release-please: very active development
    * semantic-release: Although a new version was released a couple of days ago. The release cycles appear to be decreasing.
  * Active contributors
    * release-please: The community appears to be rather active
    * semantic-release: Not so much contributions lately.
  * stars:
    * release-please: 1.4k
    * semantic-release: 16.2k
    
## Fallback

commit-and-tag-version: https://github.com/absolute-version/commit-and-tag-version

This is a fork of standard-version and can also be used as an alternative.
This might also be the easiest way to migrate to another tool, since it derives from standard-version.
However a possible downside might be the fact that it's not being developed for very long (since standard-version was marked depricated this year),
and is being developed by only 3 contributors, but it might be a good solution to bridge the gap until release-please implements the prerelease functionality.

**Comment by philipp-hinteregger** [comment]
Follow up ticket #8777
