### ISSUE TITLE
The systems throws an error when the project name exceeds 39 characters

### ISSUE THREAD

**Issue by Gevorgisk** [keptn/keptn#7999]
**Environment**
Keptn version: 0.13.5
Bridge version: 0.13.5

* Client OS: Windows

**Affected Component**

* [ ] Approval
* [x] Bridge
* [ ] CLI
* [ ] Datastore
* [ ] Docs
* [ ] Distributor / Event Broker
* [ ] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] REST API
* [ ] Webhook

**Describe the bug**
I create a project which has name of 39 characters, this works fine. Then I try to create a project which name has 40 characters, and the system throws 500 error after the project is created.

**To Reproduce**

1. Go to "Create a new project" page
2. Put a project name which has 40 or more characters, e.g. chars-40-does-not-work-sometext-sometex
3. Fill all other fields as necessary
4. Create the project
5. Go to Services page

**Expected behavior**
No error should happen since project is reported to be created successfully.

**Current behavior**
500 error is thrown.

![image](https://user-images.githubusercontent.com/14317365/171861310-7e979fc8-f24d-41cf-8c63-072df0312e60.png)

I tried to create a project with the name of 39 characters and it worked fine:
![image](https://user-images.githubusercontent.com/14317365/171861395-2309e6ef-a2a1-4a92-bf62-701441c37111.png)

**Screenshots**

**Additional context**

**Comment by agardnerIT** [comment]
This does not occur on the latest release `0.15.0`. Max project size is `200` and max service name size is `43` due to limitations on helm.

https://github.com/keptn/keptn/blob/d82e52d220ddd39ea50764a6691c35084cde5430/installer/manifests/keptn/charts/control-plane/templates/shipyard-controller.yaml#L106

https://github.com/keptn/keptn/blob/3e9f9b51839aa0da3fdea1372a4698d3a8a3ec97/installer/manifests/keptn/charts/control-plane/values.yaml#L176

**Comment by thisthat** [comment]
Thank you for the answer @agardnerIT 😄 
Closing the issue
