### ISSUE TITLE
Core :: Clean up qualitygates  integration test 

### ISSUE THREAD

**Issue by RealAnna** [keptn/keptn#8030]
Quality gates integration test should be only running a single full sequence, the rest of the checks can be moved as component test.

current stats for the test on gke19 are over 7 minutes:
Test_GKE/Test_QualityGates (182.02s) - keep it
Test_GKE/Test_QualityGates_SLIWrongFinishedPayloadSend (85.66s) - move as component test
Test_GKE/Test_QualityGates_AbortedFinishedPayloadSend (84.90s) - move as component test
Test_GKE/Test_QualityGates_ErroredFinishedPayloadSend (86.78s) - move as component test

DoD

- [x] One full qualitygates integration test around 100-200s long
- [x] All other test cases migrated to component/unit tests in lighthouse-service

**Comment by thisthat** [comment]
We might postpone this after KEP54 is done

**Comment by odubajDT** [comment]
Migration of `Test_GKE/Test_QualityGates_SLIWrongFinishedPayloadSend` as it tests a very uncommon scenario and for testing it it is necesarry to mock the mongodb-datastore, which is a lot of work to do just to test one corner case. Due to this we removed this test from the testsuite. We added some additional test instead.
