### ISSUE TITLE
Disallow `.only` in commits

### ISSUE THREAD

**Issue by renepanzar** [keptn/keptn#8526]
When testing only a single unit or UI test it is common to suffix a test with `.only`, like `it.only('should ...` or `cy.only(...`. This allows for executing only that one test, and nothing else. This should **never** be committed, as other tests will simply be ignored in the build run. (side note: the pipeline runs much faster in this case)

There is a [linting rule](https://www.npmjs.com/package/eslint-plugin-no-only-tests) that would allow us to check for those cases and fail the build.

Configuration would be along the lines of:

```
# .eslintrc.json

{
...
"plugins": [
  "no-only-tests"
]
"rules": [
  "no-only-tests/no-only-tests": [
    "error", {
      "block": ["describe", "it", "cy"]
    }
  ]
```

**Acceptance criteria**

- [ ] The linting rule has been added and is active during pipeline runs
- [ ] A `it.only` or `cy.only` in a pushed commit is detected and fails the build

**Comment by boranx** [comment]
I've opened a PR to address this: https://github.com/keptn/keptn/pull/8562

Is there an example of `js` test that we want to deny?

**Comment by Kirdock** [comment]
@boranx at the moment there aren't any tests in master that we want to deny. With this rule, we are making sure that we don't ignore other tests that have been excluded because another one had `.only` when merging into master.

To test it you can just put a `.only` to `describe` or `it` in our Cypress tests, which are located in `bridge/cypress/integration` or some jest tests, which are somewhere in `/bridge/client/app/**/*.spec.ts` and run the `lint:check` command with `yarn` or `npm`

**Comment by boranx** [comment]
ack, will test it and share my findings on the PRs comments, thanks!
