### ISSUE TITLE
Bridge Refresh Broken

### ISSUE THREAD

**Issue by agardnerIT** [keptn/keptn#8754]
**Environment**

* Client OS (e.g., Linux, macOS, Windows): `macOS`
* Keptn Version (`keptn version`): 0.18.1 (Safari + Firefox)

**Affected Component**
* [ ] Approval
* [x] Bridge
* [ ] CLI
* [ ] Datastore
* [ ] Docs
* [ ] Distributor / Event Broker
* [ ] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] REST API
* [ ] Webhook

**Describe the bug**
Bridge refreshes fail with this console error on localhost using port-forward.

```
[Error] Did not parse stylesheet at 'http://localhost:8080/bridge/styles.e1bda1a7137a0cde23d6.css' because non CSS MIME types are not allowed in strict mode.
[Error] TypeError: 'text/html' is not a valid JavaScript MIME type.
	promiseReactionJob
```

**To Reproduce**

1. Load the bridge: `http://localhost:8080`. Page loads fine.
2. Refresh with `Command + R` and page fails. 3. 
3. Even re-requesting the page via the URL bar fails. I have to navigate back to `http://localhost:8080` and start again4. 

**Expected behavior**
Page works

**Comment by ermin-muratovic** [comment]
Hi @agardnerIT and thanks for your feedback.

We tried to reproduce your problem and found out that the Bridge loads the stylesheet twice, once from the wrong URL and the second time from the correct path, see screenshot below.
![image](https://user-images.githubusercontent.com/6098219/186850786-1935d077-c314-463c-85ce-6fd4d76a7f96.png)

This is due to our `base-href` detection, which we run at runtime:
https://github.com/keptn/keptn/blob/e2d5e9d2a1b382ca277c6bd39b29ab98b22af48e/bridge/client/index.html#L7-L16

This behaviour could be improved maybe with https://github.com/keptn/keptn/issues/6216, but I'm not sure if we can totally get rid of the `base-href`, since our Bridge needs to allow being based not only at a domain root-level but also with a sub-path.

But anyway in our case the Bridge always loads fine although we have this known issue, also using port-forward and accessing it via `localhost:8080` everything works but sometimes the Bridge takes some seconds to load all the resources.

Could you please provide us more details how you start and access your Bridge?

**Comment by agardnerIT** [comment]
Thanks for the super quick investigation! I'm not doing anything strange (I don't think):

`helm install keptn 0.18.1` then `kubectl -n keptn port-forward svc/bridge 8080:8080`

**Comment by TannerGilbert** [comment]
Hey @agardnerIT, what command have you used for installing Keptn? Have you set the `continuousDelivery.enabled` and `apiGatewayNginx.type` as described in the installation instructions?

e.g. `helm install keptn keptn --version 0.18.1 -n keptn --repo=https://charts.keptn.sh --create-namespace --wait --set=continuousDelivery.enabled=true,apiGatewayNginx.type=LoadBalancer`

**Comment by agardnerIT** [comment]
I didn't use the `continuousDelivery.enabled` as I'm not 100% clear on what it does or why I need it but other than that, the above is the exact command I used.

**Comment by thisthat** [comment]
we couldn't reproduce this and it looks like a one-off error
