### ISSUE TITLE
Cannot Trigger "delivery" sequence from Bridge

### ISSUE THREAD

**Issue by agardnerIT** [keptn/keptn#8801]
**Environment**

* Keptn Version (`keptn version`): `0.17.1` and possibly affects `0.18.2`

**Affected Component**

* [x] Bridge

**Describe the bug**
I cannot trigger a sequence named `delivery` from the bridge.

If I rename to `delivery2` the sequence is shown in the list.

<img width="824" alt="image" src="https://user-images.githubusercontent.com/26523841/188307381-5623d3b8-a1cd-4ead-83c0-b210c229081f.png">
<img width="401" alt="image" src="https://user-images.githubusercontent.com/26523841/188307399-887fa899-244e-4c51-92fb-70dd6bf3172d.png">

-------

<img width="371" alt="image" src="https://user-images.githubusercontent.com/26523841/188307487-db519328-e5ae-4b53-baad-b5930f40401c.png">
<img width="684" alt="image" src="https://user-images.githubusercontent.com/26523841/188307524-1d079f7a-7b36-4198-a8b9-bfadaacfa48d.png">

Raising this against Keptn 0.17.1 but there's nothing in the release notes for

**To Reproduce**
Create a sequence called `delivery` and you won't be able to trigger it.
Rename the sequence to `sequence2` (or anything else) and it'll be trigger able.

**Comment by thisthat** [comment]
Hey @agardnerIT, in order to have such an option you would need to set the env var `KEPTN_INSTALLATION_TYPE= QUALITY_GATES,CONTINUOUS_OPERATIONS,CONTINUOUS_DELIVERY`. 
The last value `CONTINUOUS_DELIVERY` is the one that enables such a feature.
Via Helm, you can use `bridge.installationType=KEPTN_INSTALLATION_TYPE= QUALITY_GATES,CONTINUOUS_OPERATIONS,CONTINUOUS_DELIVERY`
