### ISSUE TITLE
Hope the cli can add a “-o” option is used to control the output field.

### ISSUE THREAD

**Issue by DomineCore** [keptn/keptn#9189]
**Is your feature request related to a problem? Please describe.**
Hope the cli can add a “-o” option is used to control the output field.
I am to have such a scene: in a script by cli to trigger the squence, and USES the trigger the "ID of Keptn context" of the command output, But now, due to the too rich output style cause I need to do some string processing operations can access to it.
```
$ keptn trigger delivery --project demoa --service demoa --stage stg --image demo
Availability of provided image cannot be checked.
Starting to deliver the service hollyberry-scene-service in project cmk with image: 20221122
ID of Keptn context: 2cdd064b-b0f8-4275-8e8d-6ac5ea87196b
```

**Describe the solution you'd like**
If you can add a -o option on the cli, is used to specify the output fields, I need can easily fix.
like this：
```
$ keptn trigger delivery --project demoa --service demoa --stage stg --image demo -o context-id
2cdd064b-b0f8-4275-8e8d-6ac5ea87196b
```

**additional context**
If you can add this option in all of the cli command, and I think we can better use in the devops pipeline keptn.

**Comment by MdSahil-oss** [comment]
@mowies I would like to work on this issue.

**Comment by MdSahil-oss** [comment]
@mowies I'm having doubt on this enhancement issue, according to the enhancement `-o` flag is needed to add in the CLI, But if `-o` is added in the CLI then there will be an ambiguity because `-o` flag already exist in the CLI as `--output` short, So I'm confused what I shoud do. Should I remove `-o` as short of `--output` flag and add `-o` flag for the enhancement ? or  should I use any other character as flag for the enhancement ?'

**Comment by thisthat** [comment]
Hey @MdSahil-oss, thanks for looking into this issue. I will close this with `not planned` since, as you suggested, there is already a `-o` flag. If users wants to filter the output, they could pipe the result with tools such as `jq` or `yq`. 
If you want to work on the CLI, you could pick up one of these two tickets :) 
- https://github.com/keptn/keptn/issues/7586
- https://github.com/keptn/keptn/issues/8102
