### ISSUE TITLE
API-Service Image 1.3.0 (api:1.3.0) Does Not Exist

### ISSUE THREAD

**Issue by WalkerSasser** [keptn/keptn#9692]
I am supporting a keptn deployment on AKS and some time last week users starting having issues in the bridge UI. While investigating the issue I noticed that the api-service pods were in a failed state, and that the api:1.3.0 image was failing to be pulled.

To test I pulled the tags on the api image from the repo on the registry (ghcr.keptn.sh/keptn/api) and I didn't see 1.3.0 in the list, but there is a latest tag. I manually updated the deployment yaml for api-service to use the api:latest tag instead of api:1.3.0 and then deleted the pods to force a re-pull and the pods spun up successfully, and the issues users were experiencing in the bridge UI were resolved.

So I wanted to post here to see if this is something that was caused by a re-tag in the registry or if we made some sort of mistake when we deployed keptn 1.3.0 with helm.

**Comment by mowies** [comment]
Hi! thanks for raising this issue. We had some issues with our version-usage proxy tool called scarf.sh which we used in v1.3.0.
The proxy was not forwarding requests reliably so we removed it again with Keptn v1.4.0 (https://github.com/keptn/keptn/pull/9678).

To solve your issue, you can just upgrade to the newer version or you can set the `glopbal.keptn.registry` helm value and set it to `ghcr.io/keptn`. That will then pull the images directly from GHCR instead of through our proxy.

**Comment by odubajDT** [comment]
Since Keptn V1 has reached EOL on December 22nd, 2023, this issue has been closed.
